### ISSUE TITLE
BrandId missing from Envelope.cs

### ISSUE THREAD

**Issue by fredmbarrett** [docusign/docusign-csharp-client#1]
DocuSign Envelopes have a BrandId property on them that is not reflected in this component's Envelope.cs class.

**Comment by InbarGazit** [comment]
@fredmbarrett  , wanted to also personally invite you to our very first developer conference to be held this coming March in San Francisco. this is exactly the opportunity to meet me and other developers in DocuSign and talk shop. And the cost is very low. See all the information here http://momentum.docusign.com/san-francisco/dev-con/?mc=devcon-github

**Comment by Ergin008** [comment]
@fredmbarrett We have released a new version of this api client which is generated from Swagger - this means that we have complete model objects now including the `brandId` in the Envelope class that you are seeking.  

I'll go ahead and close this issue for now, feel free to open new issues if anything comes up or is not working with the new version. 

Thanks,
-Ergin
