### ISSUE TITLE
Issue in Trying to Access Custom Controls from Docusign in C#.net

### ISSUE THREAD

**Issue by kranthi17** [docusign/docusign-csharp-client#100]
Hi,

I have requirement where I need to access custom controls and populate the values from database. I have defined one custom control below is the code, its name is **Address**

![custom](https://cloud.githubusercontent.com/assets/20257734/17021609/b93c2ac4-4f66-11e6-858b-85a39a00bf3e.PNG)

Now I have dragged and dropped the control on to PDF file below is the screen shot.

![data](https://cloud.githubusercontent.com/assets/20257734/17021643/f4cdbc1a-4f66-11e6-9829-3662d449842e.PNG)

Below the code I have used to get information of custom fields. But it always returns 0 for some reason. It successfully login and return accountid.

private string GetRecipientDocumentUrl(string accountId)
        {
            //var envelope = BuildEnvelopeDefinition(documents);
            var envelope = BuildEnvelopeDefinition();
            // |EnvelopesApi| contains methods related to creating and sending Envelopes (aka signature requests)
            var envelopesApi = new EnvelopesApi();
            var custList = envelopesApi.ListCustomFields(accountId, "44d25c06-4fc3-4cbe-a9d0-7e0e1e3013bc"); // **using TemplateId 44d25c06-4fc3-4cbe-a9d0-7e0e1e3013bc to retrieve custom controls**
            var summary = envelopesApi.CreateEnvelope(accountId, envelope);

            //var documentList = envelopesApi.ListDocuments(accountId, summary.EnvelopeId);
            //var customList = envelopesApi.ListDocumentFields(accountId, summary.EnvelopeId, documentList.EnvelopeDocuments[0].DocumentId);

            //var evnInfo = envelopesApi.GetEnvelope(accountId, summary.EnvelopeId);
            //===========================================================
            // Step 3: Create Embedded Signing View (URL)
            //===========================================================
            var viewOptions = BuildRecipientViewRequest(envelope);
            var recipientView = envelopesApi.CreateRecipientView(accountId, summary.EnvelopeId, viewOptions);
            return recipientView.Url;
        }

private EnvelopeDefinition BuildEnvelopeDefinition()
        {
            TemplateRole templateRole = new TemplateRole();
            templateRole.Email = "kpothireddy@ciber.com";
            templateRole.Name = "Kranthi";
            templateRole.RoleName = "Kranthi";
            //templateRole.ClientUserId = "Kranthi";

            templateRole.Tabs = new Tabs();
            templateRole.Tabs.TextTabs = new List<Text>();
            Text textTab = new Text();
            templateRole.ClientUserId = Guid.NewGuid().ToString();
            textTab.Name = "Address";
            textTab.TabLabel = "Address";
            textTab.Value = "Kranthi";
            textTab.TabId = "Address";
            templateRole.Tabs.TextTabs.Add(textTab);
            List<TemplateRole> rolesList = new List<TemplateRole>();
            rolesList.Add(templateRole);
            var envelope = new EnvelopeDefinition
            {
                TemplateRoles = rolesList,
                TemplateId = "44d25c06-4fc3-4cbe-a9d0-7e0e1e3013bc", //Prefill
                //TemplateId = "6f898104-57db-4ef1-8c74-a6cd78aa9d50",
                Status = "sent"
            };
            return envelope;
        }

below is the screen shot of custom fields are 0. Please help me out on this.
![customresult](https://cloud.githubusercontent.com/assets/20257734/17021940/dde17f8a-4f68-11e6-8d31-3f9ae36b772c.PNG)

**Comment by kranthi17** [comment]
I fixed the issue by myself, you have to use below API methods.

 var listRecipients = envelopesApi.ListRecipients(accountId, "YourTemplateID");
            var listTabs = envelopesApi.ListTabs(accountId, "YourTemplateID", listRecipients.Signers[0].RecipientId);

**Comment by MarsMayflower** [comment]
Good to see you got it working.
