### ISSUE TITLE
Calling envelopesApi.Update() to modify email subject fails when envelope is in delivered status.

### ISSUE THREAD

**Issue by joepetrakovich** [docusign/docusign-csharp-client#102]
I can't tell if this is intentional or a bug.  If the envelope is in 'delivered' status, the call to .update fails when using the current values of the envelope.  Is it okay to set it back to sent from delivered?

`Error calling Update: { "errorCode": "INVALID_REQUEST_PARAMETER", "message": "The request contained at least one invalid parameter. Value for 'status' must be 'created', 'sent' or 'voided'." }`

```
        EnvelopesApi envelopesApi = new EnvelopesApi();

        Envelope envelope = envelopesApi.GetEnvelope(AccountId, envelopeId);
        envelope.EmailSubject = emailSubject;
        envelope.EmailBlurb = emailMessage;
        envelope.PurgeState = null;
        //envelope.Status = "sent"; <--fails unless this is uncommented.  Current value is 'delivered'.

        var updateOptions = new EnvelopesApi.UpdateOptions { resendEnvelope = "true" };

        var updateSummary = envelopesApi.Update(AccountId, envelopeId, envelope, updateOptions);
```

**Comment by gsnavin** [comment]
@joepetrakovich This is a expected behaviour. You cannot change the status once its delivered.
