### ISSUE TITLE
How to use with Oauth bearer token

### ISSUE THREAD

**Issue by intergleam** [docusign/docusign-csharp-client#103]
I am struggling to use Oath and can't find any info. I can obtain bearer token by calling /restapi/v2/oauth2/token but how do I use it with EnvelopesApi etc? 
Thanks

**Comment by LarryKlugerDS** [comment]
Thank you for raising this issue. I have added an "Authentication" section to the ReadMe that discusses this issue. Please open another issue if additional information is needed.
