### ISSUE TITLE
Clarify code notes regarding baseURL

### ISSUE THREAD

**Issue by gobenb** [docusign/docusign-csharp-client#104]
There are several references to changing the base URL from demo. to www. when switching from dev to production. However, this did not work in my case. For me, it only works if I use na2 instead of www. If I use www. I get a user authentication error. 

`// instantiate api client with appropriate environment (for production change to www.docusign.net/restapi)`
`configureApiClient("https://demo.docusign.net/restapi");`

Documentation should be updated throughout to be a little more clear on that. 

For example: 
`// instantiate api client with appropriate environment (for production change to www., na2., eu1. or eu depending on how you have been setup in the Docusign portal)`

**Comment by LarryKlugerDS** [comment]
Thank you for raising this issue. I have added an Authentication section to the ReadMe file. It covers the basePath value and how to obtain it both with Legacy and OAuth authentication.

Please let us know any other comments or issues as you use the DocuSIgn system.

Thanks!
