### ISSUE TITLE
Trying to use paging functionality for listEnvelopesTest in Recipe.cs for .NET

### ISSUE THREAD

**Issue by Shyam200408** [docusign/docusign-csharp-client#106]
Hi ,
I need to use paging like functionality for getting data .My requirement is , I want to fetch 50 records per request.
For e.g. First call will bring 1 to 50 records, then second call from 51 to 100, third will 101 to 150 and so on.
I am able to get NextUri property 
Next URI: /accounts/6XXXX2/envelopes?start_position=10&count=10&from_date=9%2f15%2f2016+12%3a00%3a00+AM&from_to_status=changed. But unable to use it for paging.

Can you suggest, how to achieve it for listEnvelopesTest() method.
As I can use 
EnvelopesApi.ListStatusChangesOptions options = new EnvelopesApi.ListStatusChangesOptions()
            {
                count = 50 ,
                fromDate = fromDateStr,
                toDate = toDateStr,
            };

 EnvelopesApi envelopesApi = new EnvelopesApi();
 EnvelopesInformation envelopes = envelopesApi.ListStatusChanges(accountId, options);

There is no documentation available. Your quick help is highly appreciable.

**Comment by abhaydhar** [comment]
Were you able to achive this ?

**Comment by Shyam200408** [comment]
No

**Comment by Shyam200408** [comment]
Docusign doesn't provide paging feature, need to live with date ranges

**Comment by abhaydhar** [comment]
ok
i am also searching for any example on how to do paging in json and mvc C#

**Comment by Shyam200408** [comment]
No , you can not, raise a help Desk ticket, if you have licensed version

**Comment by abhaydhar** [comment]
ok great!. Thanks
