### ISSUE TITLE
Programmatically create PowerForms from templates

### ISSUE THREAD

**Issue by TiagoOliveiraMarques** [docusign/docusign-csharp-client#107]
Hello all,

I was investigating the API, looking for a way to create PowerForms from templates programmatically, but I couldn't find anything.

Since it is possible to create them in the docusign console, it should be simple do add some method calls to add and manage PowerForms.

![powerforms_form](https://cloud.githubusercontent.com/assets/9203181/19080158/14e6c7c2-8a4e-11e6-8b23-a1cfdbbeb4a9.png)

Is this feature planned?

Best,

**Comment by mmallis87** [comment]
@TiagoOliveiraMarques we have already started looking into this. We may release this API as beta or experimental in the coming months. I will make sure this page is up to date.

**Comment by gsnavin** [comment]
@TiagoOliveiraMarques Here is the documentation for the API to create powerform from templates using an API. Hope this helps.

https://docs.docusign.com/esign/restapi/PowerForms/PowerForms/create/

Please reopen this issue if you have any questions or concerns.
