### ISSUE TITLE
Unable to add a document to existing envelope

### ISSUE THREAD

**Issue by ajayraghuwanshi** [docusign/docusign-csharp-client#108]
hi Team,

When I try to add a pdf document to existing draft envelope in, i get below INVALID_REQUEST_PARAMETER error.

ce
{
  "errorCode": "INVALID_REQUEST_PARAMETER",
  "message": "The request contained at least one invalid parameter. A filename was not found in the Content-Disposition header ('filename=\"filename.ext\""
}
0

I can see file name in the content disposition header section filename="Yahoo.pdf", but getting error from docusign that it is not avialable.

Rest service call to add document to envelope is:
https://demo.docusign.net/restapi/v2/accounts/XXXXXX/envelopes/ccd111ed-f0e8-446f-9271-01628dd4d18d/documents/99680

PUT https://demo.docusign.net/restapi/v2/accounts/XXXXXX/envelopes/ccd111ed-f0e8-446f-9271-01628dd4d18d/documents/99680 HTTP/1.1
Authorization: SAML <<removed xaml encrypted here>>
Schwab-RRBus-PortType: DocuSignRESTInterface
Schwab-RRBus-ServiceKey: uddi:schwab.com:service:sch.core.ria.DocuSignHttpService
Content-Type: multipart/form-data; boundary=BBOOUUNNDDAARRYY
Accept: application/json
Host: intermediary-test.dev.abc.com:9049
Content-Length: 2070764
Expect: 100-continue

Content-Type: application/pdf
Content-Disposition: file; filename="Yahoo.pdf"; documentId="99680"

%PDF-1.4
%����
...
...
## ...

is above is not the proper way to call rest service to add document to draft envelope? Could you please provide me correct rest service call?
Appreciate your help.

Regards,
Ajay

**Comment by gsnavin** [comment]
@ajayraghuwanshi Sorry for the delayed response.

If you are still facing this issue, please refer to the sample code below to get you unblocked.
https://github.com/docusign/docusign-csharp-client/blob/master/test/SdkTests/UnitTests.cs#L62

Please reopen this issue if you still have any questions/concerns.
