### ISSUE TITLE
Add multiple documents to draft envelope

### ISSUE THREAD

**Issue by ajayraghuwanshi** [docusign/docusign-csharp-client#109]
hi Team,

REST service documentation to add document to draft envelope says 'Adds a document to an existing draft envelope.'. I need to add more then 1 document, which rest call I can use to add multiple documents via one rest service call? I don't see any information in the documentation.

HTTP request
PUT /v2/accounts/{accountId}/envelopes/{envelopeId}/documents/{documentId} 

Regards,
Ajay

**Comment by gsnavin** [comment]
@ajayraghuwanshi Sorry for the delayed response.

If you are still having this issue please read our API documentation below on how to add multiple documents to an existing envelope.
https://docs.docusign.com/esign/restapi/Envelopes/EnvelopeDocuments/updateList/

Please reopen this issue if you have any additional questions.
