### ISSUE TITLE
Can't get my head around composite templates

### ISSUE THREAD

**Issue by NickWhittaker99** [docusign/docusign-csharp-client#110]
I am using the following logic: (simplified)

ServerTemplate serverTemplate = new ServerTemplate();
CompositeTemplate compositeTemplate = new CompositeTemplate();

serverTemplate.TemplateId = "c081f3c4-82cf-4312-b360-4471361d7079";
serverTemplate.Sequence = "1";

compositeTemplate.ServerTemplates.Add(serverTemplate); // errors here
envDef.CompositeTemplates.Add(compositeTemplate);

It errors when trying to add the server template to the compositeTemplate.ServerTemplates list
The error is null reference it is saying that the ServerTemplates 'collection' is null.
This would be true as at that point it would be empty.

**Comment by dmartin00** [comment]
Before a Server Template can be added to a Composite Template, the Composite Template's list of Server Templates must be instantiated.

Adding this line prior to the //errors here line should resolve
`compositeTemplate.ServerTemplates = new List<ServerTemplate>()`

The same is true of the Inline Templates list.

**Comment by LarryKlugerDS** [comment]
Please re-open this issue if it is still current.
Thank you,
Larry
