### ISSUE TITLE
Same TabLabel Value Doesn't Show up in Multiple Pages using C# SDK in Docusign

### ISSUE THREAD

**Issue by Shyam200408** [docusign/docusign-csharp-client#111]
Team Docusign,
I am facing an issue, where I have many TabLabel for e.g. SellerAddress, SellerTitle. These tabs are used in 7 pages of a single PDF template. 

When I send it for signing, and opens up, last page of a template(Page7), does not show up populated data in Tabs Values, while starting pages, always shows up.I am using latest DocuSign.eSign.Api.   

Please see the screen shot: Page1, shows up all data, but Page2(which is actually Page7 in my template)

[![Page1][1]][1]

[![Page2][2]][2]
                                                   
Here is the code: // template role name must match the placeholder role name saved in your account template.  
            TemplateRole tRole = new TemplateRole()
            {
                Email = "shy@XXCXC.com",
                Name = "Shyamsundar Singh",
                RoleName = "Signer",
                Tabs = new Tabs()
                {
                    TextTabs = new List<Text>()
                {
                    new Text
                {
                    TabLabel = "username", Value = "RedPlanetNote2",
                }, new Text
                {
                    TabLabel ="SellerAddress", Value = "SellerAddress"
                }, new Text
                {
                    TabLabel ="MyAddress", Value="MyAddress",
                }
               }
                }
            }; 

Image Links
  [1]: https://i.stack.imgur.com/Vvxhf.png
  [2]: https://i.stack.imgur.com/9H5wW.png

**Comment by LarryKlugerDS** [comment]
Hi,

I don't quite understand what problem you are encountering. Your code has 3 text tab values set, and 3 text tabs are showing values on your pdf. 

The best would be to show the API call itself, by using the API logging feature. See the documentation for logging your API call: https://support.docusign.com/articles/API-Request-Logging

Thanks,
Larry

ps, you are missing a comma after 'SellerAddress'  
Presumably that's because you're just showing some code snippets.

**Comment by Shyam200408** [comment]
If you see another screenshot below first one, those 3 text boxes(See Red Text Area, which shows text Demonstration only) are still blank, while I used same Tabs for second page, but still values are blank. I hope you got my point now. Comma after a property is not mandatory, so missing comma in Selleraddress is fine.

**Comment by LarryKlugerDS** [comment]
Are you using the **exact** same field names for the second set of tabs? In that case, it should work. If it is a separate doc within the envelope, you need to set the account property for replicating information. See screenshot below (from the New DocuSign Experience's Admin tool.)

If this isn't the issue, then the next step for debugging is to send your API log as I suggest above.

![screen shot 2016-10-26 at 10 58 18 am](https://cloud.githubusercontent.com/assets/13013082/19717871/62adfdda-9b6b-11e6-96aa-9c4bb8d1911f.png)

**Comment by Shyam200408** [comment]
Okay, Thanks. I figured it out, if we are using same tabs in multiple places, need to use 
"\*" in TabLevel, see below.

new Text
                {
                    TabLabel =@"\*"+"SellerAddress", Value = "SellerAddress",
                }

**Comment by LarryKlugerDS** [comment]
Well done! Thank you for the follow-up.

And thank you for using DocuSign.
