### ISSUE TITLE
Trailing space gives unexpected error

### ISSUE THREAD

**Issue by KathyTheGreat** [docusign/docusign-csharp-client#113]
I used the TemplateAPI to get a template, but for a test, I put a blank space at the end of the templateid ( such as "5401aaa-bdc0-49ec-b2ac-a8ba317e111 ". I also tried the same template Id, but put a space at the beginning. The one with the space at the beginning gave me a TEMPLATE_ID_INVALID code, which is what I would expect. The one with the trailing space gave a 404 error. I'm curious why the trailing space resolved like that not TEMPLATE_ID_INVALID.

**Comment by LarryKlugerDS** [comment]
Hi Kathy,

Thank you for trying out various corner cases of the template id parsin. My guess is that your latter case created invalid json in the request. If you want to continue the investigation, the next step would be for you to check what was exactly sent as the json by using the api log facility

**Comment by KathyTheGreat** [comment]
I did get the log. Here is the gist of it:

404 NotFound
Content-Type: application/json; charset=utf-8
X-DocuSign-ClientTransactionId: T50959058317611812815
X-DocuSign-TimeTrack: REQ_SENT,2017-01-10T17:49:15.490Z;;REST0_Start,2017-01-10T17:49:15.5155338Z;REST0_End,2017-01-10T17:49:15.5467556Z
X-DocuSign-TraceToken: ebf0b1cc-a6d8-4488-8089-afa973273daf

{"errorCode":"RESOURCE_NOT_FOUND","message":"The URL provided does not resolve to a resource."}



So the Response.StatusDescription and the Response.status are correct. It was the Response.content here that was an empty string.


________________________________

**Comment by LarryKlugerDS** [comment]
Ok, thanks. That means that, for the specific method you were invoking, the template_id was a parameter of the url itself. And URLs can't include spaces. (They need to be encoded.)

The SDKs don't encode the template_ids (or envelope_ids, or account_ids) since correct ones never include spaces or special characters that need to be encoded.

The downside is that an incorrect template_id can cause an unexpected error response, as you found out.

We don't have a plan to fix this corner case at this time.

**Comment by KathyTheGreat** [comment]
That's fine. I just happened onto it. I would never be sending over account id or template id without "cleaning" them up if they happened to have a trailing space. I do appreciate your getting back to me. My company is working to use Docusign fairly extensively and I was fortunate enough to find this github project, which will help us out.

________________________________

**Comment by LarryKlugerDS** [comment]
Thank you for using DocuSign Kathy,

If you find any other issues or have other questions, please let us know.

Many thanks,

Larry Kluger
API Product Manager

**Comment by LarryKlugerDS** [comment]
ps. Another place to ask questions is our stackoverflow tag, "docusignapi"
