### ISSUE TITLE
Nuget package is a trainwreck

### ISSUE THREAD

**Issue by conficient** [docusign/docusign-csharp-client#114]
This is packaged in Nuget as a library but the Nuget package has the entire source code embedded in it and tries to compile the docusign client in the build. While it works on my local machine, it crashes hard on the build server we use because it's trying to reference DLLs in a /bin  folder whereas these are in /bin/Release on our build server.

I had to create my own version of the package locally to get this to work, by creating a new repository with the source code and a nuget package that only contains the `DocuSign.eSign.dll`, and references to the two dependencies in the .nuspec file

**Comment by gsnavin** [comment]
@conficient Sorry for the inconvenience. We have resolved the issue you have mentioned with version 2.1.4. Please try that and reopen this issue if it still an problem.
