### ISSUE TITLE
Which api call is needed to void an envelope

### ISSUE THREAD

**Issue by KathyTheGreat** [docusign/docusign-csharp-client#115]
Which call in the EnvelopesApi would I need to use to set the envelope status to void? I seem to be missing something.

**Comment by Ergin008** [comment]
Hi Kathy,

To void an envelope you can call the [Envelopes::update](https://docs.docusign.com/esign/restapi/Envelopes/Envelopes/update/) API with the following request body:

	{ 
		"status":"voided", 
		"voidedReason":"The reason for voiding the envelope"
	}

**Comment by KathyTheGreat** [comment]
Thank you.

**Comment by KathyTheGreat** [comment]
I tried the following and here is the error it is giving:
"The request contained at least one invalid parameter. Value for 'purgeState' must be 'documents_queued' or 'documents_and_metadata_queued' or 'documents_dequeued'."


            string envelopeId = "1d34a59e-cd55-4b63-a499-1dee3d599xxx";
            EnvelopesApi ea = new EnvelopesApi();
            DocuSign.eSign.Model.Envelope env = ea.GetEnvelope(TestConfig.AccountId, envelopeId);
            env.Status = "voided";
            env.VoidedReason = "heck, it was the wrong thing to do";

            try
            {
                EnvelopeUpdateSummary es = ea.Update(TestConfig.AccountId, envelopeId, env);
                textBox1.Text += es.ToJson() + "\r\n\r\n";
            }
            catch (ApiException ex)
            {
                textBox1.Text += ex.Message + "\r\n\r\n";
            }

**Comment by brbeaird** [comment]
What was the status of the envelope you tried to void?

**Comment by KathyTheGreat** [comment]
The status is "sent". I sent it to two people, one has signed it and I want to void it so that the second person doesn't sign.

**Comment by brbeaird** [comment]
The biggest difference I see in what you've done vs. what I have set up in my own void process is that you don't need to call GetEnvelope. You can just set up a new one - the envelopeID gets passed straight to the Update method anyway. My code looks something like this:

Envelope env = new Envelope();
env.Status = "voided";
env.VoidedReason = "Action was deleted in Risk Management";

EnvelopesApi ea = new EnvelopesApi(loginInfo.Configuration);
ea.Update(accountId, doc.EnvelopeId, env);

**Comment by KathyTheGreat** [comment]
It worked. Thank you so much for your help.

**Comment by Ergin008** [comment]
Just so you know, I believe the issue you were running into is related to another bug that will be fixed soon.  The issue is that, when you do the GetEnvelope() call it returns ALL properties of the envelope definition (whether or not that have been set for that particular envelope).  

In this case one of the properties that's coming back is `"purgeState: null"` and when you subsequently send the request to void the envelope the platforms sees the property and complains that it is set to `null`.  As mentioned, should be fixed soon.

Cheers,
-Ergin

**Comment by KathyTheGreat** [comment]
Thank you so much for the info, Ergin. I appreciate your time.
