### ISSUE TITLE
Call to list Custom Fields is coming back empty

### ISSUE THREAD

**Issue by KathyTheGreat** [docusign/docusign-csharp-client#117]
Here is what I'm doing:

            EnvelopeDefinition envDef = new EnvelopeDefinition();
            envDef.EmailSubject = "Please help me test this stuff";
            envDef.Status = "sent";
            envDef.CustomFields = new CustomFields();
            envDef.CustomFields.TextCustomFields = new List<TextCustomField>();
            TextCustomField tf = new TextCustomField();
            tf.Name = "klerrorcode";
            tf.Value = "12345";
            envDef.CustomFields.TextCustomFields.Add(tf);
            TextCustomField tf2 = new TextCustomField();
            tf2.Name = "fileid";
            tf2.Value = "9000";
            envDef.CustomFields.TextCustomFields.Add(tf2);

            EnvelopesApi ea = new EnvelopesApi();
            try
            {
                
                EnvelopeSummary es = ea.CreateEnvelope(TestConfig.AccountId, envDef);
                               
                CustomFieldsEnvelope envelp = ea.ListCustomFields(TestConfig.AccountId, es.EnvelopeId);
                List<TextCustomField> tclist = new List<TextCustomField>();
                tclist = envelp.TextCustomFields;
                foreach(TextCustomField item in tclist)
                {

                }'

Did I not add the custom fields correctly? Is not possible to get the custom fields until after the envelope is sent?

**Comment by KathyTheGreat** [comment]
Is there maybe a timing issue going on where if I had waited a few moments that it would have gotten the custom fields back? That's what it seems like to me.

**Comment by gsnavin** [comment]
@KathyTheGreat I don't see you send the signer and adding a document to the envelope definition. Once you add those, you should be able to successfully list the 2 text custom fields you added. Please reopen the issue if you still having issues. Thanks.
