### ISSUE TITLE
Configuration.Default.AddDefaultHeader same key already has been added error

### ISSUE THREAD

**Issue by obautista** [docusign/docusign-csharp-client#121]
I am using this SDK to call DocuSign.  It works just fine.  However, when there is an error somewhere when calling DocuSign (specifically the CreateEnvelope method) I receive "An item with the same key has already been added" error message on all subsequent calls.  The line of code this happens on is Configuration.Default.AddDefaultHeader().  When called initially I pass "X-DocuSign-Authentication" header value.  

The only way to get it to work again is resetting IIS.  Is there any way to clear header before adding the header value?

**Comment by gsnavin** [comment]
Can you try clearing the headers before setting your respective headers?
Configuration.Default.DefaultHeader.Clear();
