### ISSUE TITLE
Docusign Nuget v2.1.0 incorrect version? 

### ISSUE THREAD

**Issue by smcmurrin-RA** [docusign/docusign-csharp-client#123]
I was trying to use the SigningGroupsApi and after installing the v2.1.0 nuget was unable to find it. After cloning the master repo locally and manually adding the v2.1.0 dll I was able to find it.

**Comment by TuckerDowns** [comment]
Somewhat related, The nuget package appears to be very out of date on my machine. Over 1 year old.

**Comment by TuckerDowns** [comment]
I'm seeing the same issue. Tried to use add Date tabs to a Signer.Tabs object but the DateTabs container is the wrong type List<DateTime?>

**Comment by gsnavin** [comment]
@smcmurrin-RA This issue should now be fixed with version 2.1.7, please check it out. Thanks.
