### ISSUE TITLE
Unable to install v2.1.2 through NuGet (PathTooLongException)

### ISSUE THREAD

**Issue by Patman0021** [docusign/docusign-csharp-client#125]
When trying to install or upgrade from v2.1.1 to v2.1.2, i get a System.IO.PathTooLongException exception.  
Which is odd, since the only difference in path name ought to be changing the 1 to a 2...
Anyone else seeing this?
[PathTooLongException.txt](https://github.com/docusign/docusign-csharp-client/files/904056/PathTooLongException.txt)

**Comment by Patman0021** [comment]
So, if i create a project with only 19 characters in its complete path, the 2.1.2 package will install.
Maybe this has something to do with all the extra "stuff" that comes with the nuget pkg?  Shouldn't we just have the dlls?  I bet its all that code and it's directory structure that's causing the issue.

**Comment by gsnavin** [comment]
@Patman0021 This issue now should be fixed with version 2.1.4.
