### ISSUE TITLE
DocuSign 2.1.2 package needs to get cleaned up.

### ISSUE THREAD

**Issue by CoolDadTx** [docusign/docusign-csharp-client#126]
There are several issues with the current version that are causing havoc when upgrading.

1) The package contains the entire GitHub repos basically. It should only contain the contents need to deploy. This is wasting space on my build server.

2) There is a SNK for the assembly but the version that gets built is not strongly named. I believe it used to be as I have an older library that targeted v2.0.0.0 as strongly named. The problem is that when I update to the latest version while still having the older library then the EXE wants to use the unsigned version, the library wants to use the older signed version and assembly redirect I don't believe will work (haven't tried yet) because it isn't signed.

3) All versions of 2.x have a dependency on RestSharpSigned 105.2.3 or higher. But in the readme it says there is a bug in the RestSharp code that prevents uploading files. That bug hasn't been fixed yet. So upgrading to this new version pushes me to use a broken version of RestSharp.

**Comment by gsnavin** [comment]
@CoolDadTx Thanks for reporting the issues. Here is an update

1. This should be resolved with version 2.1.4
2. 2.1.4 should have these issues fixed. Please give it a try and confirm.
3. 2.1.4 version uses RestSharpSigned v105.2.2 or higher. Hope that works for you.

**Comment by CoolDadTx** [comment]
Thanks. I'll give it a try.
