### ISSUE TITLE
DateTime? instead of Date in Tabs.cs

### ISSUE THREAD

**Issue by miketonguk** [docusign/docusign-csharp-client#130]
According to the source code on github, the type of the `DateTabs` property on the `Tabs` object should be `List<Date>`. However in the nuget package v2.1.4 this property is of type `List<DateTime?>`. 

Please can this be updated to match the latest source.

**Comment by ECHDeveloper** [comment]
Same issue here but with VB.NET. Upgraded from 2.0.6 to 2.1.4 and now its asking for List(Of System.DateTime.Date?) instead of List(Of DocuSign.eSign.Model.Date), had to downgrade back to 2.0.6

**Comment by codingdawg** [comment]
Docusign development team is looking into this. Hopefully we will have fix soon.

**Comment by vadimkirikov** [comment]
There is a workaround for the issue:
custom validator
regexp: ^(([1-9])|(0[1-9])|(1[0-2]))\/((0[1-9])|([1-31]))\/((19|20)\d\d)$
tooltip: MM/DD/YYYY
error message: invalid date

**Comment by gsnavin** [comment]
@miketonguk @ECHDeveloper @vadimkirikov This should be fixed in version 2.1.7.

**Comment by codingdawg** [comment]
https://www.nuget.org/packages/DocuSign.eSign.dll/2.1.7
