### ISSUE TITLE
Get List of Tabs for Dcoument

### ISSUE THREAD

**Issue by colson22** [docusign/docusign-csharp-client#131]
When querying a recipient for a list of Tabs using the c# REST SDK version 2.1.4 from NuGet, we are getting the following error from the SignHere Class.

`{"Error converting value 1 to type 'DocuSign.eSign.Model.Number'. Path 'signHereTabs[0].scaleValue', line 7, position 23."}`

The Tabs on the document are setup like this:

`            // Create a |SignHere| tab somewhere on the document for the recipient to sign
            signer.Tabs = new Tabs();
            signer.Tabs.SignHereTabs = new List<SignHere>();
            SignHere signHere = new SignHere();
            signHere.DocumentId = "1";
            signHere.PageNumber = "1";
            signHere.RecipientId = "1";
            signHere.XPosition = "100";
            signHere.YPosition = "100";
            signer.Tabs.SignHereTabs.Add(signHere);

            // Create a Checkbox tab based on AnchorTags
            signer.Tabs.CheckboxTabs = new List<Checkbox>();
            Checkbox checkBox1 = new Checkbox();
            checkBox1.DocumentId = "1";
            checkBox1.RecipientId = "1";
            checkBox1.AnchorString = "BOR_1_CHK";
            signer.Tabs.CheckboxTabs.Add(checkBox1);`

The EnvelopesApi.ListTabs method in this test was implemented in this way:

`            //Get envelope information
            EnvelopesApi envelopesApi = new EnvelopesApi();
            EnvelopesApi.ListTabsOptions options = new EnvelopesApi.ListTabsOptions();
            options.includeAnchorTabLocations = "True";
            Envelope envInfo = envelopesApi.GetEnvelope(accountId, envelopeID);
            
            //Get recipients on envelope
            Recipients recips = envelopesApi.ListRecipients(accountId, envelopeID);

            //List tabs in documents
            foreach (Signer recip in recips.Signers)
            {
                // Offending line of code
                Tabs tabs = envelopesApi.ListTabs(accountId, envInfo.EnvelopeId, recip.RecipientId, options);`

If SignHere tabs are removed from the envelope, the EnvelopeApi.ListTabs method works properly.

We are implementing checkboxes for our Signing Requests and this is currently a blocker for us.  Your help is greatly appreciated.

Thanks,

Frank

**Comment by colson22** [comment]
I just tested this issue when using the source from GitHub, and the issue appears to be fixed.  Could you let me know when a new version of the c# sdk will be published to NuGet, the latest version 2.1.4 on NuGet still has the scaleValue defect.

Thanks,
Frank

**Comment by imranmp** [comment]
Looks like this is still a bug in the latest Nuget package (2.1.5). Anyone know when the Nuget package will be updated with the fix?

**Comment by gsnavin** [comment]
@colson22 @imranmp This should be fixed with version 2.1.7
