### ISSUE TITLE
Getting UNSPECIFIED_ERROR when specifying the EnvelopeId for a new envelope

### ISSUE THREAD

**Issue by victorvartan** [docusign/docusign-csharp-client#136]
Hard to believe that a public API returns an error like this one:

[...]Error calling CreateEnvelope: {\r\n  \"errorCode\": \"UNSPECIFIED_ERROR\",\r\n  \"message\": \"Object reference not set to an instance of an object.\"\r\n}[...]

First of all if anybody from DocuSign reads this I think that in the future you should allow API users to send any GUID as the envelope identifier and throw a descriptive error only if that GUID already exists for another envelope created on the same account.

But for now maybe a more user friendly message can be sent back then the user calls CreateEnvelopeAsync with an envelope definition that has EnvelopeId set, if not in the API at least in the client.

**Comment by codingdawg** [comment]
Can you please share your request.

**Comment by victorvartan** [comment]
It's reproducible by adding an EnvelopeId the the Create envelope request in the DocuSign Postman requests pack https://docusign.github.io/postman-esign-api-collection/ . Here's a sample request:

POST {{baseUrl}}/envelopes?merge_roles_on_draft={{merge_roles_on_draft}}&cdse_mode=%7B%7Bcdse_mode%7D%7D

Headers:
X-DocuSign-Authentication:{"Username":"{{username}}","Password":"{{password}}","IntegratorKey": "{{clientId}}"}
Content-Type:application/json

Body:
{"EnvelopeId":"00000000-0000-0000-0000-000000000000"}

Response:
{
    "errorCode": "UNSPECIFIED_ERROR",
    "message": "Object reference not set to an instance of an object."
}

And if you don't specify the EnvelopeId you get a response similar to:
{
    "envelopeId": "e9bb1a46-f183-428c-b7e7-b5c1df7db0d9",
    "uri": "/envelopes/e9bb1a46-f183-428c-b7e7-b5c1df7db0d9",
    "statusDateTime": "2017-07-19T13:38:27.6530000Z",
    "status": "created"
}
where you can see the EnvelopeId generated by DocuSign.

**Comment by codingdawg** [comment]
You are passing Invalid request to the api.

See the documentation for the CreateEnvelope api call here.
https://docs.docusign.com/esign/restapi/Envelopes/Envelopes/create

**Comment by victorvartan** [comment]
Yes, the request may be considered invalid because I was trying to set the EnvelopeId myself (to a meaningful value) instead of letting the API choose a random GUID, but my point is that a robust API or at least the client should handle situations like this and worst case throw a user friendly error with a message like "You are not allowed to set the envelope id, it's only generated by the API" or something instead of "UNSPECIFIED_ERROR Object reference not set to an instance of an object." which is not helpful especially when you have a big envelope definition like I did, with documents, recipients, tabs etc.

**Comment by codingdawg** [comment]
Thanks. We will look into this

**Comment by victorvartan** [comment]
Thanks! I think you have more important tasks but it would save the new users a lot of time (it took me some trial and error to realize that I must not send EnvelopeId in the request to get it working).
