### ISSUE TITLE
Login API returns the wrong base URL when using production Integrator Key

### ISSUE THREAD

**Issue by lamduh** [docusign/docusign-csharp-client#138]
```
AuthenticationApi authApi = new AuthenticationApi();
LoginInformation loginInfo = authApi.Login();

accountId = loginInfo.LoginAccounts[0].AccountId;
				
apiClient = new ApiClient(loginInfo.LoginAccounts[0].BaseUrl);
```

The parameter used to initialize the ApiClient should be the base url for future requests to the API. In production it should replace or postfix the www. with "na2", "eu", or "eu2", but instead it just returns the regular www base rest api. 

As a related side note, It also appeared like the base url returned had a path appended to  it which would break future API requests, e.g. the returned url was https://www.docusign.net/restapi/accounts/{accountId} and the envelopesApi.createEnvelope(...) call also appended the accounts/{accountId} piece of the path so the call went to something similar to to https://www.docusign.net/restapi/accounts/{accountId}/accounts/{accountId}/envelopes/ (or whatever the correct api endpoint for creating an envelope is) . This produced a 404.

So summary:
the base url returned from  authApi.Login(); is wrong for 2 reasons.
1. the base url doesn't have the proper subdomain of your api ("na2", "eu2", or "eu")
2. the base url isn't a base url. It has the path to the accounts api appended to it (which may be used in every request, but the way your envelopesApi class works is to accept the accountId as a parameter to each method call and build the accounts piece of the url. This leads to duplicated pieces in the url.

We currently solved this by just hardcoding the base url instead of using the way recommended in your github readme, but if for some reason we ever get assigned to a different subdomain of your service I feel that the hardcoded URL with break. At the very least your README should be clarified because this lead to a very stressful deployment (and me working until 12:30) because the issue only shows up when going to production.

**Comment by codingdawg** [comment]
The following url is a valid DocuSign base Url 
    https://www.docusign.net/restapi/accounts/{accountId}

You can obtain the list of valid  docusign sites by naviagting to this URL 
https://www.docusign.net/restapi

Here is the response from the above url.
```
<linkedSites>
 <string>https://www.docusign.net</string>
 <string>https://na2.docusign.net</string>
 <string>https://na3.docusign.net</string>
 <string>https://eu.docusign.net</string>
</linkedSites>
```

You can read the api documentation about how DocuSign defines the BaseUri  
https://docs.docusign.com/esign/

**Comment by lamduh** [comment]
I was getting USER_AUTHENTICATION_FAILED error codes until I switched the  "www" returned from the login api to "na2". If "www.docusign.net" is a valid base url, I believe there has to be an error with the generated response from the login api as it appears my production account belongs on na2, not www.

I also don't understand how https://www.docusign.net/restapi/accounts/{accountId} can be a valid base url. The envelopesApi CreateEnvelopeWithHttpInfo method (helper method for CreateEnvelope) looks as such.

```
public ApiResponse< EnvelopeSummary > CreateEnvelopeWithHttpInfo (string accountId, EnvelopeDefinition envelopeDefinition = null, EnvelopesApi.CreateEnvelopeOptions options = null)
{
    // verify the required parameter 'accountId' is set
    if (accountId == null)
        throw new ApiException(400, "Missing required parameter 'accountId' when calling EnvelopesApi->CreateEnvelope")
    var localVarPath = "/v2/accounts/{accountId}/envelopes";
    var localVarPathParams = new Dictionary<String, String>();
    var localVarQueryParams = new Dictionary<String, String>();
    var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
    var localVarFormParams = new Dictionary<String, String>();
    var localVarFileParams = new Dictionary<String, FileParameter>();
    Object localVarPostBody = null
    // to determine the Content-Type header
    String[] localVarHttpContentTypes = new String[] {
    };
    String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes)
    // to determine the Accept header
    String[] localVarHttpHeaderAccepts = new String[] {
        "application/json"
    };
    String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
    if (localVarHttpHeaderAccept != null)
        localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept)
    // set "format" to json by default
    // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
    localVarPathParams.Add("format", "json");
    if (accountId != null) localVarPathParams.Add("accountId", Configuration.ApiClient.ParameterToString(accountId)); // path paramete
    if (options != null)
    {
        if (options.cdseMode != null) localVarQueryParams.Add("cdse_mode", Configuration.ApiClient.ParameterToString(options.cdseMode)); // query parameter
        if (options.completedDocumentsOnly != null) localVarQueryParams.Add("completed_documents_only", Configuration.ApiClient.ParameterToString(options.completedDocumentsOnly)); // query parameter
        if (options.mergeRolesOnDraft != null) localVarQueryParams.Add("merge_roles_on_draft", Configuration.ApiClient.ParameterToString(options.mergeRolesOnDraft)); // query parameter
    
    if (envelopeDefinition != null && envelopeDefinition.GetType() != typeof(byte[]))
    {
        localVarPostBody = Configuration.ApiClient.Serialize(envelopeDefinition); // http body (model) parameter
    }
    else
    {
        localVarPostBody = envelopeDefinition; // byte array
    
    // make the HTTP request
    IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
        Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
        localVarPathParams, localVarHttpContentType)
    int localVarStatusCode = (int) localVarResponse.StatusCode
    if (ExceptionFactory != null)
    {
        Exception exception = ExceptionFactory("CreateEnvelope", localVarResponse);
        if (exception != null) throw exception;
    
    
    // DocuSign: Handle for PDF return types
    if (localVarResponse.ContentType != null && !localVarResponse.ContentType.ToLower().Contains("json"))
    {
        return new ApiResponse<EnvelopeSummary>(localVarStatusCode, localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()), (EnvelopeSummary) Configuration.ApiClient.Deserialize(localVarResponse.RawBytes, typeof(EnvelopeSummary)));
    }
    else
    {
        return new ApiResponse<EnvelopeSummary>(localVarStatusCode, localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()), (EnvelopeSummary) Configuration.ApiClient.Deserialize(localVarResponse, typeof(EnvelopeSummary)));
    }
    
}
```

It appears that localVarPath (declared on line 2), should be appended to the returned base path. localVarPath is set to "/v2/accounts/{accountId}/envelopes".  In my mind, it doesn't make sense that the base path returned from the logins API should include "/accounts/{accountID}" because it seems like that would lead to the following url: https://www.docusign.net/restapi/accounts/{accountId}/v2/accounts/{accountId}/envelopes"

I could be wrong in my understanding of the envelopesApi client, but I can say with certainty that using the workflow described in my first post (and in the readme of this github) did not work when switching to a production integrator key.

**Comment by gsnavin** [comment]
@lamduh Sorry for the confusion, Readme has been updated to reflect the correct way to set the base url from LoginAccounts. One more thing to note is that, its recommended to use the base url from the default account.

You need to trim the base uri that you get from login information call as show below.
https://github.com/docusign/docusign-csharp-client/blob/master/test/SdkTests/UnitTests.cs#L55

So in your case it will be something like "https://na2.docusign.net/restapi". Hope that helps.

**Comment by lamduh** [comment]
Cool. Thanks for updating the documentation so quickly.

With that said, I still have to say it seems kind of like a hacky fix to me. I would have just made the PR myself if I thought that was how you were going to handle it. The property on the account object is called "BaseUrl". Most people would assume that property would return a base url, not a string that needs to be manipulated into a base url.

**Comment by lamduh** [comment]
Got it. I am assuming that the base url property on the account means the base url of the account rather than the base url of the docusign api. I can see that. Thanks.

**Comment by gsnavin** [comment]
Glad I could help. I am going to close this issue now. Feel free to reach out if you have any other questions/concern.
