### ISSUE TITLE
MoveEnvelopes Unhandled Response Type Exception

### ISSUE THREAD

**Issue by Greatsamps** [docusign/docusign-csharp-client#141]
We have just started using this function, here is sample code for how it is being called:

````
var foldersAPI = new FoldersApi();            
foldersAPI.MoveEnvelopes(accountId, "recyclebin", 
    new FoldersRequest(new List<string>() { envelopeId }));`
````

The function does what you would expect it to, i.e the document is successfully voided on Docusign, but an exception is generated when trying to parse the response:

````
Unhandled response type. at DocuSign.eSign.Client.ApiClient.Deserialize(Byte[] content, Type type, IList`1 headers) 
at DocuSign.eSign.Api.FoldersApi.MoveEnvelopesWithHttpInfo(String accountId, String folderId, FoldersRequest foldersRequest) 
at DocuSign.eSign.Api.FoldersApi.MoveEnvelopes(String accountId, String folderId, FoldersRequest foldersRequest)
````

**Comment by elliottbenzle** [comment]
Having the exact same problem. Anyone else experiencing this?

**Comment by djangosoe** [comment]
I got the excact same error, the envelope is being moved in docusign but C# trows a "Unhandled Response Type" exception. Is there something we can do to prevent this?
When I do the same movement trough the  apieplorer I dont het a error.https://apiexplorer.docusign.com/#/esign/restapi?categories=Folders&tags=Folders&operations=moveEnvelopes

**Comment by LarryKlugerDS** [comment]
Thank you for the bug report. I have filed internal bug # DCM-3084. It is on the roadmap to be fixed, but no schedule yet. Please contact your DocuSign business or technical contact to have your organization's name added to the bug report.

Work around

In the meantime, you can call the API directly. See the [C# example](https://github.com/docusign/eg-03-csharp-auth-code-grant-core/blob/master/eg-03-csharp-auth-code-grant-core/Controllers/Eg010SendBinaryDocsController.cs) of how to do this (for a different API method).

**Comment by RajRele** [comment]
This is fixed with v3.1.5-rc. Please have a look, https://www.nuget.org/packages/DocuSign.eSign.dll/3.1.5-rc. Feel free to close this issue.

**Comment by RajRele** [comment]
https://github.com/docusign/docusign-csharp-client/pull/222

**Comment by RajRele** [comment]
This is fixed with a this release: https://github.com/docusign/docusign-csharp-client/releases/tag/v3.1.5

**Comment by snagadiya** [comment]
Getting the same problem again. Is it reopened?
