### ISSUE TITLE
Duplicate Data Label not working for Text tabs

### ISSUE THREAD

**Issue by mikev** [docusign/docusign-csharp-client#143]
DocuSign's documentation states that "fields with the same "Data Label" will populate with the same data when a recipient enters or modifies information in the field for all documents in the envelope."
See - https://support.docusign.com/en/answers/00003842

We have multiple Tabs and many are identified with the same label, as DocuSign describes.  For tabs with the same label, we pre-populate a few of them with identical value data.  However when we create the Envelope, the tabs are all empty, except for the last tab which contains the correct value.  Duplicate labels for Checkbox tabs are working correctly.

We are using the CSharp dotNet SDK to create the Envelope.  See - https://github.com/docusign/docusign-csharp-client
We noticed that the SDK is still Failing it's CI unit tests.  Could the failure to pass unit tests be related to our issue?

**Comment by dmartin00** [comment]
If you have several tabs with the same label, Data Population won't take effect unless you prefix the tab label with `\\*`

**Comment by LarryKlugerDS** [comment]
Documentation on including the \\* before the data label: [doc link](https://developers.docusign.com/esign-rest-api/guides/concepts/tabs#automatically-populating-tabs)
