### ISSUE TITLE
Bulk Api UpdateRecipients method does not work

### ISSUE THREAD

**Issue by osmant** [docusign/docusign-csharp-client#144]
Hi,

In our project we were using nuget package version 2.0.6. That version did not have support for BulkSend feature so we had to use REST api to handle our needs.

Recently we upgraded the nuget package to latest version which is 2.1.7. I noticed that [BulkEnvelopeApi ](https://github.com/docusign/docusign-csharp-client/blob/master/sdk/docs/BulkEnvelopesApi.md) have been added. So I decided to refactor our existing code and leverage the out of box methods such as `BulkRecipientsSummaryResponse UpdateRecipients (string accountId, string envelopeId, string recipientId, BulkRecipientsRequest bulkRecipientsRequest = null)`

But this method keeps returning following response.

`{
  "errorCode": "UNSPECIFIED_ERROR",
  "message": "Value cannot be null.\r\nParameter name: stream"
}`

I tried to monitor what kind of request is being made using fiddler

![image](https://user-images.githubusercontent.com/3219424/29293565-62a2efbe-8100-11e7-8400-9a338b31f4e8.png)

Therefore, we are unable to use the new methods in latest version. In current solution, we directly use REST api and that works as expected. When we were building that solution we use following two links.

1. [Add or Replace an Envelope Bulk Recipient File](https://www.docusign.com/p/RESTAPIGuide/Content/REST%20API%20References/add-replace-envelope-bulk-recipient-file.htm) : to understand how to call api

2. [General Requirements for the Bulk Send CSV file](https://www.docusign.com/DocuSignHelp/Content/create-recipient-list.htm) : To figure out how to build csv file.

At the end, working solution is making following http request.

![image](https://user-images.githubusercontent.com/3219424/29294031-38e30054-8102-11e7-8e2b-88cea29251bf.png)

Two differences between 2 http request is Content-Type property. 

- In  the working solution, Content-Type is provided as `text/csv`, but c# api set it as `application/json`
- In the working solution, request body is in Csv format, but c# api set it in json format.

Is there something I am missing in C# api to be able to make a successfull request or is there a bug ?

Thank you.

**Comment by larrykluger** [comment]
Thank you for this issue report! I'll leave it to my C# expert colleagues to respond to your specific question. In the meantime, we're starting to look into different ways to improve our bulk send capability and API. If you'd like to discuss, please contact me via apihelp@docusign.com. Thanks, Larry

**Comment by RajRele** [comment]
Hi, this has been resolved with our new release candidate version [v3.1.3-rc](https://www.nuget.org/packages/DocuSign.eSign.dll/3.1.3-rc)

Let us know if this resolves your issue. Thanks

**Comment by RajRele** [comment]
Thanks, I am closing this as resolved. Please open a new issue if you have any questions.
