### ISSUE TITLE
Problem with ListStatus

### ISSUE THREAD

**Issue by Lyndsay-G** [docusign/docusign-csharp-client#146]
I'm using the SDK via the NuGet package, and I'm running into a problem with ListStatus.  What I want to do is pull the statuses for a list of Envelope Ids, which I'm trying to do like this:

**var apiInstance = new EnvelopesApi();**
**var envelopeIdsRequest = new EnvelopeIdsRequest();** 
**List<string> envelopeIds = new List<string>();**

**envelopeIds.Add("envelope-id-1");**
**envelopeIds.Add("envelope-id-2");**

**envelopeIdsRequest.EnvelopeIds = envelopeIds;**
**EnvelopesInformation result = apiInstance.ListStatus(accountId, envelopeIdsRequest);**

Running this generates the request that I would expect from having looked at the API documentation [https://docs.docusign.com/esign/restapi/Envelopes/Envelopes/listStatus/](url):

**PUT https://demo.docusign.net/restapi/v2/accounts/account-id/envelopes/status **HTTP/1.1**
**X-DocuSign-SDK: C#**
**X-DocuSign-Authentication: {"Username":"my_username", "Password":"my_password",** **"IntegratorKey":"my_integrator_key"}**
**Accept: application/json**
**User-Agent: Swagger-Codegen/2.1.0/csharp**
**Content-Type: application/json**
**Host: demo.docusign.net**
**Content-Length: 193**
**Accept-Encoding: gzip, deflate**

**{"envelopeIds":["envelope-id-1","envelope-id-2"]}****

This request returns an error: "The request contained at least one invalid parameter. Query parameter 'from_date' must be set to a valid DateTime, or 'envelope_ids' or 'transaction_ids' must be specified."

If I edit the request like this, it works, even though this doesn't match the documentation, and isn't what's generated by the SDK:

**PUT https://demo.docusign.net/restapi/v2/accounts/account-id/envelopes/status?envelope_ids=envelope-id-1,envelope-id-2 HTTP/1.1**
**X-DocuSign-Authentication: {"Username":"my-username", "Password":"my-password",** **"IntegratorKey":"my-integrator-key"}**
**Accept: application/json**
**User-Agent: Swagger-Codegen/2.1.0/csharp**
**Content-Type: application/json**
**Host: demo.docusign.net**
**Content-Length: 193**
**Accept-Encoding: gzip, deflate**

**{"envelopeIds":[]}**

And yes, the request body containing the empty list of envelope Ids seems to be required!

So, what is going on?  Am I not using the SDK correctly, or missing something from the API documentation?  Or what?

**Comment by jmcleman** [comment]
The Rest spec and API do not agree on this call. The ListStatusWithHttpInfo method needs to be modified to add teh query paramaters as follows to work:
 if (envelopeIdsRequest != null && envelopeIdsRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(envelopeIdsRequest); // http body (model) parameter
                localVarQueryParams.Add("envelope_ids", Configuration.ApiClient.ParameterToString(envelopeIdsRequest.EnvelopeIds));//JM change for API 
            }
            else
            {
                localVarPostBody = envelopeIdsRequest; // byte array
            }

**Comment by Hendel81** [comment]
This is still an issue and has been open for almost a year, any reason why it hasn't been assigned yet.
I don't see a way of using the SDK in order to return just the envelope ID I want.

**Comment by RajRele** [comment]
Closing this. We have a solution mentioned #196, will update that with our progress.
