### ISSUE TITLE
Authentication with new service Integration method using JWT

### ISSUE THREAD

**Issue by VishmayShah** [docusign/docusign-csharp-client#148]
Hello All,

How can I use c# client SDK for Service Integration Authentication?
it is now the recommended way.

https://docs.docusign.com/esign/guide/authentication/auth_overview.html#service-integration-authentication
https://docs.docusign.com/esign/guide/authentication/oa2_jwt.html
https://www.docusign.com/blog/dsdev-docusign-developers-look-inside-new-authentication-apis/

Thanks

**Comment by mmallis87** [comment]
@gsnavin is working on adding JWT support to this SDK, so it’s coming very soon!

**Comment by larrykluger** [comment]
In the meantime, you can obtain a Bearer Token by using the JWT OAuth flow yourself. Eg see https://github.com/dvsekhvalnov/jose-jwt  Then add the token to this library:

    Configuration.Default.AddDefaultHeader("Authorization", "Bearer " + token);

**Comment by VishmayShah** [comment]
@mmallis87, thanks for the reply.
I was looking for something that if user doesn't want to share his password in API, still we can use his email id as sender,
By the way I solved my issue with Legacy header using SOBO.

Let me know once you add JWT support to this SDK is live so I can close this issue.

**Comment by gsnavin** [comment]
@VishmayShah I have added the JWT authentication support C# SDK. There are some unit test cases added to show the usage. There is a sample code on in readme too. Let me know if you still have further questions/concerns.
