### ISSUE TITLE
Call to CreateEnvelope calling the wrong URL in V2.1.8

### ISSUE THREAD

**Issue by t-davies** [docusign/docusign-csharp-client#151]
Creating an envelope from V2.1.8 fails.
The URL I see in our logs has the path duplicated for some reason, the response is a 404.

**Environment**
Azure Web App

**.NET version**
.NET Framework 4.5.2

**Expected**
POST https://demo.docusign.net/restapi/v2/accounts/12345678/envelopes

**Actual**
POST https://demo.docusign.net/restapi/v2/accounts/12345678/v2/accounts/12345678/envelopes

**Comment by gsnavin** [comment]
@t-davies When you instantiate/update the ApiClient you need to trim the base URL as show in the readme. Here is the line below

// Update ApiClient with the new base url from login call
string[] separatingStrings = { "/v2" };
apiClient = new ApiClient(loginInfo.LoginAccounts[0].BaseUrl.Split(separatingStrings, StringSplitOptions.RemoveEmptyEntries)[0]);

Hope that solves the issue. I am closing the issue for now. Please reopen it if you still have other questions.

**Comment by t-davies** [comment]
Ahh, yep, thanks.
Does 2.1.7 behave differently then? I downgraded and everything started working again.
