### ISSUE TITLE
Unable to update or retrieve brand logo

### ISSUE THREAD

**Issue by conficient** [docusign/docusign-csharp-client#153]
I am trying to figure out how to use the API to set or get the logo for brands. The rest API has methods for doing this, but there is nowhere to provide the logo data or retrieve it, or describe the formats to provide.

The `CreateBrand` method appears to support logos but the [documentation](https://docs.docusign.com/esign/restapi/Accounts/AccountBrands/create/) does not explain how to do this. I tried specifying a URL in `BrandResourceUrls` but there were no logos on the resulting brand that was created. The examples are useless because all strings have "sample string xxx" in giving no clues on what to do. I also tried looking at the code and the unit tests, but again no clues.

I tried to use the `UpdateBrandLogo` method - but there is nowhere in the API method to provide the logo or image data?

I looked at the `GetBrandLogoByType` but this returns? I also tried `GetBrandLogoByTypeAsyncWithHttpInfo` - this returns the `ApiResponse` but the data is null, even though I know the test brand has a logo.

Also see my related [StackOverflow question](https://stackoverflow.com/questions/47454697/managing-docusign-brand-logos-via-api) - so far not even a comment, let alone an answer.

I am posting this as an issue here as I believe the brand logo functionality in csharp-client is broken since the code generated from Swagger does not seem to implement the necessary functionality.

**Comment by conficient** [comment]
Having queried on StackOverflow and played around with the API using postman it looks like the problem lies with the swagger codegen (or how that is used) when a request returns content or requires body content uploaded as part of a request.

**Comment by RajRele** [comment]
Similar to #202.
