### ISSUE TITLE
sending template json instead of calling template

### ISSUE THREAD

**Issue by GameScrub** [docusign/docusign-csharp-client#155]
Is there a way to design complex templates using the docusign website, then downloading the json template file and sending that json file from c#?  We don't want to manage templates on the website, just use it for initial template creation and do versioning and source control on our codebase.

Is this possible with the current sdk?

**Comment by mmallis87** [comment]
Most of the template editing can be done through the SDK (and API), although you will have to parse the json file and construct the templateDefinition using some custom C# code. [TemplatesApi](https://github.com/docusign/docusign-csharp-client/blob/master/sdk/src/DocuSign.eSign/Api/TemplatesApi.cs) has many utility files to manipulate templates.

See the docs for information about specific methods: https://docs.docusign.com/esign/restapi/Templates/
How-to send a document for signature using templates: https://www.docusign.com/developer-center/recipes/request-a-signature-via-email-using-a-template
More about templates: https://www.docusign.com/developer-center/explore/features/templates

**Comment by GameScrub** [comment]
This seems to work for me now.

`var definition = JsonConvert.DeserializeObject<EnvelopeDefinition>(ContractDefinition);`

After that loads I can set the templateid to string.empty, populate the tabs with data and sends fine.

**Comment by LarryKlugerDS** [comment]
I'm glad your solution is working for you. 

If you have further API usage questions, please open a new issue here or (better) on StackOverflow with the `docusignapi` tag.
