### ISSUE TITLE
ListTemplates with ListTemplatesOptions { "folder = " } not working if it's a name

### ISSUE THREAD

**Issue by reaua001** [docusign/docusign-csharp-client#160]
All,

I have read and coded the following listed in documentation https://docs.docusign.com/esign/restapi/Templates/Templates/list/

In above the following is shown

folder string
The query value can be a folder name or folder ID. The response will only return templates in the specified folder.

when I use folder id it's found but nothing is returned when I use folder name. 

**I have verified that folder name matches** 
Also tried to use a "[{"name": "GTP"}]" but that will result in a error...

C#

`templatesApi.ListTemplates(AccountId, new TemplatesApi.ListTemplatesOptions { sharedByMe = "true", folder = "bba1e719-1f38-4a1a-a8cc-03c4960de336" }); // works
`

`templatesApi.ListTemplates(AccountId, new TemplatesApi.ListTemplatesOptions { sharedByMe = "true", folder = "GTP" }); // no results
` 
Help!

**Comment by LarryKlugerDS** [comment]
I see that you also asked your question on [StackOverflow](https://stackoverflow.com/questions/47914986/docusign-template-list-folder-by-name-not-working/54747475). I have provided a full answer there.

Thanks,
Larry
