### ISSUE TITLE
Support for API limit headers (X-RateLimit)

### ISSUE THREAD

**Issue by brbeaird** [docusign/docusign-csharp-client#162]
Would it be possible to expose the X-RateLimit headers in some of the envelopeAPI responses? In some cases I need to send pretty large numbers of docs out at once, and it would be helpful if I could check the API limit counts, which should be in the create envelope header.

**Comment by RajRele** [comment]
Hi @brbeaird, we already have support for exposing our the headers information.

For example, if you are using EnvelopesApi, just switch to using the "WithHttpInfo" method which returns a Type of ApiResponse. The ApiResponse type has the Data and Headers information which you need.

```
// Get the Envelope Summary using the "WithHttpInfo" method
ApiResponse<EnvelopeSummary> envelopeSummary = envelopesApi.CreateEnvelopeWithHttpInfo({Your Account Id}, {Envelope Def});

// to get the EnvelopeSummary use the Data property
EnvelopeSummary envelopeSummary = envelopeSummary.Data;

// to get the headers use the Headers property
var headers = envelopeSummary.Headers;
```
Headers property looks like this:
<img width="776" alt="screen shot 2018-11-21 at 4 41 36 pm" src="https://user-images.githubusercontent.com/26106738/48875252-a698f500-edac-11e8-8f26-8e281cb487a9.png">

Headers have the key values like

> X-RateLimit-Limit

 and 

> X-RateLimit-Remaining


Hope this helps. Let us know.
Thanks,

**Comment by brbeaird** [comment]
Interesting. Not sure how I missed that. Thanks.
