### ISSUE TITLE
What is the difference between Envelope and EnvelopeDefinition? 

### ISSUE THREAD

**Issue by leoseccia** [docusign/docusign-csharp-client#164]
The classes Envelope and EnvelopeDefinition seeems very similar... Why the separation? 
Why no inheritance?

**Comment by leoseccia** [comment]
And EnvelopeSummary...?

**Comment by LarryKlugerDS** [comment]
Thank you for your suggestion. The SDK is auto-generated from the API's Swagger file.  Unfortunately, using inheritance is beyond the current capabilities of the program generator.
