### ISSUE TITLE
Recipients types would benefit from inheriting from a common base class

### ISSUE THREAD

**Issue by leoseccia** [docusign/docusign-csharp-client#167]
Recipient types such as `Agents, CarbonCopies, CertifiedDeliveries, Editors, Intermediaries and Signers` would benefit from inheriting from a common base class since they have so much in common. 

I think in the old API, they used to be all the same type: `Signer`

**Comment by LarryKlugerDS** [comment]
Thank you for the suggestion. The SDK is auto-generated from the Swagger file, so implementing your suggestion would be difficult. The engineering team has decided that it would not be appropriate to implement at this time.
