### ISSUE TITLE
Unexpected PEM type exception

### ISSUE THREAD

**Issue by awerber** [docusign/docusign-csharp-client#168]
I'm using the code in the example,and I get the error message 'Unexpected PEM type' after the call to piClient.ConfigureJwtAuthorizationFlow(integratorKey, userId, oauthBasePath, privateKeyFilename, expiresInHours).

I'm using the Integrator key from the https://admindemo.docusign.com/api-integrator-key screen for my account.

UserID is API user name from the same web page (I'm using the long string, not my email address)

oauthBasePath is https://demo.docusign.net/restApi/v2/accounts/{accountId}/envelopes where I substitute {accountId} with the number I see in my profile drop down. The account ID is a 7 digit number.

The private key file name is the name of a file that has the private key that I generated as part of an RSA key pair. This value is being read into the code properly. The value of 'key' in private static RSA CreateRSAKeyFromPem(string key) is from my file.

I would appreciate any help with this.

**Comment by awerber** [comment]
Follow up - I tried sending NULL for the key file, now I get another exception with the message "The specified Integrator Key was not found or is disabled. An Integrator key was not specified". 

This comes in the method  public ApiResponse< LoginInformation > LoginWithHttpInfo (AuthenticationApi.LoginOptions options = null).

**Comment by mmallis87** [comment]
@awerber oauthBasePath should be "account-d.docusign.com" (in demo/sandbox) and the PEM private and public files SHOULD be generated from https://admindemo.docusign.com/api-integrator-key, under that specific integrator key that you are using (RSA keys modal). Make sure to store the two PEM files to a location that is accessible from your codebase.

A full example of using JWT flow is here: https://github.com/docusign/docusign-csharp-client/blob/master/test/SdkTests/JwtAuthUnitTests.cs and the config file is here: https://github.com/docusign/docusign-csharp-client/blob/master/test/SdkTests/TestConfig.cs

**Comment by awerber** [comment]
Thanks, I’ll give this a try next week.

Regards,
Andrew Werber

**Comment by FJBDev** [comment]
I encountered the same issue and resolved it by using the following code :

testConfig.PrivateKeyFilename = File.ReadAllText("./private.pem");

**Comment by RajRele** [comment]
Please checkout our latest releases and open new issue if this still persists...

**Comment by souzasilvio** [comment]
I solve this with the following line:
var privateKeyStream = System.Text.Encoding.UTF8.GetBytes(File.ReadAllText(testConfig.PrivateKeyFilename));
OAuth.OAuthToken tokenInfo = apiClient.RequestJWTUserToken(testConfig.clientId, testConfig.UserId, testConfig.OAuthBasePath, privateKeyStream, testConfig.ExpiresInHours);
