### ISSUE TITLE
ListStatus not working - possible parameter mismatch or API bug?

### ISSUE THREAD

**Issue by leoseccia** [docusign/docusign-csharp-client#169]
This code does not work...
```
EnvelopesApi envelopesApi = new EnvelopesApi();
var info = envelopesApi.ListStatus(AccountId, new EnvelopeIdsRequest(new List<string>() { EnvelopeId }));
```
Tracing the call in Fiddler shows that the request contains the envelope ids parameter as
`{"envelopeIds":["4491782b-1e52-477f-adad-d5dff4419319"]}` 

And the error returns 
```
{
  "errorCode": "INVALID_REQUEST_PARAMETER",
  "message": "The request contained at least one invalid parameter. Query parameter 'from_date' must be set to a valid DateTime, or 'envelope_ids' or 'transaction_ids' must be specified."
}
```

The parameter would appear to be mismatching (ie. `envelopeIds `v `envelope_ids`) however when I change it to match the response error and replay the request from Fiddler, the call still fails with the same error.

**Comment by moraleslos** [comment]
Exact same issue here.  Using 2.1.8.  

@leoseccia Have you figured out how to make it work?

**Comment by leoseccia** [comment]
No sorry - I just abandoned it. I haven't tried anything else since I posted the issue however by looking at the API doc, it seems peculiar to me that this is a `PUT ` rather than a `GET`... It is possible that this is an API documentation error than then propagated to the consumer API library. Who knows...

**Comment by avvi00** [comment]
Also hit this in 2.1.9. The API docs for from_date seem to be inline:

> The date/time setting that specifies when the request begins checking for status changes for envelopes in the account.
> 
> This is required unless parameters envelopeIds and/or transactionIds are set.

**Comment by RajRele** [comment]
Refer to #196

**Comment by RajRele** [comment]
Closing this. We will update #196 with our progress.
