### ISSUE TITLE
from where i get this      string oauthBasePath = "[OAUTH_BASE_PATH]"; and  string privateKeyFilename = "[PRIVATE_KEY_FILENAME]"; and  string userId = "[USER_ID]"; // use your userId (guid), not email address

### ISSUE THREAD

**Issue by developerpp** [docusign/docusign-csharp-client#172]
from where i get this      string oauthBasePath = "[OAUTH_BASE_PATH]"; and  string privateKeyFilename = "[PRIVATE_KEY_FILENAME]"; and  string userId = "[USER_ID]"; // use your userId (guid), not email address

**Comment by RajRele** [comment]
Once you create a SandBox account you should be able to create Integrator Keys and RSA Private Keys for JWT Authentication...

Check our test project to see how we use oauth base path and other properties.
https://github.com/docusign/docusign-csharp-client/tree/master/test

Follow Quickstart guide here and let us know if you still have questions.
https://developers.docusign.com/esign-rest-api/guides

**Comment by RajRele** [comment]
@developerpp, Closing this issue, feel free to open a new issue if you have any questions. 
Thanks
