### ISSUE TITLE
.NET Core: Envelope creation timed out

### ISSUE THREAD

**Issue by denadr** [docusign/docusign-csharp-client#173]
I'm using the inofficial .NET Core DocuSign SDK (https://github.com/mitchdowd/DocuSign.NetCore) to call the API and ran into the same issue as reported in this StackOverflow question: https://stackoverflow.com/questions/47666100/docusign-esign-createenvelope-requests-timing-out

When calling `CreateEnvelope` of the `EnvelopesApi` class I'm getting an `ApiException` `The operation has timed out.` from `DocuSign.eSign`:

`Error calling CreateEnvelope: The operation has timed out.`

I just tried to fix it the same way as provided by the answer in the linked question (https://stackoverflow.com/a/47685989/5373084). But the timeout doesn't seem to be applied, since the request always cancels after a duration of 100 secs (the default timeout of DocuSign ApiClient Configuration). That's some kind of weird because I can validate the configured timeout values within `Configuration`, `ApiClient` and internal `RestClient` objects. I also checked the eSign version, but this already points to 2.1.0 as dictated:

    using DocuSignConfig = DocuSign.eSign.Client.Configuration;

    ...

    Console.WriteLine(DocuSignConfig.Version); // 2.1.0

    var envelopesApi = new EnvelopesApi();
    envelopesApi.Configuration.Timeout = (int)TimeSpan.FromMinutes(5).TotalMilliseconds; // 300000 [ms]

    Console.WriteLine(envelopesApi.Configuration.Timeout);                         // 300000 [ms]
    Console.WriteLine(envelopesApi.Configuration.ApiClient.Configuration.Timeout); // 300000 [ms]
    Console.WriteLine(envelopesApi.Configuration.ApiClient.RestClient.Timeout);    // 300000 [ms]

    Console.WriteLine(DocuSignConfig.Default.Timeout);                         // 300000 [ms]
    Console.WriteLine(DocuSignConfig.Default.ApiClient.Configuration.Timeout); // 300000 [ms]
    Console.WriteLine(DocuSignConfig.Default.ApiClient.RestClient.Timeout);    // 300000 [ms]
    
What am I missing?

Any hint would be really appreciated!

Thanks in advance!

**Comment by ShunnyBunny** [comment]
Did you figure it out?

**Comment by RajRele** [comment]
Hi @denadr, we have recently released a .Net Core / Standard 2.0 version. The library which you are referring to is not official, so I would recommend to use the official .Net Standard version and open a issue if you have any concerns. Thanks.

**Comment by marouanSalem** [comment]
p'l kttltkttlltltltktkt okk  pokrk orktok okoko op$$& opkkoooorroror
