### ISSUE TITLE
SignHere tabs not adding on document while creating signer recipient

### ISSUE THREAD

**Issue by pranavd** [docusign/docusign-csharp-client#174]
I am creating Signer Recipient from REST C# SDK using **EnvelopesApi** "**CreateRecipient**" method. I am also putting SignHere tabs for the respective recipient on the basis of anchor text, but the tabs are not displayed in the signing email.
Am I missing anything?

**Comment by LarryKlugerDS** [comment]
Best would be for you ask your question on StackOverflow with the `docusignapi` tag. When you ask, include the API request as received by DocuSign. See [tracing docs](https://support.docusign.com/guides/ndse-user-guide-api-request-logging) to get a copy of the trace.

There are more people watching the StackOverflow docusign feed. In any case, next step is to provide a copy of the API call/response trace.

**Comment by RajRele** [comment]
Hi @pranavd, Please look into this article https://developers.docusign.com/esign-rest-api/guides/features/tabs and look for "Tab Placement Method 2: Auto-Place (Anchor Tagging)".
Thanks, Let us know if your issue is resolved.
