### ISSUE TITLE
Readme example issue

### ISSUE THREAD

**Issue by ShunnyBunny** [docusign/docusign-csharp-client#177]
I have emailed the support team about this problem, and they said there is no problem. I hope I am not crazy or anything.

Under the Readme
To send a signature request from a template using legacy authentication: (section)

`// Update ApiClient with the new base url from login call
string[] separatingStrings = { "/v2" };
apiClient = new ApiClient(loginInfo.LoginAccounts[0].BaseUrl.Split(separatingStrings, StringSplitOptions.RemoveEmptyEntries)[0]);`

The "new ApiClient" here is assigned to the apiClient variable which is no longer referenced later in this example. The EnvelopesApi() later in the example is using an apiClient with out the new baseUrl we got from making the login call.

If you have resharper installed, you should easily spot this reference problem. If this is intended, please add comments to describe why. This adds so much confusion to first time user.

**Comment by RajRele** [comment]
Sorry that you were facing these issues, we have updated the [ReadMe](https://github.com/docusign/docusign-csharp-client/blob/master/README.md) to showcase latest examples... Please open a new issue if you still have any challenges...
