### ISSUE TITLE
C# client library uses TLS 1.0 while DocuSign requires TLS 1.1

### ISSUE THREAD

**Issue by bstr413** [docusign/docusign-csharp-client#178]
Our organization ran into a recent issue with this C# client library. Due to it being built using .NET 4.5, it uses TLS 1.0 by default. DocuSign now requires TLS 1.1 or higher in their demo environment and will require it in their production environment on June 25: https://support.docusign.com/en/articles/End-of-TLS-1-0-and-weak-cipher-support.

You can fix this client library by adding in the following line of code before each call to DocuSign in the library:
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`

As a temporary workaround, you can also change the registry keys on every server that uses this library as mentioned here: https://support.solarwindsmsp.com/kb/solarwinds_n-central/How-To-Force--NET-to-use-TLS-1-2.

**Comment by LarryKlugerDS** [comment]
Hi @bstr413,

Thank you for raising the issue and solution.

I will be updating the ReadMe with your solution. We will also be updating the SDK itself to included the fix.

Regards,

Larry Kluger
DocuSign

**Comment by FJBDev** [comment]
I raised the issue [here ](https://stackoverflow.com/questions/50592783/tls-issue-using-the-demo-site) as well.
However, the solution is not to ask to use TLS 1.2 but  instead, to disable SSL3 and TLS1.0. That way, no code change will be needed to be done when TLS1.3 is available.

SecurityProtocolType[] securityProtocolTypes =
				(SecurityProtocolType[])Enum.GetValues(
					typeof(SecurityProtocolType));

			SecurityProtocolType protocolVersions = new SecurityProtocolType();
			foreach (SecurityProtocolType securityProtocolType in
				securityProtocolTypes)
			{
				protocolVersions |= securityProtocolType;
			}
			// SSL 3.0 and TLS 1.0 have to be turned off
			protocolVersions &= ~SecurityProtocolType.Ssl3;
			protocolVersions &= ~SecurityProtocolType.Tls;

			ServicePointManager.SecurityProtocol = protocolVersions;

**Comment by RajRele** [comment]
This is resolved in all versions >= [v2.1.10](https://github.com/docusign/docusign-csharp-client/blob/master/CHANGELOG.md#v2110---esignature-api-v18102---6132018)
