### ISSUE TITLE
Issues with example test program, source code not valid

### ISSUE THREAD

**Issue by Rowdster** [docusign/docusign-csharp-client#184]
In the example code provided here, there are a few issues.  https://github.com/docusign/docusign-csharp-client/blob/master/README.md

1. It seems to require the latest rc, 2.2.0-rc in order to get using DocuSign.eSign.Client.Auth;
2. There are two references to "            string accountId = string.Empty;"
3. privateKey is not declared.  

Would it be possible to update this code to something that can compile?

**Comment by RajRele** [comment]
@Rowdster, thanks for you comments, we have updated the ReadMe code example.
Yes, it does require you to select and install the Prerelease version from NuGet.

Thanks,
Bharat
