### ISSUE TITLE
RestSharp Signed longer being updated

### ISSUE THREAD

**Issue by ShunnyBunny** [docusign/docusign-csharp-client#189]
If I understand correctly, going forward restsharp won't have a signed version anymore.
"The RestSharp package is now signed so there is no need to install RestSharp.Signed, which is obsolete from v160.0.0." -restsharp github

My RestSharpSigned is still on 105.2.3
but the Docusign SDK seems to be trying to use the regular rest sharp anyway. Which I just updated to 106.3.1
But I am getting a error and it is probably cause by having two different version of Restsharp installed.

**Comment by RajRele** [comment]
Yes we have updates our RestSharp with the .Net Standard release. Please checkout the latest releases and open a new issue if you face any challenges... Thanks.
