### ISSUE TITLE
Exception when adding Note to NoteTabs Collection

### ISSUE THREAD

**Issue by DeMeritus** [docusign/docusign-csharp-client#191]
I am using v2.1.8 of the DocuSign.eSign.DLL in Visual Studio 2015 inside a test web app, and it works fine until I try to add a 'Note' tab into the mix.  (I'm trying to see if we can add "Instructions" to the signing process via Notes...)

When I add the code for adding the Note, I get a "System.NullReferenceException: Object reference not set to an instance of an object.".  I will attach the code snippet below -->

[GitHub Issue for Exception adding Note.txt](https://github.com/docusign/docusign-csharp-client/files/2210835/GitHub.Issue.for.Exception.adding.Note.txt)

I'm finding it hard to get documentation/examples for the .Net C# DLL library beyond the simple stuff.  Any suggestions regarding the Exception for adding a 'Note' and/or sites to go for documentation/examples for the .Net C# DLL library are welcome.

**Comment by DeMeritus** [comment]
FYI - I upgraded to v2.2.1 and no change - still an Exception when adding a 'Note'

**Comment by dmartin00** [comment]
Hello DeMeritus,

In this code sample, you've correctly declared the Tabs Lists for SignHereTabs and for TextTabs (`signer.Tabs.SignHereTabs = new List<SignHere>();` and  `signer.Tabs.TextTabs = new List<Text>();`) but not for the list of Note tabs.

Adding `signer.Tabs.NoteTabs = new List<Note>();` should resolve this error.

**Comment by DeMeritus** [comment]
Ooops... Thanks so much.
