### ISSUE TITLE
Questions: How to update envelope status from `sent` to `created`

### ISSUE THREAD

**Issue by MariusDing-InfoTrack** [docusign/docusign-csharp-client#193]
Hi,

Can I ask if it's possible to update envelope status from `sent` to `created`?

We are going to implement a feature to correct the envelope document.

We realized that correctView can be used for this purpose, however, there are lots of actions on Correct view which we don't want to expose to our users.

So what we think is to update envelope status from `sent` to `created` and then get senderViewUrl to let user to setup the signing tag by drag and drop. 

Best Regards,
Marius Ding

**Comment by RajRele** [comment]
@MariusDing-InfoTrack 
Setting the status property on the envelope to "sent" allows you to send it or "created" to save it as a draft. You can have a look at the detailed API Reference here. https://developers.docusign.com/esign-rest-api/reference/Envelopes/Envelopes
Thanks

**Comment by MariusDing-InfoTrack** [comment]
@RajRele Thanks for reply.

Setting status to `sent` or `created` works perfectly when I used it on `createEnvelope`.

However, when I tried to update status from `sent` to `created` by using `updateEnvelope`, it returns the error.

According to the documentation:

`update | PUT /v2/accounts/{accountId}/envelopes/{envelopeId}`
 `Sending a Draft Envelope To send a draft envelope, 
include this in the request body`
`{"status": "sent"}`

I am little bit confused about why it need set to `sent` when the envelope status is already `sent` for sending a draft envelope? Or not set to `created`?

I am not sure if `updateEnvelope` can be used to change `sent` status to `created`.

I am looking forward to your reply.

Thanks~

**Comment by MariusDing-InfoTrack** [comment]
Error:
![2018-07-26_10h56_52](https://user-images.githubusercontent.com/23064596/43235071-9ca83610-90c2-11e8-9a85-20d9c51830c1.png)

**Comment by dmartin00** [comment]
Once an envelope has been Sent, you cannot revert it back to Created. Based on your explanation, I believe you would want to generate the envelope as a draft (Created status), have the sender perform whatever actions, and then send it once the relevant corrections are complete.

**Comment by MariusDing-InfoTrack** [comment]
@dmartin00 

Got you~Thank for your reply. 🤗

**Comment by tabish-bp** [comment]
> Error: ![2018-07-26_10h56_52](https://user-images.githubusercontent.com/23064596/43235071-9ca83610-90c2-11e8-9a85-20d9c51830c1.png)

hey, can i see your code, where you're changing status.
I am trying to implement almost same feature where client uploads and save document as created and then i want to send it later. Can you help me out a little here?
