### ISSUE TITLE
Locating string oauthBasePath = "[OAUTH_BASE_PATH]"

### ISSUE THREAD

**Issue by jepstein1** [docusign/docusign-csharp-client#194]
How do I find the string oauthBasePath = "[OAUTH_BASE_PATH]" ?

**Comment by RajRele** [comment]
@jepstein1 
If you are working on a Sandbox/Demo environment, use the demo base path - "account-d.docusign.com", else on Production you may use production base bath. 
Please have a look at our Test Projects here where we have are using Demo account... https://github.com/docusign/docusign-csharp-client/tree/master/test

Thanks.
