### ISSUE TITLE
EnvelopesApi.CreateEnvelope documentation summary is excessively long and unreadable within Visual Studio

### ISSUE THREAD

**Issue by willl** [docusign/docusign-csharp-client#197]
![image](https://user-images.githubusercontent.com/926823/43626302-a2b9c6cc-9734-11e8-893a-dca31af96233.png)

I'm aware that DocuSign uses Swagger, so some things may be out of your control.

My main issue is that after I type `,` it takes 2 or 3 seconds for Visual Studio to load the tooltip (and freezes up before it loads).

I guess this is partly a Visual Studio issue, but at the same time, I think really long documentation is probably not too useful.

Here's a few links I found that document the issue on the Visual Studio side:
* [Visual Studio (devenv.exe) hangs when Intellisense tooltip is too long](https://developercommunity.visualstudio.com/content/problem/268093/visual-studio-devenvexe-hangs-when-intellisense-to.html)
* [VS crashes when editing](https://developercommunity.visualstudio.com/content/problem/251922/vs-%D0%B7%D0%B0%D0%B2%D0%B8%D1%81%D0%B0%D0%B5%D1%82-%D0%BF%D1%80%D0%B8-%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8.html)

Related to this, when I look at the [markdown documentation file](https://github.com/docusign/docusign-csharp-client/blob/master/sdk/docs/EnvelopesApi.md#createenvelope), I notice that it too is just an unreadable blob rather than separated out into legible paragraphs.

**Comment by LarryKlugerDS** [comment]
This issue is still planned but is not current `in progress`

**Comment by RajRele** [comment]
@willl 
This is resolved with [v3.1.6-rc](https://www.nuget.org/packages/DocuSign.eSign.dll/3.1.6-rc) in our ESign Api v2.

We will update the same with ESign Api v2.1 with next release.

Feel free to close this issue.
