### ISSUE TITLE
CspParameters won't work in Linux/Net Core

### ISSUE THREAD

**Issue by jvrobert** [docusign/docusign-csharp-client#201]
In ApiClient.c there is a section:
`
var cspParameters = new CspParameters
            {
                Flags = CspProviderFlags.UseMachineKeyStore,
            };
            var provider = new RSACryptoServiceProvider(cspParameters);
`
This throws an exception under dotnet core on linux because it depends on the Windows CSP.  As far as I can tell there's no point to using it anyway, I rebuilt a client DLL just taking it out and using the default RSACryptoServiceProvider constructor and it seems to work fine now.

**Comment by LarryKlugerDS** [comment]
Thank you for the bug report. I have filed DocuSign internal bug number DCM-2837

Please ask your DocuSign contact to add your name and organization/company information to the bug ticket. I'm glad that you were able to build a new DLL to solve the problem in the meantime.

**Comment by RajRele** [comment]
@jvrobert Thank you for pointing this out. We have fixed this in v3.1.1-rc for .Net Standard/Core implementations. Please have a look, we have a [release candidate](https://github.com/docusign/docusign-csharp-client/releases/tag/v3.1.1-rc) published here as well as NuGet store. Feel free to close this issue.

**Comment by RajRele** [comment]
Closing this issue. Open a new issue if you have any questions.
