### ISSUE TITLE
ApiClient.RequestJWTUserToken Missing in 3.0.1 release

### ISSUE THREAD

**Issue by SebastianC** [docusign/docusign-csharp-client#204]
I'm attempting to use the 3.0.1 release (from the nuget package), and i've hit the point where i need to use the function ApiClient.RequestJWTUserToken , however this code does not exist within the 3.0.1 release:  https://github.com/docusign/docusign-csharp-client/blob/bharat.rele/v3.0.1/sdk/src/DocuSign.eSign/Client/ApiClient.cs  i was able to find this function in the master branch: https://github.com/docusign/docusign-csharp-client/blob/master/sdk/src/DocuSign.eSign/Client/ApiClient.cs#L959

What am i missing? Thanks...

**Comment by RajRele** [comment]
@SebastianC The method you are referring to is a new method added in **3.1.0-rc** version, this is a pre-release version. If you are downloading from NuGet please get the latest pre-release version [here](https://www.nuget.org/packages/DocuSign.eSign.dll/3.1.1-rc). 

You can also get the latest code from [here](https://github.com/docusign/docusign-csharp-client/releases/tag/v3.1.0-rc).

**Comment by SebastianC** [comment]
i was able to find the function there. thanks.
