### ISSUE TITLE
Could not load type 'System.IdentityModel.Tokens.JwtSecurityTokenHandler' from assembly 'System.IdentityModel.Tokens.Jwt

### ISSUE THREAD

**Issue by alexandre-bandeira** [docusign/docusign-csharp-client#206]
Using docusign version 3.1.1-rc.

When calling RequestJWTUserToken in a WebApi project the following error occurs:

"ClassName": "System.TypeLoadException",
    "Message": "Could not load type 'System.IdentityModel.Tokens.JwtSecurityTokenHandler' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at DocuSign.eSign.Client.ApiClient.RequestJWTUserToken(String clientId, String userId, String oauthBasePath, Byte[] privateKeyBytes, Int32 expiresInHours, List`1 scopes)\r\n   at Homer.Service.Helpers.Docusign.JWTAuthLogin() in C:\\Code\\homer.service\\Homer.Service\\Helpers\\Docusign.cs:line 56\r\n   at Homer.Service.Controllers.DocumentsController.Test() in C:\\Code\\homer.service\\Homer.Service\\Controllers\\DocumentsController.cs:line 22\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__3(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nRequestJWTUserToken\nDocuSign.eSign, Version=3.1.1.0, Culture=neutral, PublicKeyToken=7fca6fcbbc219ede\nDocuSign.eSign.Client.ApiClient\nOAuthToken RequestJWTUserToken(System.String, System.String, System.String, Byte[], Int32, System.Collections.Generic.List`1[System.String])",
    "HResult": -2146233054,
    "Source": "DocuSign.eSign",
    "WatsonBuckets": null,
    "TypeLoadClassName": "System.IdentityModel.Tokens.JwtSecurityTokenHandler",
    "TypeLoadAssemblyName": "System.IdentityModel.Tokens.Jwt, Version=5.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
    "TypeLoadMessageArg": null,
    "TypeLoadResourceID": -2146233054

Am I missing something? 

Thanks

**Comment by RajRele** [comment]
Hi @alexandre-bandeira. This is a common issue when your build folder has one or more old referencing assembly version(s). While there are various solution to resolve this issue, please follow below steps which should reload the correct version of the library:
1. Clean-up your packages and bin contents from Debug and Release. 
2. Go to Nuget package manager and uninstall DocuSign package and _its dependencies_. 
3. Re-Install DocuSign.eSign (v3.1.1-rc) latest version from NuGet package manager and this will recursively install the missing dependencies with correct versions.
4. Clean/Rebuild should resolve this issue.

Thanks, let us know if issue still persists. Feel free to close this issue if resolved.

**Comment by RajRele** [comment]
Hi @alexandre-bandeira, 
DocuSign.eSign .Net Framework library has a dependency on System.IdentityModel.Tokens.Jwt Version="4.0.2.206221351" and it seems you have other integrations in your project which have a 5.X version of System.IdentityModel.Tokens.Jwt which unfortunately seems to be not backward compatible with 4.X version. 

We have upgraded this dependency to 5.X version in our .Net Standard implementation. This implementation works with .Net Standard2.0 and .Net Core projects.

I would suggest that you keep DocuSign as a separate service or project which you can inject or call from your main web-api project. Or isolate Twilio as a separate project which has a conflicting version. 

Once you have done that, make sure you delete all contents from packages/, bin/Debug, bin/Release and obj/  folders.
Uninstall the libraries gracefully from NuGet Package Manager.
Also, remove any incorrect references to the System.IdentityModel.Jwt version from the csproj or AppConfig files or packages.config files. Please repeat this clean-up process a couple time if the issue persists… as some reference(s) may still be called in your code.

Let us know if you still face these issues or you can also talk to your DocuSign support contact and we would love to help you fix this issue.

Thanks

**Comment by alexandre-bandeira** [comment]
hi @RajRele,

Thanks for your suggestions. I will talk with my team to figure out which one we gonna do (make docusign as separeted service or twilio).

I just got confused with : 

> We have upgraded this dependency to 5.X version in our .Net Standard implementation. This implementation works with .Net Standard2.0

Actually I'm using .Net Standard / Docusign 3.1.1-RC and Twilio uses version 5.x of System.IdentityModel.Tokens.Jwt . Sorry but I did not understand why it does not work.

Thank you very much!

**Comment by RajRele** [comment]
Thanks @alexandre-bandeira, let us know how it works for you.

Looking at your packages.config I do not see TargetFramework as netcoreapp2.X or .netstandard. Instead I see the framework is targeted at .net 4.7. Also your packages.config has downloaded all the dependencies which we have for our .net framework sdk. 
In .Net Standard project you would see dependencies separated by NuGet packages so you would have different dependency resolution contexts...

Hope that helps, 
Thanks :)

**Comment by willl** [comment]
Was just wondering whether there's any reason you're only upgrading the dependency for .NET Standard and .NET Core projects? Why not upgrade it for all framework versions?

**Comment by ChuckByram** [comment]
Also wondering about updating for all framework versions. We have the same DocuSign and Twilio SDK incompatibility.

**Comment by alexandre-bandeira** [comment]
Just to update, We are in a tight deadline so the fastest path for us was create another rest api service for Docusign integration :'(

**Comment by RajRele** [comment]
@alexandre-bandeira, @willl, @ChuckByram, @ArchetypeTechnology-Jim 
Sorry to hear that you are facing this issue with one of our .Net Framework dependencies. We are looking into this (Jira# DCM-2942).
Thanks for your patience.

**Comment by RajRele** [comment]
Hi, We have released a RC version of the C# SDK. The v4.5 framework dependencies are updated to avoid the integration issues with other versions. Please have a look at [NuGet Store v3.1.3-rc](https://www.nuget.org/packages/DocuSign.eSign.dll/3.1.3-rc)

**Comment by RajRele** [comment]
Hi @here,
We have a [release](https://github.com/docusign/docusign-csharp-client/releases/tag/v3.1.3) published which fixes this, please have a look at [NuGet Store](https://www.nuget.org/packages/DocuSign.eSign.dll/3.1.3)
Thanks you all for your patience.
Regards,
-Bharat

**Comment by ChuckByram** [comment]
Thank you, Bharat. We should be able to check this out next week.

**Comment by mrflag** [comment]
@RajRele , Thank you! I went live creating another service, but asap I will change to put everything on the same service.

Regards,
Alexandre

**Comment by RajRele** [comment]
Thanks, I am closing this issue. Please open a new issue if you have any questions.
