### ISSUE TITLE
ApiClient.RequestJWTUserToken doesn't fulfill ErrorContent of ApiException from server

### ISSUE THREAD

**Issue by yevgen-ponomarenko** [docusign/docusign-csharp-client#208]
It might be useful to have the ErrorContent to be fulfilled here. Especially, it'd be a handful for catching the `consent_required` in initial consent request or responding on revocation case.
It looks like a simple change of the [following code](https://github.com/docusign/docusign-csharp-client/blob/master/sdk/src/DocuSign.eSign/Client/ApiClient.cs#L1049) onto smth like below may do the work:
```csharp
throw new ApiException(
                    (int)response.StatusCode,
                    string.Concat(
                        "Error while requesting server, received a non successful HTTP code ",
                        response.ResponseStatus,
                        " with response Body: '", 
                        response.Content, "'"),
                    response.Content);
```
Thanks

**Comment by yevgen-ponomarenko** [comment]
Hi, @RajRele . 
Is it possible to set `ApiException.ErrorContent` to represent the response Body here - it'd be more convenient than string parsing?

**Comment by RajRele** [comment]
Hi @yevgen-ponomarenko, we have resolved this with v3.1.3 release.
Please have a look, feel free to close this issue.
Thanks.

**Comment by yevgen-ponomarenko** [comment]
Thank you. It's helpful.

**Comment by sameedaris** [comment]
hello , 
I am receiving this error when trying to use  RequestJWTUserToken. Please help .
DocuSign.eSign.Client.ApiException: 'Error while requesting server, received a non successful HTTP code Error with response Body: 
![image](https://user-images.githubusercontent.com/4318526/50110997-7e8e9b80-025d-11e9-8cb9-e7764e3b825b.png)

**Comment by LarryKlugerDS** [comment]
Please try the JWT example. These are Visual Studio solutions, ready to run:

* For .NET Framwork: [eg-01-csharp-jwt-framework](https://github.com/docusign/eg-01-csharp-jwt-framework)
* For .NET Core: [eg-01-csharp-jwt-core](https://github.com/docusign/eg-01-csharp-jwt-core)

**Comment by SrinathJandhyala** [comment]
I have the same problem. Error response was empty when i make call to ApiClient.RequestJWTUserToken. How did you fix the issue?

**Comment by zeeshan-adil-systems** [comment]
@SrinathJandhyala 

Docusign doesn't send clear errors when there is an issue with the request. In my case I was using `https://account-d.docusign.com` instead of `account-d.docusign.com` for the AuthServer value and it didn't tell the issue.

while calling `apiClient.RequestJWTUserToken`

**Comment by ZeeshanAdilButt** [comment]
@SrinathJandhyala 

Docusign doesn't send clear errors when there is an issue with the request. In my case I was using https://account-d.docusign.com instead of account-d.docusign.com for the AuthServer value and it didn't tell the issue.

while calling` apiClient.RequestJWTUserToke`

**Comment by rmuhammed** [comment]
> Hi @yevgen-ponomarenko, we have resolved this with v3.1.3 release.
> Please have a look, feel free to close this issue.
> Thanks.

I am using v3.1.3. But gets this error
"Error while requesting server, received a non successful HTTP code Completed with response Body: {"error":"consent_required"}"
at OAuth.OAuthToken authToken = ApiClient.RequestJWTUserToken(DSConfig.ClientID,
                            DSConfig.ImpersonatedUserGuid,
                            DSConfig.AuthServer,
                            Encoding.UTF8.GetBytes(DSConfig.PrivateKey),
                            1);

**Comment by marwajlaili** [comment]
Bonjour,
j'ai la meme erreur lorsque j'utilise apiClient.requestJWTUserToken:
**"message": "Error while requesting server, received a non successful HTTP code 400 with response Body: '{\"error\":\"consent_required\"}'",******

Est ce que vous avez trouvé une solution pour ça?
Merci

**Comment by kernel2** [comment]
Hello @LarryKlugerDS @RajRele 
I am using v5.0.0. But gets this error  
![Capture](https://user-images.githubusercontent.com/13397604/94935792-c67fc080-04cd-11eb-93da-d93038150a60.JPG)

**Comment by ltickett** [comment]
For anyone else facing this issue (e.g. no error returned by the response):

```
DocuSign.eSign.Client.ApiException: 'Error while requesting server, received a non successful HTTP code Error with response Body: '
```

The issue/solution for me was malformed `oauthBasePath`. At first I was using `https://account-d.docusign.com/oauth/auth` then tried `https://account-d.docusign.com` then finally got it to work with just `account-d.docusign.com`

Hope this helps someone else!
