### ISSUE TITLE
'Unexpected PEM type'

### ISSUE THREAD

**Issue by virgo22** [docusign/docusign-csharp-client#212]
Hi

I am trying to set the authentication method to JWT and followed the guidance given on the page 

https://developers.docusign.com/esign-rest-api/guides/authentication/oauth2-jsonwebtoken
 
with the following examples :
 
https://github.com/docusign/docusign-csharp-client/blob/master/test/SdkTests/JwtAuthUnitTests.cs
 
https://github.com/docusign/docusign-csharp-client/blob/master/test/SdkTests/TestConfig.cs

 
TestConfig testConfig = new TestConfig();
testConfig.ApiClient = new ApiClient(testConfig.Host);
byte[] privateKeyStream = File.ReadAllBytes(testConfig.PrivateKeyFilename);
OAuth.OAuthToken tokenInfo = testConfig.ApiClient.RequestJWTUserToken(testConfig.IntegratorKey, testConfig.UserId, testConfig.OAuthBasePath, privateKeyStream, testConfig.ExpiresInHours);
 
I am keep getting the following error : System.Exception: 'Unexpected PEM type'

DocuSign.eSign.dll version i am currently using is : 3.1.3

I would appreciate any help on this.

**Comment by gsnavin** [comment]
Hi @virgo22 
Can you please make sure the pem file looks similar to this sample file we have in the test project?
https://github.com/docusign/docusign-csharp-client/blob/master/test/SdkNetCoreTests/docs/private.pem

Naveen

**Comment by LarryKlugerDS** [comment]
Also see the ready to run visual studio projects for 
[.NET Core](https://github.com/docusign/eg-01-csharp-jwt-core) and [.NET Framework](https://github.com/docusign/eg-01-csharp-jwt-framework)

**Comment by virgo22** [comment]
Hi 

Thank you for the replies,

I have checked the pem file looks similar to the given example (same format) and i have also tried with the ready to run visual studio projects for .NET Core and .NET Framework but the result is same, however 
the same key works fine with the deprecated method ConfigureJwtAuthorizationFlowByKey

string privatekey = File.ReadAllText(testConfig.PrivateKeyFilename);
OAuth.OAuthToken tokenInfo2 = piClient.ConfigureJwtAuthorizationFlowByKey(testConfig.IntegratorKey, testConfig.UserId, testConfig.OAuthBasePath, privatekey, expiresInHours);

the only difference between them is one is receiving the key as byte array and another receiving as string, it seems to me there is an issue with RequestJWTUserToken method.

any idea ?

Thank you.

**Comment by virgo22** [comment]
Hi 

Resolved it by, reading the file into a string and then converting a string into byte array with encoding resolved this issue.

string privatekey = File.ReadAllText(testConfig.PrivateKeyFilename);
byte[] privateKeyBytes = Encoding.UTF8.GetBytes(privateKey)

Thanks.

**Comment by LarryKlugerDS** [comment]
Glad it's working for you. The same code is on line 48 of https://github.com/docusign/eg-01-csharp-jwt-common/blob/master/ExampleBase.cs for the example JWT C# projects.

**Comment by gadigep** [comment]
I am getting the same error 
Error: Unexpected PEM type

   at DocuSign.eSign.Client.ApiClient.CreateRSAKeyFromPem(String key)
   at DocuSign.eSign.Client.ApiClient.RequestJWTUserToken(String clientId, String userId, String oauthBasePath, Byte[] privateKeyBytes, Int32 expiresInHours, List`1 scopes)


I downloaded the project "eg-01-csharp-jwt-framework-master"
Please help me fix this.

**Comment by madebyjeffrey** [comment]
This is caused by saving the key with a UTF-8 BOM at the beginning. The code should be using ReadAllText instead of ReadAllBytes. Load the key file up in Notepad++, and check the file encoding. If it says BOM, then change to plain UTF-8 and it can work as is.
