### ISSUE TITLE
Signer Custom Fields

### ISSUE THREAD

**Issue by sameedaris** [docusign/docusign-csharp-client#213]
Hello ,
At present Signer class contains Custom fields as list of strings and when XML is return from docusign it 
it contains something like 
`<CustomFields>
<CustomField>xxxxx</CustomField>
<CustomField>xxxxx</CustomField>
</CustomFields>`

as documentation says schema is custom field class not string .**so it needs to be corrected from `List<string> to List<Customfield>`**

**Comment by LarryKlugerDS** [comment]
Thank you for your suggestion.

We believe that it is more convenient for the developer to type the Signer.customFields as an array (list) of strings than to invent a new type for them. In the JSON response, they're an array of `string`.

Custom fields are essentially cookies for the client app--you can store any string value in them, including a stringified JSON object. 

See the API docs definition:

>An optional array of strings that allows the sender to provide custom data about the recipient. This information is returned in the envelope status but otherwise not used by DocuSign. Each customField string can be a maximum of 100 characters.
