### ISSUE TITLE
Agent Model doesn't content canEditRecipientEmails attribut

### ISSUE THREAD

**Issue by OlivierRoecker** [docusign/docusign-csharp-client#216]
The DocuSign document describe an attribut "canEditRecipientEmails" but the SDK Agent Model doen't content this attribut.

Best Regard
Oliver

**Comment by LarryKlugerDS** [comment]
I think you mean recipients who can edit the email addresses of subsequent recipients. The following recipient types have this ability: `Agents`, `Editors`, and `Intermediaries`. They change the emails of subsequent signers by `correcting` the envelope's recipients when they receive the envelope. They do this through the DocuSign web tool.

If you want to programmatically change a recipient's email, do so using the [EnvelopeRecipients::update](https://developers.docusign.com/esign-rest-api/reference/Envelopes/EnvelopeRecipients/update) API method

**Comment by OlivierRoecker** [comment]
I agree your description of feature.
But where can i setup the Agent recipient creation with this specific attribute  "canEditRecipientEmails."
 It's not included in c# class model. I find it in Json Model etc... but in this C# Package.

**Comment by LarryKlugerDS** [comment]
All `agent` recipients have the edit capability. I don't think there is a specific attribute.

**Comment by OlivierRoecker** [comment]
Sorry, i'm confuse.
How can i send "canEditRecipientEmails=true" with C# API to DocuSIgn server in accordance with thiis part of teh documentation : https://developers.docusign.com/esign-rest-api/reference/Envelopes/EnvelopeRecipients/
![image](https://user-images.githubusercontent.com/7466678/53974447-e0df9580-4102-11e9-94b3-9b67bcbb87a4.png)

**Comment by LarryKlugerDS** [comment]
Sorry for the confusion. The documentation is not correct. (I will start the process to have it updated.)

The `agentCanEditEmai` and `agentCanEditName` fields are attributes of the **Signer** object.

You add those attributes to allow a Signer's email/name to be changed by an Agent recipient.

See lines 42, 43 of file [Model/Signer.cs](https://github.com/docusign/docusign-csharp-client/blob/master/sdk/src/DocuSign.eSign/Model/Signer.cs)

**Comment by OlivierRoecker** [comment]
Perfect!

**Comment by LarryKlugerDS** [comment]
I've filed internal ticket DEVDOCS-795. 
This issue is closed, but the internal documentation ticket will still be worked. 
Thanks,
Larry
