### ISSUE TITLE
Documentation confusion

### ISSUE THREAD

**Issue by dmcbride** [docusign/docusign-csharp-client#220]
https://github.com/docusign/docusign-csharp-client/blob/37e3edf4af9099695f8129fb126b46ee5977698d/sdk/src/DocuSign.eSign/Client/ApiClient.cs#L1135

The name and the description are using different units. Just a bit confusing.

**Comment by LarryKlugerDS** [comment]
Thank you for the report. The parameter is being interpreted as hours. 
By the way, the correct value for this parameter is always 1 (1 hour). Note that this parameter is setting how long the JWT will be valid, not the validity time for the access token that is returned.

-- The returned access tokens are generally valid for 8 hours. (See the expires attribute in the returned object.

I will file a documentation bug.

**Comment by RajRele** [comment]
This is resolved with https://www.nuget.org/packages/DocuSign.eSign.dll/4.0.3-rc
