### ISSUE TITLE
Async Api Methods Should Have a CancellationToken Parameter

### ISSUE THREAD

**Issue by mattscully** [docusign/docusign-csharp-client#221]
Since all the API SDK methods make HTTP calls (via RestSharp), they should also allow a CancellationToken to be passed in as a parameter.  Given that API calls may vary significantly in the time they take to complete (some may query for a quick status and others may download megabytes of documents), it may be quite common to have different timeout expectations for different methods.  Accepting a CancellationToken would improve the API by:

1. Allowing for a timeout to be set by method invocation while still sharing a common Configuration instance.
2. Allowing the request to be cancelled by a user action.

It is quite common to make the CancellationToken an optional parameter, which I think would make sense here.  For example

```
public async Task<Envelope> GetEnvelopeAsync(
      string accountId,
      string envelopeId,
      EnvelopesApi.GetEnvelopeOptions options = null,
      CancellationToken cancellationToken = default(CancellationToken))
```

**Comment by LarryKlugerDS** [comment]
Thank you for the enhancement idea. This idea has not been raised by other developers, so its prioritization will probably be low. If we have many developers asking for the idea, it will be considered more.

**Comment by LarryKlugerDS** [comment]
Note that the Envelopes::create method does include an `asynchronous` boolean attribute. 

I have filed enhancement request EC-1507
