### ISSUE TITLE
AWS Lambda: Could not load file or assembly 'System.IdentityModel.Tokens.Jwt'

### ISSUE THREAD

**Issue by SrinathJandhyala** [docusign/docusign-csharp-client#228]
I am getting below error message when i request user token using ApiClient.RequestJWTUserToken method. I am using DocSign.eSign.dll (3.1.5) in my AWS Lamda function built in C#. Please advise.

System.IO.FileLoadException: Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=5.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)

**Comment by LarryKlugerDS** [comment]
This appears to be a problem with the AWS Lambda support of .NET. For more information, see 

* https://github.com/aws/aws-lambda-dotnet/issues/133
* https://github.com/dotnet/corefx/issues/16227
* https://forums.aws.amazon.com/thread.jspa?threadID=296482
* https://stackoverflow.com/questions/10055158/is-there-any-json-web-token-jwt-example-in-c
* Google phrase: "AWS Lambda System.IdentityModel.Tokens.Jwt"

To solve this problem, you may need to implement the equivalent of the  `ApiClient.RequestJWTUserToken` method yourself for use on AWS Lambda. The good news is that the DocuSign use of the JWT Grant flow is pretty standard.

When you are able to find a solution, please update this issue so others can benefit from your experience. I have filed enhancement request  DCM-3368, but we don't have a timeline for it.

I suggest that the fastest solution would be to engage with AWS experts.

**Comment by LarryKlugerDS** [comment]
This is a really an issue of using `System.IdentityModel.Tokens.Jwt` with AWS Lambda. As such, we need a solution from AWS.

If you figure out a solution, please help others by updating this issue with the answer.

Thanks,
Larry

**Comment by Thejacques1** [comment]
Yes, I would like to see this fixed by AWS too. Don't see why we need to hand-roll this. Thanks
