### ISSUE TITLE
"Error while requesting server, received a non successful HTTP code" with no response body 

### ISSUE THREAD

**Issue by SrinathJandhyala** [docusign/docusign-csharp-client#229]
Received the following error when i make .Net Core 2.1 WEB API call to RequestJWTUserToken method. No more details on the error type, code or error reason.
"Error while requesting server, received a non successful HTTP code Error with response Body: "

OAuth.OAuthToken authToken = ApiClient.RequestJWTUserToken(DSConfig.ClientID,
                            DSConfig.ImpersonatedUserGuid,
                            DSConfig.AuthServer,
                            Encoding.UTF8.GetBytes(DSConfig.PrivateKey),
                            1);

**Comment by SrinathJandhyala** [comment]
Figured out. Closing the ticket.

**Comment by manishandankar** [comment]
How did you resolve this. I am getting this error in an MVC Web App which is directly consuming docusign esign dll and dependencies. .Net Framework 4.6.1? Appreciate your help on this.

**Comment by manishandankar** [comment]
> Figured out. Closing the ticket.

I am getting the same error while consuming Docusign.eSign.DLL in MVC Webapp build in dotnet 4.6.1 framework. I would really appreciate your help on this.

**Comment by gtk-aschmidt** [comment]
The response code is 401. 401 means authorization problem.

But there's the rub. You don't want to get too specific with authorization errors, because then it's a security risk.

If I were to guess, the answer is going to be in generic OAuth documentation somewhere, since the SDK presumes mastery of OAuth as a prerequisite.

**Comment by neena2504** [comment]
@SrinathJandhyala Hi I am facing the same error and I have followed every step mentioned in the c# example by Docusign. Can you please let me know how did you resolved this issue?

**Comment by shobhitvaish** [comment]
For me, it was the incorrect AuthServer value. The correct value of the AuthServer is account.docusign.com, not https://account.docusign.com
