### ISSUE TITLE
Unable to use Newtonsoft.Json 11.0.2. Trying to load Newtonsoft.Json, Version=10.0.0.0

### ISSUE THREAD

**Issue by manishandankar** [docusign/docusign-csharp-client#233]
Trying to integrate with website built in .net 6.4.1 framework, I get the following runtime exception while initializing the api client - ApiClient docusingApiClient = new ApiClient(basePath);
Exception:
System.IO.FileLoadException: 'Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

**Comment by manishandankar** [comment]
bindingRedirect doesn't work.

**Comment by RajRele** [comment]
Hi @manishandankar Do you mean .net 4.6.1 framework? Can you confirm what version of DocuSign library are you using?

**Comment by LarryKlugerDS** [comment]
Hi @manishandankar , please confirm which .Net version you're using.
Thank you,
Larry

**Comment by manishandankar** [comment]
I noticed that the existing assembly binding redirect  tag in the config file had appliesTo attribute with a specific framework version. I added another assemblyBinding tag under it without the appliesTo attribute and moved the bindings there. Worked fine. Thanks for the followup.
