### ISSUE TITLE
How to specify a docusign api version while consuming the library?

### ISSUE THREAD

**Issue by manishandankar** [docusign/docusign-csharp-client#237]
I want to target v2.1 of docusign api, how would I be sure that the api calls are made to this specific version?

**Comment by LarryKlugerDS** [comment]
Good question! The master branch now uses v2.1 of the API.

version 4.0.0 and later versions of this SDK use DocuSign REST API version 2.1.
This is noted in the change log file.
The only way to use version 2 of the API is to use an older version of the SDK.
