### ISSUE TITLE
Error while creating new envelope from existing envelope

### ISSUE THREAD

**Issue by krishnamhn009** [docusign/docusign-csharp-client#238]
I am creating new envelope from existing envelope.

```
var envDef = new EnvelopeDefinition
        {
            EmailSubject = "Email Subject",
            Status = "sent",
            EnvelopeId = envelopeId
        };
var envelopeSummary = await envelopesApi.CreateEnvelopeAsync("accountId", envDef);
```

//**_CreateEnvelopeAsync_** this method is giving below error 

> errorCode:"UNSPECIFIED_ERROR","message":"The value for column 'EnvelopeSourceTypeId' in table 'Envelope' is DBNull".

It was working fine.Suddenly I am getting this error from today

**Comment by LarryKlugerDS** [comment]
Hello, as this issue been resolved? 
Thanks,
Larry

**Comment by krishnamhn009** [comment]
I faced this issue while updating nuget package to v4.0,I reverted nuget update due to this issue.

**Comment by LarryKlugerDS** [comment]
Before v4.0 you're using v2 of the API. With v4 and above, you're using v2.1 of the API.

In v2.1, the DocuSign webtool creates a new envelope from an existing envelope by **only** providing the envelope Id.A log:

````
Request:
{
    "envelopeId": "b4adb898-851d-46ca-a60e-673cec8d3e06"
}

Response:
{
    "envelopeId": "a1a4fc87-022d-45b3-a61b-7a059fedd824",
    "uri": "/envelopes/a1a4fc87-022d-45b3-a61b-7a059fedd824",
    "statusDateTime": "2019-11-05T11:01:37.5966414Z",
    "status": "created"
}
````

I suggest that you try this flow. (After the envelope is created, update it with your new subject and change the status to `sent`)

**Comment by LarryKlugerDS** [comment]
Please re-open / comment if the above does not solve the issue.
Thanks,
Larry

**Comment by krishnamhn009** [comment]
its working with old code ..thanks 
```
var envDef = new EnvelopeDefinition
        {
            EmailSubject = "Email Subject",
            Status = "sent",
            EnvelopeId = envelopeId
        };
var envelopeSummary = await envelopesApi.CreateEnvelopeAsync("accountId", envDef);
```
