### ISSUE TITLE
.Net Standard 2.0 Compatibility 

### ISSUE THREAD

**Issue by JMatt297** [docusign/docusign-csharp-client#241]
I'm trying to this nuget package setup in a .Net Standard 2.0 library project, however, I am getting the following exception when I hit the RequestJWTUserToken() method in DocuSign:

System.TypeLoadException: Could not load type 'Org.BouncyCastle.Security.DotNetUtilities' from assembly 'BouncyCastle.Crypto, Version=1.8.5.0, Culture=neutral, PublicKeyToken=null'.

I've noticed are that your dll references version Portable.BouncyCastle 1.8.2, rather than 1.8.5. I have tried upgrading this reference to 1.8.5 manually, but the DotNetUtilites class is still missing from the object browser. Please can you have a look at why this would be happening?

I can get it to work if I reference the original BouncyCastle and BouncyCastle.NetCore packages together, but this gives warnings about version compatibility, which then cause problems when deploying my code.

Cheers

**Comment by RajRele** [comment]
Need some more information on this, can you paste your csproj file here?

**Comment by JMatt297** [comment]
I have resolved this issue. Turns out there was a reference to Bouncy Castle .NetCore 1.8.5 in one of our external projects that was conflicting with DocuSigns portable reference. Thanks for your response though.

**Comment by adamhathcock** [comment]
had this same issue.  Directly referenced BouncyCastle.Portable to avoid clashing with BouncyCastle.NetCore.

MySql.Data did it to me....Oracle's fault yet again.

**Comment by LarryKlugerDS** [comment]
HI @adamhathcock , thank you for the information.
