### ISSUE TITLE
Tooltip / Name - different? same? mixup?

### ISSUE THREAD

**Issue by John15213** [docusign/docusign-csharp-client#245]
It seems that if I set the Tooltip and Name properties on tabs via the API, the "Tooltip" property in the web console UI displays the Name property that was set.   When the information is downloaded via the api the Tooltip/Name properties are populated as they were originally set via the API. 

 
![image](https://user-images.githubusercontent.com/11163532/66867986-76c98180-ef6a-11e9-87e5-34104b99ad0f.png)

![image](https://user-images.githubusercontent.com/11163532/66868047-9660aa00-ef6a-11e9-8733-46de87d0aad4.png)

**Comment by LarryKlugerDS** [comment]
Please use the API logger system to download the actual JSON that was sent to DocuSign by the SDK. (And post here.) That way we can see what the SDK is doing. 

[API Logger](https://support.docusign.com/en/guides/ndse-user-guide-api-request-logging)

Thank you,
Larry

**Comment by John15213** [comment]
I updated to latest nuget 4.1.1.1 for this test.   So it seems like the data is going back/forth, just the name is shown as the tooltip in the console UI not the Tooltip field?  Also the sort order of the entries in the log.zip aren't same as request time sort. 

Thank You!

[Sample.pdf](https://github.com/docusign/docusign-csharp-client/files/3731689/Sample.pdf)

[logs.zip](https://github.com/docusign/docusign-csharp-client/files/3731686/logs.zip)

![image](https://user-images.githubusercontent.com/11163532/66874337-ce6ee980-ef78-11e9-9182-b1913c46889f.png)

```
			var recipients = api.ListRecipients(ACCOUNT_ID, envelopeId, new EnvelopesApi.ListRecipientsOptions() { });
			var signer1 = recipients.Signers[0];
			var tabs = api.ListTabs(ACCOUNT_ID, envelopeId, signer1.RecipientId, new EnvelopesApi.ListTabsOptions() { });

			Tabs updated = new Tabs();
			updated.TextTabs = new List<Text>();
			int i = 0;
			foreach (var text in tabs.TextTabs)
			{
				text.Tooltip = "TOOLTIP" + i.ToString();
				text.Name = "NAME" + i.ToString();
				updated.TextTabs.Add(text);
				i++;
			}
			var result = api.UpdateTabs(ACCOUNT_ID, envelopeId, signer1.RecipientId, updated);
			var after = api.ListTabs(ACCOUNT_ID, envelopeId, signer1.RecipientId, new EnvelopesApi.ListTabsOptions() { });
```

**Comment by LarryKlugerDS** [comment]
Thank you. I have investigated and am asking our Engineering group for confirmation of the following:

The tab name attribute is used to set the tool tip text.
The tab tabId attribute is read only. Any value sent during Envelope or Tab create is ignored.
The tab tabLabel attribute is for the developer’s use. It is shown on NDSE as “Data Label.” It is included with Connect notifications and read operations on the tab.
The tab tooltip attribute does not appear to be of use.
 
Details
 
Envelopes::create API Request:  "name": "Text-tab-name",
NDSE: Tooltip
Connect notification: <TabName>Text-tab-name</TabName>
EnvelopeTabs::list API Response: name: "Text-tab-name"
 
 
Envelopes::create API Request:  "tabId": "text-id-1",
Connect notification: not included
EnvelopeTabs::list API Response: "ec8c7e7d-xxxx-xxxx-xxxx-384638fbe8d5"
(Conclusion: TabId is read only, create value is ignored.)
 
 
Envelopes::create API Request:  "tabLabel": "text-label-1",
Connect notification: <TabLabel>text-label-1</TabLabel>
NDSE: Data Label
EnvelopeTabs::list API Response: tabLabel: "text-label-1"
 
Envelopes::create API Request:  "tooltip": "text-tooltip-value"
Connect notification: not included
EnvelopeTabs::list API Response: attribute not included

**Comment by John15213** [comment]
Thank You!
