### ISSUE TITLE
Templates API taking much time

### ISSUE THREAD

**Issue by krishnamhn009** [docusign/docusign-csharp-client#247]
I am using docusign api to retrieve templates from docusign folder which shows in our app to select in dropdown.Now,We have very large templates in folder and its taking much time for api call.It's killing our performance.Do docusign have any caching support? Do docusign provides a digest API of some sort where we can hit it and see if there are changes and then not make the call if nothing has changed.So I can use caching at our end or any suggestion appreciated.

**Comment by LarryKlugerDS** [comment]
How many items are in your templates folder?

At this time, I suggest that your app cache the template information and then run a nightly job to update your cache.

Is it true that the DocuSign web tool is also slow when it is asked to display your account's list of templates?

I will also file an enhancement ticket about the issue.

Thank you,
Larry

**Comment by krishnamhn009** [comment]
we have more than thousands templates in folders.Web tool looks fine.I know we can cache ,wanted to know if docusign have endpoint to check if templates are modified!!
