### ISSUE TITLE
Is an exception raised when using CreateEnvelope and the email used is invalid?

### ISSUE THREAD

**Issue by awerber** [docusign/docusign-csharp-client#249]
I originally used the code downloaded from this project to my solution. When an envelope had a non-existent email address, and exception was thrown. I handled the exception in my code. Now we use the NuGet package DocuSign.eSign.dll version 3.1.1, and no exception is being thrown. Yet, when I examine the code in this repository, it looks like an exception should be thrown. Why do we not get an exception from the code in the package, and, is there a way to detect when there is a delivery failure right after the envelope is sent? We want to notify our users of the problem right after sending the envelope.

**Comment by LarryKlugerDS** [comment]
In my experience, there are two checks for valid email addresses.

1. The email address is of the wrong format. Eg just larry@docusign. (no top level domain). An envelope with this email address problem should cause an immediate error from the API and the error should raise an exception in the SDK. 

  What is happening for this type of error?

1. Delivery bounce error. Sometimes, an email address is supplied. But when docusign sends an email to the address, a bounce message is returned. If the various standards are used by the email gateways, DocuSign can detect this and will mark the recipient with the status of a bad email.

  This error only happens asynchronously. Your app can detect it by obtaining the envelope status from DocuSign.

**Comment by awerber** [comment]
Thank you for replying to my issue.

Our system prevents the first problem.

I've just been testing the original code I used, and I don't get an exception using an undeliverable email address.

On further inspection, the error we're getting is INVALID_USERNAME_FOR_RECIPIENT. I'll be investigating what can cause this, but it looks like it has nothing to do with a bad email address.

**Comment by jcmatadev** [comment]
> In my experience, there are two checks for valid email addresses.
> 
> 1. The email address is of the wrong format. Eg just larry@docusign. (no top level domain). An envelope with this email address problem should cause an immediate error from the API and the error should raise an exception in the SDK.
> 
> What is happening for this type of error?
> 
> 1. Delivery bounce error. Sometimes, an email address is supplied. But when docusign sends an email to the address, a bounce message is returned. If the various standards are used by the email gateways, DocuSign can detect this and will mark the recipient with the status of a bad email.
> 
> This error only happens asynchronously. Your app can detect it by obtaining the envelope status from DocuSign.

Hey Larry, 

Do you happen to know how can I get this _Failure_ status for Delivery bounce errors?
I've tried with `GetEnvelopeAsync()` with no luck, and `ListRecipientsAsync()` would get me at much a _"autoresponded"_ status for the corresponding signer.

![envelope](https://user-images.githubusercontent.com/38059387/76473903-889b3d80-63bf-11ea-85db-c8237f2c0b71.PNG)

**Comment by LarryKlugerDS** [comment]
Hi, the "autoresponded" status is how DocuSign records the bounced email message in the DocuSign system.

If you use the DocuSign webhook system, Connect, then you can ask to have autoresponse statuses (email bounces) cause a notification message to your app. This is not the default. To have it turned on for demo or production accounts, send your account-ids to go-live@docusign.com.

**Comment by LarryKlugerDS** [comment]
Also, if you're using v2 of the API, try v2.1 of the API to get more information about the envelope status.
