### ISSUE TITLE
Is the Document-level authoritativeCopy field unavailable in the C# SDK?

### ISSUE THREAD

**Issue by dullroar** [docusign/docusign-csharp-client#250]
I can successfully set the **Envelope**-level authoritativeCopy field using the API, but see no way to set it on the Document (to allow only certain documents in the envelope to have authoritative copy turned on). I have not had good luck finding that field in the REST docs, so is it only offered via the SOAP API (where I can see it after importing a service reference)? That would be bad, because everything else we've done is with the C# SDK, so then to have to "shell out" to the SOAP API for the one (1) envelope we need authoritative copy on, which has one (1) document out of many in the envelope in which we need to set it, is going to be "non-optimal." I found an ancient StackOverflow answer (2013) that seemed to imply that it was only available at the SOAP level?

**Comment by LarryKlugerDS** [comment]
Unfortunately, the authoritative copy attributes and the authoritative copy of a document can only be transferred via the DocuSign SOAP API.

Note that you don't need a SOAP library to make SOAP calls, you can include the SOAP headers within an HTTP POST/response to use the SOAP API.
