### ISSUE TITLE
Refused to display 'https://account-d.docusign.com/recipient/auth?ui_locales=en' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by Hussain08** [docusign/docusign-csharp-client#253]
Hi,
I'm trying to embed a docusign url in an iFrame. But the browsers (tested on Chrome, Firefox) are refusing to render the url.  
The embed url from `envelopesApi.CreateRecipientViewAsync(...).Url` looks something like `"https://demo.docusign.net/Signing/MTRedeem/v1/XXXXXXXXX?slt=XXX`
But when the source of the iFrame sets to this url, it redirects to `https://account-d.docusign.com/managed_token/v1/redeem/?slt=XXXX`. 
Which comes with the header `X-Frame-Options: SAMEORIGIN`. 
In addition to the x-frame header it also redirects to `https://demo.docusign.net/Signing/StartInSession.aspx?code=XXX`.

**Comment by LarryKlugerDS** [comment]
What are you trying to do?

You can embed a signing ceremony or the sending consoler in an iFrame. Obtain the urls using the DocuSign API.

We have an example launcher which demonstrates both workflows. 
See https://github.com/docusign/eg-03-csharp-auth-code-grant-core 

Next time, this type of usage question is best asked on StackOverflow with tag `docusignapi`
Thank you.
