### ISSUE TITLE
Various ApiClient Constructors have subtle/confusing differences

### ISSUE THREAD

**Issue by mikesigs** [docusign/docusign-csharp-client#256]
The ApiClient has a default constructor:

```csharp
  public ApiClient()
    {
      this.InitializeTLSProtocol();
      this.Configuration = Configuration.Default;
      this.RestClient = new RestClient("https://www.docusign.net/restapi");
    }
```

It has other constructors that use optional arguments. For my use case, I am concerned with this one:

```csharp
    public ApiClient(string basePath = "https://www.docusign.net/restapi", WebProxy proxy = null)
    {
      if (string.IsNullOrEmpty(basePath))
        throw new ArgumentException("basePath cannot be empty");
      this.InitializeTLSProtocol();
      this.basePath = basePath;
      this.SetOAuthBasePath((string) null);
      this.Proxy = (IWebProxy) proxy;
      this.RestClient = new RestClient(basePath)
      {
        Proxy = (IWebProxy) proxy
      };
      this.Configuration = Configuration.Default;
      this.Configuration.ApiClient = this;
    }
```

First of all, the default arguments are kind of unnecessary. If I new up an instance like `new ApiClient()` it will always use the parameterless constructor. So it's not actually possible to invoke the other constructors and *not* provide values to their parameters. I suppose one could provide _just_ the proxy, and leave the default basePath.

The big concern I have is, in the JWT example, an initial apiClient is created with `new ApiClient()`. Then after getting the JWT Token that instance is reinitialized using `new ApiClient(Account.BaseUri + "/restapi");` instead of setting the base path via `apiClient.SetBasePath(Account.BaseUri + "/restapi")` on the existing instance. Why is this so?

It appears that somehow the subtle differences in the second constructor are necessary, and the only option to make it work is to reinitialize it. Those differences are:
1. `this.SetOAuthBasePath((string) null);` 
2. `this.Configuration.ApiClient = this;`

Can someone please explain why the `OAuthBasePath` is explicitly nulled in this constructor. As well, why the `Configuration.ApiClient` gets set to `this`?

The way these constructors are different is making it complicated to use Dependency Injection properly to create the ApiClient. I'd prefer to have a single ApiClient instance registered as a scoped instance. Then I can modify that instance after refreshing the JWT token, and still use that instance in the other API accessors, like the EnvelopesApi. 

What I have found is if I pass just `new ApiClient()` to the EnvelopesApi, it doesn't work. I must pass it one using `new ApiClient(basePath)`. 

I think I may have just stumbled on to something actually. The `new ApiClient()` uses `Configuration.Default`. Then it performs the JWT Auth, which I betcha somehow updates the configuration with the JWT token. Then in the `new ApiClient(basePath)` call, it ALSO uses `Configuration.Default` (that has been previously initialized with the JWT Token), but in that constructor it also sets the ApiClient on the default configuration to be itself. The only reason the JWT example works is because there is a static `Configuration.Default` class that the constructors are sharing!

What a tangled mess you guys!!

Please help me understand. There has to be a better way. The JWT sample is not a good example of production code. And I am struggling to make this work properly with proper IoC patterns.

Thank you!

**Comment by mikesigs** [comment]
Yes, I found the line that modifies the shared static `Configuration.Default` object after getting a JWT token.

```csharp
Configuration.Default.AddDefaultHeader("Authorization", string.Format("{0} {1}", (object) oauthToken.token_type, (object) oauthToken.access_token));
```

**Comment by mikesigs** [comment]
I derived number (1) above from Resharper's decompiled version of the ApiClient. I see now in the actual source (here on GitHub) that it's just calling `this.SetOAuthBasePath()` which makes more sense now. It's setting the OAuthBasePath, not to null, but telling it to determine the proper OAuthBasePath from the provided basePath.

**Comment by RajRele** [comment]
Hi @mikesigs this is the way swagger-codegen provide different ways to instantiate as per your needs and over on top of that we have a bunch of customizations which we have added to suit our OAuth and special cases... if you are interested in looking into our raw open api spec please take a look here... https://github.com/docusign/eSign-OpenAPI-Specification, if you think your question is answered or if you have figured it out, please feel free to close this issue...
