### ISSUE TITLE
question on using webhooks to track envelope status

### ISSUE THREAD

**Issue by gh0st** [docusign/docusign-csharp-client#262]
Coming across [this article](https://developers.docusign.com/esign-rest-api/code-examples/webhook-status) on developer.docusign caught my eye. Examples are given in python and php but I'm interested in doing this using csharp. Am I in the right place? I've been browsing a number of methods but my confidence isn't quite as high as I'd expect it to be. 

The closest method I found to updating an envelope was this one
```csharp
/// <summary>
/// Sets envelope notification (Reminders/Expirations) structure for an existing envelope.
/// </summary>
/// <remarks>
/// 
/// </remarks>
/// <exception cref="DocuSign.eSign.Client.ApiException">Thrown when fails to make API call</exception>
/// <param name="accountId">The external account number (int) or account ID Guid.</param>/// <param name="envelopeId">The envelopeId Guid of the envelope being accessed.</param>
/// <param name="envelopeNotificationRequest"> (optional)</param>

/// <returns>ApiResponse of </returns>
ApiResponse<Notification> UpdateNotificationSettingsWithHttpInfo (string accountId, string envelopeId, EnvelopeNotificationRequest envelopeNotificationRequest = null);
```

But the fact that the parameter names and types sound too "notificationy" are throwing me off. I simply want to take an envelope ID after it's been created from within DocuSign, and add a webhook to that envelope programmatically. Am I in the right place here?

**Comment by gh0st** [comment]
Forgot I came across this. https://github.com/docusign/recipe-010-webhook-csharp/blob/master/Webhook/Controllers/Webhook010Controller.cs Sorry!

**Comment by RajRele** [comment]
This may help too https://developers.docusign.com/esign-rest-api/guides/connect

**Comment by LarryKlugerDS** [comment]
Hi @gh0st ,
If you want to receive the webhook from behind your firewall without needing to change the firewall, check out my post and code examples: https://www.docusign.com/blog/dsdev-webhook-listeners-part-4/ 

I also have a code example for using Azure as the PAAS, see [connect-node-listener-azure](https://github.com/docusign/connect-node-listener-azure) and [connect-node-worker-azure](https://github.com/docusign/connect-node-worker-azure)
