### ISSUE TITLE
ApiClient - InterceptRequest/InterceptResponse are not accessible from the nuget package

### ISSUE THREAD

**Issue by bgrew** [docusign/docusign-csharp-client#265]
The partial methods `InterceptRequest` and `InterceptResponse` in the `ApiClient` are not implementable when you bring in the package through a nuget package. According to this
[Microsoft Documentation](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods):

> All partial-type definitions meant to be parts of the same type must be defined in the same assembly and the same module (.exe or .dll file). Partial definitions cannot span multiple modules.

At compile time of the package, partial classes are combined into one class. Since `InterceptRequest` and `InterceptResponse` are not implemented anywhere, they do not end up in the compiled class at all and are effectively removed from the class. You can see this using ReSharper and looking at the definition of `CallApi`. The Intercept methods are not there since they are never implemented.

```
public object CallApi(
      string path,
      Method method,
      Dictionary<string, string> queryParams,
      object postBody,
      Dictionary<string, string> headerParams,
      Dictionary<string, string> formParams,
      Dictionary<string, FileParameter> fileParams,
      Dictionary<string, string> pathParams,
      string contentType)
    {
      RestRequest restRequest = this.PrepareRequest(path, method, queryParams, postBody, headerParams, formParams, fileParams, pathParams, contentType);
      this.RestClient.Timeout = this.Configuration.Timeout;
      this.RestClient.UserAgent = this.Configuration.UserAgent;
      return (object) this.RestClient.Execute((IRestRequest) restRequest);
    }
```
I would like to use the `InterceptResponse` method to include these request/responses in my telemetry. This is also the only method that would easily expose the RateLimit headers for all requests. The only way I can think to currently access these methods would be to clone this repository and include the source in my project, which negates the ease of a nuget package.

**Comment by RajRele** [comment]
Hi @bgrew Good point, I will update these methods to virtual, these come from swagger-codegen so this is a nice enhancement for the community too for instance: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Client/ApiClient.cs#L40
