### ISSUE TITLE
Docusign "Could Not load file or Assembly Restsharp" Error

### ISSUE THREAD

**Issue by mia01** [docusign/docusign-csharp-client#273]
Hello,

I'm using Docusign in my (.netcore 3.1) project and I'm also using another nuget package which relies on minio. 
Both seem to rely on Restsharp.

When I try to run my app I'm getting this error:
```
System.IO.FileLoadException: 'Could not load file or assembly 'RestSharp, Version=106.3.1.0, Culture=neutral, PublicKeyToken=598062e77f915f75'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)'
```

Docusign Version: 4.4.1

This is a screenshot of the dependencies as viewed from visual studio:
![image](https://user-images.githubusercontent.com/15933995/83579723-f58f2100-a531-11ea-932b-e67a6e976216.png)

![image](https://user-images.githubusercontent.com/15933995/83579730-fe7ff280-a531-11ea-9c37-364d5c382ec1.png)

I've tried adding this binding redirect in App.Config:

```
<configuration>
  <runtime>
    <dependentAssembly>
      <assemblyIdentity name="RestSharp" publicKeyToken="598062e77f915f75" culture="neutral" />
      <bindingRedirect oldVersion="0.0.0.0-106.3.1.0" newVersion="106.10.1" />
    </dependentAssembly>
  </runtime>
</configuration>
```

This has had no impact whatsoever. Please can you help me. Any help very much appreciated! :)

**Comment by RajRele** [comment]
Hi @mia01 you are facing an existing issue with RestSharp Library compatibility. https://github.com/docusign/docusign-csharp-client/issues/101 
We are working towards a fix by this week, in the meantime you can get our source code from this git repo and update the RestSharp Dependency manually. 

We will soon update the NuGet package so that you don't have to do this workaround.

**Comment by RajRele** [comment]
Hi @mia01 please try to get a pre-release version https://www.nuget.org/packages/DocuSign.eSign.dll/4.5.0-rc and let us know if this resolves your issue?

Alternatively you can use `dotnet add package DocuSign.eSign.dll --version 4.5.0-rc`

Thanks

**Comment by RajRele** [comment]
Closing this as resolved, open a new issue if you still face this. thank you
