### ISSUE TITLE
Checkbox group validation

### ISSUE THREAD

**Issue by MaxHampton** [docusign/docusign-csharp-client#275]
I'm trying to set up groups of CheckboxTabs with selection requirements, and can't seem to get the validation part working.

I'm creating a signer for an envelope, and then assigning signer a tab collection. Tab collection contains (defined properties as sub list items):
  - SignHere 
    -AnchorString
    -AnchorUnits
    -AnchorYOffset
    -AnchorXOffset
  - FullName
    - Same as SignHere
  - DateSigned
    - Same as SignHere
  - CheckboxTabs
    -AnchorString
    -AnchorUnits
    -AnchorXOffset
    -AnchorYOffset
    -TabLabel
    -TabGroupLabels (matching a defined group), not all Checkboxes belong to a group
    -TabType
    -DocumentId
  - TabGroups
    -AnchorString
    -GroupLabel (matching some of the checkboxtabs)
    -MinimumRequired = "1"
    -MaximumAllowed = "1"
    -GroupRule = "SelectARange" (also tried SelectExactly)
    -TabType
    -DocumentId

Tabs are getting created and placed properly. However, when I go to sign the document it is not enforcing the select 1 rule I am trying to define for the checkbox groups. When I look in the document editor I can see the checkboxes and see that they are grouped, however there are no options under validation, and group label appears blank.

Are there properties that I need to be setting that I'm missing above? Are there any rules for string format of GroupLabel? Do you have a sample showing how to create checkbox groups with validation rules and apply them to a specific signer? I appreciate any help in getting this selection validation working.

I'm using the latest SDK version 4.4.1.

**Comment by LarryKlugerDS** [comment]
I apologize for the delay in my response. This type of usage question is best asked on StackOverflow with tag `docusignapi` 

My suggestion is that you set up a document with the checkboxes (and required selection rules) using the DocuSign web tool. Then either download the envelope tab definition or use the DocuSign API logging to see how the rules were implemented using the API. Remember to use v2.1 of the API.

**Comment by LarryKlugerDS** [comment]
Closing the issue due to no further comment. Please comment if you have additional questions on this issue. Thanks.
