### ISSUE TITLE
DocuSign Connect API HMAC Signing Security Flaw

### ISSUE THREAD

**Issue by CrossBound** [docusign/docusign-csharp-client#277]
The signing key for HMAC signatures appears to be a 32 byte randomly generated number, **_however_** it appears that when signing the content of the message the key is converted to bytes by using `Encoding.UTF8.GetBytes("key")` instead of `Convert.FromBase64String("key")`. 

This severely weakens the strength of the signing key by making it more vulnerable to brute force attacks. 

When converting the string representation directly back to bytes using UTF8 bytes we are simply getting the byte value of each UTF8 character which is guaranteed to always be a base64 character (`ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/`). This causes the search space for a brute force attack to be 44^64 ( a total search space of 1.51695010066444967630810858243e+105 ).

If using `Convert.FromBase64String("key")`, however, there are less bytes but 256 possible combinations per byte instead of 64 (and they are completely random). This causes the possible brute force search space to be 32^256 ( a total search space of 2.0815864389328798163850480654728e+385 ).

**Comment by LarryKlugerDS** [comment]
Hi @CrossBound , Thank you for raising this issue. 
Please confirm which SDK method you're commenting on.

For Connect webhook HMAC signatures for the notification messages, the key is generated by the DocuSign web tool. See [docs](https://developers.docusign.com/esign-rest-api/guides/connect-hmac).

Are you saying that the keys generated by the web tool are not using as large a potential key space as they could/should?

**Comment by LarryKlugerDS** [comment]
Closing. Please respond if you'd like to discuss further.
