### ISSUE TITLE
API Call - 400 Bad Request on oauth/token

### ISSUE THREAD

**Issue by vatanyadav** [docusign/docusign-csharp-client#284]
Hi,
I am using the java code to obtain the access token. When I use the configuration with a particular User ID, I am able to generate the access token and all remaining tasks work fine.

When I create a new User with same role, under same Account, I am receiving "400 Bad Request on oauth/token" error.

Both users have admin access, even the consent is provided. But no idea why for any new user, the API call fails.
On reverting to the old user, I get the expected results.

Any help would be appreciated.

<img width="1046" alt="Screenshot 2020-07-13 at 11 24 47 PM" src="https://user-images.githubusercontent.com/47236094/87336916-3aaa6800-c560-11ea-962e-f9fd68e3ae1f.png">

**Comment by LarryKlugerDS** [comment]
Ok, the next step is for you to print out the entire response object when your call fails. 
The response object will include both an error code and an error message.

Once we have the error code and message, we can figure out how to solve the problem.

Also, what OAuth flow are you using? JWT or Authorization Code grant?

**Comment by vatanyadav** [comment]
I was using the JWT.
The issue got fixed after I revoked the consent and provided the consent again.
Regarding the message, point taken.
Thank You Larry.
