### ISSUE TITLE
`ExpireAfter` and `ExpireEnabled` values not honored when creating envelopes

### ISSUE THREAD

**Issue by marchchad** [docusign/docusign-csharp-client#288]
Am trying to configure a dynamic expiration date for envelopes based on the documents being signed and need their expiry datetimes to be different than the 120 days that DocuSign defaults to.

Below is a snippet of the code used to create the envelope:
```c#
            var envelopesApi = new EnvelopesApi(ApiClient.Configuration);

            /* An Envelope is a top level container for all the data a signing flow needs */
            var envelopeDefinition = new EnvelopeDefinition
            {
                ExpireAfter = ((int)(burnPermit.BurnPermitExpirationDate - DateTime.Now).Value.TotalDays).ToString(),
                ExpireEnabled = "true",
                TemplateId = this._permitTemplateId,
                TemplateRoles = templateRoles,
                Status = "sent"
            };

            EnvelopeSummary results = await envelopesApi.CreateEnvelopeAsync(AccountID, envelopeDefinition);
```

The envelope is created successfully, however when viewing the Expire Date in the DocuSign Admin console, it is set to 12/25/2020 (120 days from today).

Using DocuSign.eSign.dll (4.1.1) in .NET Core 2.2

**Comment by marchchad** [comment]
I used Fiddler to capture this JSON that is generated by the SDK that is sent to the DocuSign API:
```json
{
    "expireAfter": "726",
    "expireEnabled": "true",
    "status": "sent",
    "templateId": "dredacted",
    "templateRoles": [
    {
        "clientUserId": "9590",
        "email": "redacted",
        "name": "redacted",
        "roleName": "Approver",
        "routingOrder": "1",
        "tabs":
        {
            "checkboxTabs": [],
            "textTabs": [
            	...,
            ]
        }
    },
    {
        "clientUserId": "redacted",
        "email": "redacted",
        "name": "redacted",
        "roleName": "Agent",
        "routingOrder": "2"
    }]
}
```

**Comment by marchchad** [comment]
So I guess this isn't an issue with the csharp client, but is maybe an issue with the DocuSign API?

**Comment by dmartin00** [comment]
The Reminder and Expiration values need to be nested under a Notifications object.
Try this:
```
Expirations expirations = new Expirations("250", "false", "5"); //ExpireAfter, Enabled, Warning
Reminders reminders = new Reminders("2", "true", "1");  //ReminderDelay, Enabled, Frequency
envelopeDefinition.Notification = new Notification(expirations, reminders, "false"); //Expirations, Reminders, UseDefaults
```
More info here: https://www.docusign.com/blog/dsdev-trenches-reminders-expirations

**Comment by marchchad** [comment]
Thanks @dmartin00, that did it. Guess the API docs and class documentation are a bit confusing since those properties are available, are settable, and seems as if they should set the expiry for the envelope.

**Comment by RajRele** [comment]
Closing this, I created a ticket for our docs team to get this confusion resolved. 
Please open a new issue if you face issues.
