### ISSUE TITLE
How to set an envelope status to Completed?

### ISSUE THREAD

**Issue by Chaitwo** [docusign/docusign-csharp-client#291]
Hello,

I have a scenario where I want to update the envelope tabs and download the envelope and update the envelope status to **Completed**.

I've successfully updated the tabs values and downloaded the envelope with the new values, but couldn't update the envelope status to **Completed**.

If the above scenario is not possible then is there any alternate way where I can add tabs to an envelope without signer and create the envelope. This way I can download the document with tabs and once the envelope is created. It'll automatically set to **Completed** Status since there is no signer.

Thanks in advance.

**Comment by LarryKlugerDS** [comment]
Hi,
DocuSign will set the status of the envelope to completed once all of the recipients have each completed their workflows.

A signer recipient is only complete when the signer has "Finished" with the signing ceremony. The API can't be used to complete an envelope, DocuSign decides when the envelope is complete.

Tabs can only be added to InPerson Signers and Signers according to the [docs](https://developers.docusign.com/docs/esign-rest-api/reference/Envelopes/EnvelopeRecipientTabs/).  

But the docs may be out of date.

And I see that a cc recipient type request can have tab attributes according to the API specification.
So I would try to create an envelope with a cc recipient and attach the tabs to the cc recipient.

If the email address for the cc recipient is a "black hole" email address, then the envelope will complete on its own. (The email must not give a bounce back message to DocuSign.)

Or you could update the document itself to have the dynamic data that you want and then send it as an envelope with DocuSign with only a cc recipient. 

Please write back and let me know what happens.
Thanks,
Larry

**Comment by Chaitwo** [comment]
Hello,
Thank you for the quick reply @LarryKlugerDS 

I will try to add tabs to cc recipient and generate an envelope from API (I couldn't add tabs without a signer when tried from the web, I see that the drag and drop functionality is disabled until I add a signer).

Will update you back once I finish trying to add tabs to cc recipient.

Thanks again,
Chaitu

**Comment by Chaitwo** [comment]
Hey @LarryKlugerDS,

Thanks a ton for the help. 

I could create a template and add tabs to the CC recipient for the template through API, then create an envelope for the template and update the tabs values for the same CC recipient and could add new tabs too. Once the envelope is generated the status is updated to complete.

Thank you for the quick and perfect solution, Larry.

Thanks,
Chaitu

**Comment by LarryKlugerDS** [comment]
Glad to help. Thank you for the follow-up. I have filed DEVDOCS-3271 to have the docs updated.
/Larry
