### ISSUE TITLE
Authentication error after upgrading from 4.5.2 to 5.x.x

### ISSUE THREAD

**Issue by StatewideAlex** [docusign/docusign-csharp-client#300]
I'm receiving the following error after upgrading `DocuSign.eSign.dll` from `4.5.2` to `5.1.0` (same result with `5.0.0`):
```
{"errorCode":"USER_AUTHENTICATION_FAILED","message":"One or both of Username and Password are invalid. Invalid access token"}
```

The only code that I had to change was during the creation of the `EnvelopesApi` object. It looks like you have to pass the full client rather than just the configuration object now.
Previous:
```csharp
_envelopesApi = new EnvelopesApi(_apiClient.Configuration);
```
New:
```csharp
_envelopesApi = new EnvelopesApi(_apiClient);
```

I *assume* that the credentials are working because it is able to retrieve the account info during the creation of the `ApiClient` object in previous steps. It also looks like the `EnvelopesApi` object has the necessary bearer token set in the authentication headers.

In case it matters, this is a custom service integration and I'm using the same demo sandbox credentials as before.

Thank you in advance!

**Comment by ivdinkov** [comment]
Try adding demo authentication server to client after the jwt generation
`_apiClient.SetOAuthBasePath("account-d.docusign.com")`

**Comment by StatewideAlex** [comment]
@ivdinkov Thank you for your suggestion, I found that it was the `BasePath` I needed to update.
