### ISSUE TITLE
Event notification configuration in case of signer authentication failure.

### ISSUE THREAD

**Issue by dmitry-lp** [docusign/docusign-csharp-client#303]
I am trying to configure the DocuSIgn connect notifications to receive notification when the signer failed to enter 3 times the SMS code. But no success. The documentation doesn't mention that but there is an option when configuring notifications in DocuSign connect interface ("Recipient authentication failure" or something like that). But how do I choose it from API? 
Original StackOverflow question: https://stackoverflow.com/questions/64551656/docusign-connect-how-to-configure-envelope-to-receive-notifications-on-authentic

**Comment by dmitry-lp** [comment]
Ok I found in the json spec that there are two not documented events AuthenticationFailed and AutoResponded hope this will work.

**Comment by dmitry-lp** [comment]
Yes! It is working!
```
envelope.EventNotification = new EventNotification()
{
    Url = _webhookUrl,
    RequireAcknowledgment = "true",
    LoggingEnabled = "true",
    IncludeEnvelopeVoidReason = "true",
    IncludeDocuments = "false",
    IncludeCertificateOfCompletion = "false",
    IncludeCertificateWithSoap = "false",
    IncludeDocumentFields = "false",
    IncludeHMAC = "true",
    IncludeSenderAccountAsCustomField = "false",
    IncludeTimeZone = "true",
    UseSoapInterface = "false",
    EnvelopeEvents = new List<EnvelopeEvent>() { 
        new EnvelopeEvent("Completed"), 
        new EnvelopeEvent("Declined"), 
        new EnvelopeEvent("Voided") 
    },
    RecipientEvents = new List<RecipientEvent>() { 
        new RecipientEvent(null, "AuthenticationFailed"), 
        new RecipientEvent(null, "Completed"), 
        new RecipientEvent(null, "Declined")
    }
};
```

**Comment by dmitry-lp** [comment]
Well actually the <RecipientAuthenticationStatus /> is empty 👎 a bug?

**Comment by ivdinkov** [comment]
Bug case was created back in June (CONNECT-1845) and our engineers are currently working to resolve the issue
