### ISSUE TITLE
Get all Templates deeply, including all their Recipients and their Recipient Tabs in one go

### ISSUE THREAD

**Issue by gjovanov** [docusign/docusign-csharp-client#310]
Hi there,
we are currently trying to load all templates in a deep-include mode, including all their Recipients and their Recipient Tabs in one go.

However, this seems to not be possible.

We can only:
1. either, first load all templates including their Recipients // here we are still mising the Tabs
2. or load templates only (without Recipients) and then for each template to load their Recipients including their Tabs // here we have too many over-the-network requests.

It would be optimal if we could load them all deeply in one go.

Any plans to support this.

Thanks.

/GJ

**Comment by dmartin00** [comment]
That's correct, DocuSign doesn't have a single method that will allow you to go wide (multiple templates) and deep (template tags). You'll need to iterate through the list and for each template make the GET call with `include=recipients,tabs`. If you have a significant number of templates, you may consider using the version of that call that returns the HTTP info so you can track the API Rate Limits (by default 1k calls per hour, and there's a burst limit of 500 calls over 30 seconds).

**Comment by gjovanov** [comment]
yes indeed we have a lot of templates over 150 per country and there are 6 countries... so doing separate HTTP requests just to include addional data, will easily reach that 1k requests per hour limit.

Ok since this is done for [company](http://jti.com/) as user of docusign API, my colleagues will probably reach out via other channels, to increase this limit.

The option to enable include on Tabs might be worth while considering...

Closing it for now... Thanks for your quick response.
