### ISSUE TITLE
Token Issue

### ISSUE THREAD

**Issue by JMatt297** [docusign/docusign-csharp-client#312]
Hi,

I am receiving the following error when trying to get userinfo with a fresh JWT token generated for the first time in a while:

2021-03-16 12:05:54,881 [66] ERROR - Error when initialising DocuSign: Error while requesting server, received a non successful HTTP code Completed with response Body: {"error":"internal_server_error","reference_id":"3b6a9d74-1fb6-48b5-aef1-d66ac4361155"} 
DocuSign.eSign.Client.ApiException: Error while requesting server, received a non successful HTTP code Completed with response Body: {"error":"internal_server_error","reference_id":"3b6a9d74-1fb6-48b5-aef1-d66ac4361155"}
   at DocuSign.eSign.Client.ApiClient.GetUserInfo(String accessToken)

...

Subsequent JWT retrievals seem to execute this method without issue (not caching the token my side), and this seems to re-occur if I try to get a JWT token a while later (i.e. after the expiry). Please can someone take a look at the reference id and let me know what the internal server error is to give me an idea on what I'm doing wrong (if anything) my side?

Many thanks

Matt

**Comment by bendowlingtech** [comment]
Hi JMatt, looks like you were getting an "EXPIRED_ACCESS_TOKEN", its strange that you say you were getting it after creating a fresh JWT assertion as this would normally happen if a previously acquired token was submitted 1 hour after creation. It looks like you managed to solve your issue though.

**Comment by JMatt297** [comment]
Hi Ben, thanks for your reply. Yeah, contrary to what I thought previously I was somehow caching the token asynchronously my side. So when it tried to get the token from DocuSign, it would keep going into the next Api call to DocuSign and fail. Subsequent requests however worked as the token came back almost immediately after the failure to be stored into my caching process asynchronously.

I'm not sure if the asynchronous functionality was being triggered by this DocuSign code (I couldn't see anything suspicious) or my custom caching code, but removing the cache resolved it so I'm looking to use the caching functionality developed by Microsoft going forward.

Thanks again for your help.
