### ISSUE TITLE
missing support for tab types, access code, brand ID

### ISSUE THREAD

**Issue by jzzheng** [docusign/docusign-csharp-client#34]
This page of the REST API Guide (https://www.docusign.com/p/RESTAPIGuide/RESTAPIGuide.htm#REST%20API%20References/Tab Parameters.htm) defines the following tabs that don't appear to be defined in this code (please correct me if I'm wrong): 

Approve, Date, Decline, Email Address, Envelope ID, First Name, Formula, Last Name, List, Note, Number, SSN, and Zip

Envelopes don't have a parameter for Brand ID (should be as simple as adding Brand ID to Envelope and EnvelopeCreate, and then setting env.brandId = this.BrandId in the Envelope's CreateJson method)

Recipients don't have parameters for accessCode or addAccessCodeToEmail (https://www.docusign.com/p/RESTAPIGuide/RESTAPIGuide.htm#REST%20API%20References/Recipients/Signers Recipient.htm)

Great project, though!

**Comment by InbarGazit** [comment]
@jzzheng thanks for the feedback. This is a collaborative effort and as you can see we had quiet a few community check-ins in the last few months. So, while I can't promise anything - either keep on checking, or if you want to contribute - we'll be happy to look at code check-ins for all or part of the missing features you outlined here and merge them as needed. We'll later release a new version of the nuget that include these updates.

**Comment by Ergin008** [comment]
@jzzheng Thanks for your feedback, we've released a new version of this client which is generated from Swagger and hence has complete object models, though not all of the API endpoints are available yet through the client.  I encourage you to take a look at the latest version as it might have all the properties you are looking for, such as `brandId`, `accessCode`, etc.  I'm closing this issue out but please feel free to file issues against the new client moving forward.

Thanks,
-Ergin
