### ISSUE TITLE
DeleteRecipient functionality missing (was: 'Mark envelope as completed or void' )

### ISSUE THREAD

**Issue by karpenberg** [docusign/docusign-csharp-client#39]
Hello again!
My question is quite specific.
For example recipient get an envelope created by template and want to sign it in old style (just print it and sign it by his hand), for our system it's ok. As the result envelope isn't completed and this recipient will receive reminders to complete envelope with some frequency. I want to prevent it. My question: Is there any way to mark envelope as completed or void it or just delete it by using client? 

I tried to use UpdateRecipients method, here it's my simple code. It returns true all them time but there's no any effect.

 public bool CompleteEnvelope(string envelopeId)
        {
            var envelope = new Envelope() { EnvelopeId = envelopeId, Login = _account };           
            envelope.GetRecipients();
            var signers = envelope.Recipients.signers;
            for (int i = 0; i < signers.Length; i++)
            {
                signers[i].status = "completed";
            }
            return envelope.UpdateRecipients(envelope.Recipients);  
        }

**Comment by InbarGazit** [comment]
in this case you have to know in advance that the user will sign on paper and set the recipient type as such. If a recipient is not set to be a paper signer than it can only be changed to complete when they actually signed

**Comment by InbarGazit** [comment]
you can correct an envelope after it was sent, but you cannot change a recipient status to complete

**Comment by Ergin008** [comment]
Yeah as Inbar mentions, if you know ahead of time if they will sign on paper can simply configure the recipient to be a paper signer.  If you do not know until ahead of time then your integration can code around that.

When it's time for them to sign your UI can ask them if they want to sign on paper on electronically.  If they chose on paper then you can delete the recipient from the envelope with the Delete Recipient API, then you can add them back at the same routingOrder using the Add Recipient API but this time configured as an on-paper signer.

**Comment by karpenberg** [comment]
Thank you for feedbacks! 
Delete recipient is the only thing I need. This functionality has not presented in client yet, so I should use SOAP API. Correct?

**Comment by InbarGazit** [comment]
@karpenberg I am pretty sure this is available in the REST API but it might not be part of the client library. This is something you can add or another developer can add in the future.

**Comment by Ergin008** [comment]
Hi @karpenberg, we've released a new (Swagger generated) version of this C# client which is a lot more complete than the previous version, though note the function signatures have changed.  The call you are looking for (Delete Recipient Call) is now available so I'm closing this issue out but feel free to log new ones if anything else comes up.  

Also, in case you want the older library see the v1.7 tag in the repo.  

Thanks,
-Ergin
