### ISSUE TITLE
Need to add anchorIgnoreIfNotPresent property

### ISSUE THREAD

**Issue by PeterAThomas** [docusign/docusign-csharp-client#4]
I pulled and added this to my version and recompiled, but it should really be a standard property. Thanks for your good work on this library, BTW! It really helped.

**Comment by InbarGazit** [comment]
thanks @PeterAThomas we will soon add this to the code. If you can share what you did - we might be able to quickly add this the same way.

**Comment by PeterAThomas** [comment]
Added this to the Tab class:

    private bool _anchorIgnoreIfNotPresent;
    public bool anchorIgnoreIfNotPresent
    {
         get { return _anchorIgnoreIfNotPresent; }
         set { _anchorIgnoreIfNotPresent = value; }
    }

You serialize the whole object so it automatically passes it into the API with no further code needed. This will prevent DocuSign from throwing an exception if an anchor is not found in a document. This is useful if you have a standard set of anchors (sign here, date here, initial here, for example) that may be in some documents but not others.

**Comment by InbarGazit** [comment]
@PeterAThomas , if you tested this and it's working ok - can you submit it as a commit/change, then we can approve it and it will get added to the code.

**Comment by InbarGazit** [comment]
@PeterAThomas  , wanted to also personally invite you to our very first developer conference to be held this coming March in San Francisco. this is exactly the opportunity to meet me and other developers in DocuSign and talk shop. And the cost is very low. See all the information here http://momentum.docusign.com/san-francisco/dev-con/?mc=devcon-github

**Comment by Ergin008** [comment]
@PeterAThomas FYI We've released a new version of this client which is generated from Swagger and hence has complete object models.  The `anchorIgnoreIfNotPresent` property is now included in the appropriate classes so I'm closing this out, feel free to file new issues if anything comes up.

Thanks,
-Ergin
