### ISSUE TITLE
Need support for Signer.tabs.listItems

### ISSUE THREAD

**Issue by AhChris** [docusign/docusign-csharp-client#40]
I think it probably just needs to be added to the Signer class, and deserialization might just work. Not sure though, it may be more complicated than that.

Is there any other way to retrieve this info? I can see it in the raw JSON response, but don't see any way to access it through the recipients collection of an envelope.

**Comment by InbarGazit** [comment]
@AhChris you are welcome to try this out and we would love if you submit tested/working code back to the repo so everyone can enjoy it. I don't think we had this request so far, so I'm not sure.

**Comment by AhChris** [comment]
I quoted the wrong collection in my original post. "listItems" is not what I was looking for, but rather "listTabs". The listItems inside are somewhat irrelevant in my scenario since I am only looking for the selected value.

I was able to get this working in my prototype by simply adding
```C#
public TextTab[] listTabs { get; set; }
```
On the Tabs Class. This works well for retrieval, but I'm not sure what kind of affect it would have if you were trying to create a document/template like this. I may play around with this and submit a patch if I can get it working with tests.

**Comment by Ergin008** [comment]
Hi @AhChris, 

We've released a new version of this client which is generated from Swagger and hence has complete object models, though not all of the API endpoints are available yet through the client.  I encourage you to take a look at the latest version as it might have all the properties you are looking for, including support for `listTabs` and such.  I'm closing this issue out but please feel free to file issues against the new client moving forward.

Thanks,
-Ergin
