### ISSUE TITLE
OAUTH?

### ISSUE THREAD

**Issue by leoseccia** [docusign/docusign-csharp-client#46]
Hello, 
Does this library support OAUTH authentication?

**Comment by InbarGazit** [comment]
@leoseccia this came up recently so I would ask you to explain what exactly are you looking for.
We have something that is "oauth-like" but not necessary fully oauth compliant in terms of the protocol we use to authenticate users to DocuSign.
If you're looking to use oauth for 3rd party authentication - we don't support it at this time.
Let me know what you have in mind and I can see if we can help you.

**Comment by leoseccia** [comment]
Hello Inbar Gazit,

Thank you for replying to me.

There are a couple of things I would like to do.

First of all, I would like our application to provide a permanent DocuSign
"connection" (until the token is revoked) to our users which persist
password changes and without the need to store their DocuSign credentials.

Secondly, I would like to let users login using Office365 or Microsoft
credentials, like in the DocuSign App for Office.

Your help is truly appreciated.

BTW: The library works pretty well. Thank you!

All the best,

Leo

On 16 September 2015 at 22:51, Inbar Gazit <notifications@github.com> wrote:

> @leoseccia <https://github.com/leoseccia> this came up recently so I
> would ask you to explain what exactly are you looking for.
> We have something that is "oauth-like" but not necessary fully oauth
> compliant in terms of the protocol we use to authenticate users to DocuSign.
> If you're looking to use oauth for 3rd party authentication - we don't
> support it at this time.
> Let me know what you have in mind and I can see if we can help you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docusign/DocuSign-.NET-Client/issues/46#issuecomment-140904865>
> .
>



-- 

Kind Regards,

Leonardo Seccia - 07904 993550


*Materialiser Ltd.*

**Comment by InbarGazit** [comment]
you can do the first but not the second with the library today.
The token which you get from the login call (ApiPassword) is what you need for all API calls and you don't need to have user authenticate more than once.

**Comment by leoseccia** [comment]
Brilliant. Thank you for letting me know.

Any suggestions on how to do the second? Do you know whether this can be
achieved using the REST service directly?

If a user joined DocuSign (as in, it created its account) using a third
party provider (Office365 or Microsoft), how would they then login to
DocuSign via my integration? Is there a way for the user to find out their
actual DocuSign credentials?

On 16 September 2015 at 23:14, Inbar Gazit <notifications@github.com> wrote:

> you can do the first but not the second with the library today.
> The token which you get from the login call (ApiPassword) is what you need
> for all API calls and you don't need to have user authenticate more than
> once.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docusign/DocuSign-.NET-Client/issues/46#issuecomment-140909977>
> .
>



-- 

Kind Regards,

Leonardo Seccia - 07904 993550


*Materialiser Ltd.*

**Comment by leoseccia** [comment]
Hello Inbar Gazit,

Any news on this? How can we support users which have signed up to the DocuSign service using a third party provider?

Thank you.

Leo

**Comment by InbarGazit** [comment]
@leoseccia do you mind sending me an email to inbar.gazit@docusign.com so I can ask you some more specific questions about your needs? thank you

**Comment by renlesterdg** [comment]
Hi @InbarGazit I also have question related to oauth. Im looking to use oauth for 3rd party authentication - office365 in particular. You mentioned earlier that you dont support it yet for the .NET  SDK, is there a way I can do it directly on rest and get back an access token?

**Comment by Ergin008** [comment]
@leoseccia @renlesterdg We now have proper OAuth functionality available in the DocuSign Demo (sandbox) environment, and it should be available in production (www) shortly after our upcoming Momentum conference (April 5-7).  

I will close this issue out for now as it has also become quite convoluted, but please feel free to log new issues if you run into anything with our new authentication paradigm.  Thanks!
