### ISSUE TITLE
Add support for Title tab with Templates

### ISSUE THREAD

**Issue by brbeaird** [docusign/docusign-csharp-client#47]
It seems like it should be possible to populate the Title field when using a template. I see it commented out in Envelope.json.cs - maybe it just needs to be finished out?

**Comment by InbarGazit** [comment]
@brbeaird I believe you're correct. 
You can try to uncomment and test it and see if it works. If you want - you can submit the enhancement yourself. We'll get to it at some point soon.

**Comment by brbeaird** [comment]
Interesting. I tried uncommenting and adding in a RoleTitleTab class with tabLabel and value (identical to the RoleTextTab class). From there, I was able to add a titleTab to my template envelope, and it seems to be getting sent along. However, I'm not really sure what's happening after that. It definitely isn't populating Title on my doc, and when I do some calls to retrieve the envelope tabs, I see 2 entries for title tabs, but neither actually has a value listed. I can't seem to find any real documentation on doing this, so it's hard to say whether or not it's something on my end or not.

Here's me adding the title role tab:
![templatetitletab](https://cloud.githubusercontent.com/assets/7239272/10000801/00ae57ee-6064-11e5-9ab1-b1c92ceace4b.PNG)

Here's the weird empty title tab that actually ends up on the signer:
![signertitletab](https://cloud.githubusercontent.com/assets/7239272/10000806/02264762-6064-11e5-9e63-adf38e4341b8.PNG)

**Comment by InbarGazit** [comment]
Brian, let see if I can confirm what you're trying to do:

you have an existing template, which is using a title tab somewhere, correct?
now, your code is trying to create a new envelope based on this template and send it, and while doing so, make sure the title is set, correct?
this is regardless of the recipient being set?
note that the title can be linked to the recipient and if that recipient is in the same account - we'll try to match and find the title previously set for that user. If this is a brand new email that is not in the account - then I believe you should be able to do what I described. I'll try to find some time later today to play with this code and see if I can get this working.

**Comment by brbeaird** [comment]
Yes, I'm setting the title tab under one of the templateRoles on that template. The templateRole is set up as a placeholder. However, the email I'm sending is a generic one (since we're doing embedded signing and not actually sending any e-mail), so I guess it's possible the system is seeing that e-mail and thinking the title has been null in the past?

**Comment by InbarGazit** [comment]
well, we have support for other tabs you can set like textTab, you can try with these to see if they work and isolate the issue. Also, if you can share your code - I can try to debug it. I was going to write a unit test that does this so it's easy to test it without UI etc.

**Comment by brbeaird** [comment]
Yeah, it's not a huge deal - I can do the same thing with textTab, which works. Honestly, my main reason for trying this was to see if I could use Title multiple places and have it populate with the same data. If it worked, I was going to basically hijack it for a different field that I needed to have repeated. This is because the default behavior of DocuSign is that if multiple fields on a document have the same data ID, only the first one is populated.

However, later yesterday I happened upon a very helpful stackoverflow post that mentioned using wildcard functionality, prefixing tab labels with //*. That also didn't seem to work, but after tweaking the C# code a bit, I was able to get it working, so I'm pretty pumped about that. 

I think the JsonConvert function was escaping the slashes, which wasn't good. My quick hack was to add this to the Envelope.cs class at the end of the CreateJson function:

output = output.Replace("\\\\", "\\");

**Comment by InbarGazit** [comment]
pretty advanced stuff @brbeaird. you sure can probably make great contributions to this library. Let us know what else we can help you with.

**Comment by Ergin008** [comment]
FYI We've released a new version of this client which is generated from Swagger and hence has complete object models, though not all of the API endpoints are available yet through the client.  I encourage you to take a look at the latest version as it might have all the properties you are looking for, including support for `titleTabs` and other tabs and properties that were missing from the previous library.  I'm closing this issue out but please feel free to file issues against the new client moving forward.

Thanks,
-Ergin
