### ISSUE TITLE
Adding custom fields to an envelope

### ISSUE THREAD

**Issue by rizwanja** [docusign/docusign-csharp-client#54]
I'm trying to follow the approach described here: http://stackoverflow.com/questions/25254516/create-docusign-envelope-with-custom-fields.

However, when I try to create custom fields for an envelope, it doesn't work and I cannot seem to find an InlineTemplate object under CompositeTemplates. 

Any tips on how it could be done? 

API documentation would work wonders in the time to come.

**Comment by InbarGazit** [comment]
@rizwanja  at current time this library doesn't support composite templates. There are a few options for you:
you can use the library for everything else and write special code for composite templates
you can get the code here and extend it to support composite templates (or at least the part you need)
or you can just not use it at all and just call APIs in some other way.
If you choose to extend, we would welcome code contributions as we have gotten some from the community already. thanks!

**Comment by Ergin008** [comment]
Hi @rizwanja, 

We've released a new version of this client which is generated from Swagger and hence has complete object models, though not all of the API endpoints are available yet through the client.  I encourage you to take a look at the latest version as things like `compositeTemplates` and other platform features are now supported.  I'm closing this issue out but please feel free to file issues against the new client moving forward.

Thanks,
-Ergin
