### ISSUE TITLE
Get All Envelopes from Inbox (Completed)

### ISSUE THREAD

**Issue by SanyoGorbunov** [docusign/docusign-csharp-client#70]
Is there any method to retrieve all envelope guids from Completed folder ? It's possible to get list of envelopes using REST API search_folders method. Searching in .NET client by this method name brought only two lines: in retrieving drafts and in retrieving count of envelopes. But no method to retrieve guids. Please advise.

**Comment by InbarGazit** [comment]
you can do that by filtering on the envelopes you get (get all and just look for complete) but I agree that your suggestion would probably be better perf. Do you want to add this?

**Comment by InbarGazit** [comment]
@SanyoGorbunov , did you look at GetAccountsEnvelopes() method (in the Envelope class) ?

**Comment by SanyoGorbunov** [comment]
Yes, thank you for your notice. I have tried GetAccountsEnvelopes() and it returned only envelopes I sent from this account (and three envelopes which I couldn't find in Sent and Completed inboxes), but there were no Completed envelopes which this account received as carbon copy receiver.

Sorry for late response. Yes, I can add this. Will ask you for some details when ready to implement this.

**Comment by InbarGazit** [comment]
ok, just a second, there may be some terminology and confusion.
"Account" refers to an enlistment with DocuSign and can have 1 or more users (members) with different email addresses. When you add a cc, you add an email address and that email would receive the doc. This is not embedded, meaning it's done outside of DocuSign via email delivery. embedded cc does not currently exist the way I think you describe it. You can see any envelope that's in your account using this API, but the envelope that was cc to your email does not go on your account (unless it was sent from the same account?). So, I'm not completely sure what you're looking for, might need a bit more clarification....

**Comment by SanyoGorbunov** [comment]
Okay, this means that I won't get cc docs from GetAccountsEnvelopes, right ? But I see these envelopes in Completed inbox (via UI), so I am looking for a method in SDK which returns all envelopes from Completed box (including cc's). These envelopes' info may be retrieved using search_folders REST API method.

**Comment by InbarGazit** [comment]
hmmm, if you see them, you should be able to get them. I wonder if you're not using the same user/account when making API calls? also, remember by default we're pointing to demo (maybe you're looking at production?) this API should give you the completed envelopes you see in the UI, so I'm not sure why it's not working exactly, if you can provide API logs - we can try to research this for you

**Comment by SanyoGorbunov** [comment]
Yes, I tried with production environment. Account is the same for API calls. I will try to make some tests on holidays and reproduce the situation on the demo environment, let you know about results. Thanks!

**Comment by Ergin008** [comment]
Hi @SanyoGorbunov, we've released a new (Swagger code-generated) version of this C# client which has complete object models and has a good portion of the API endpoints exposed.  We encourage you to try the new library to see if resolves this issue, in the mean time I'm closing this out but don't hesitate to log new issues moving forward.
