### ISSUE TITLE
Docusign-Rest client - preview the envelope

### ISSUE THREAD

**Issue by Jack0192** [docusign/docusign-csharp-client#73]
I am using rest api for docusign integration.
I am creating the envelope with multiple templates ( using composite template)and trying to preview it in readonly mode.
In my case, the the work flow goes like this... Rep ( Creates envelope and previews it in readonly mode). If everything looks good in preview, then click sent button in my App UI, which will actually sent the envelope to 3 remote recipients ( signer 1, signer2, signer3 -these are actual signers).
I am able to create and sent but not able to preview the envelope in read only mode.
1) Tried downloading the document as byte[].. but the prefill field data is missing
2) Tried by adding a previewer role to the templates and then make him as embedded user. Then created recipients view.. this again is missing the prefill data.
How to preview a created envelope in non editable mode with prefill field data?

**Comment by InbarGazit** [comment]
@Jack0192  do you have code you built for an integration and just have an issue? or are you starting now and asking what is possible? I'm asking cause composite templates are not currently supported by this library

**Comment by Jack0192** [comment]
Looks like I have posted in wrong lib.. to answer your question.. I have build a client that uses composite template...If you have any idea on preview..you can let me know.

**Comment by InbarGazit** [comment]
I'm not sure this is currently possible, I'll consult with the experts internally and see if there's such a way and update this

**Comment by Jack0192** [comment]
Thank you

**Comment by InbarGazit** [comment]
Here is a response from an expert:
"In general, the sender is the owner of the envelope.  Which means he can see (and change) everything during embedded sending.  If there's a use case for the person being the sender but not the owner, then you have to either 1.) just do a one click send and don't show them anything.  This prevents the sender from seeing (and thus changing) the envelope before it is sent, but it relies heavily on the integration getting it exactly correct, which is sometimes tricky.  2.) Make it so the sender is not the person logged in, and the person logged in is actually the first recipient, but that recipient is an different Recipient Role (like Agent, etc… this is in the documentation).  This tends to be VERY complex and confusing, however, so we don't recommend it."
