### ISSUE TITLE
NumberTabs and DateTabs Aren't Actually Tabs

### ISSUE THREAD

**Issue by joshjeppson** [docusign/docusign-csharp-client#77]
The NumberTabs and DateTabs collections aren't actually tabs like all other tab collections on the Tabs class are. They are just a list of nullable doubles and a list of nullable datetimes. This means there is no way to specify the positioning of the tabs via the library. This doesn't make sense based on the REST API documentation. I tried including links but they didn't format correctly.

**Comment by MarsMayflower** [comment]
Has there been any progress on this issue? I can't use the C# library unless I convert the fields to Text fields in our workflow, which is not an ideal solution.

**Comment by JMarlin** [comment]
This was fixed in 26648a5, but hasn't been merged into the master. Is there anyone that can poke the maintainers to pull this change?

**Comment by gsnavin** [comment]
Sorry for the delayed response.

@joshjeppson @MarsMayflower @JMarlin This issue should be resolved in version 2.1.7. Can you please give that a shot and see if that resolves your issues?

**Comment by RajRele** [comment]
Closing this as resolved. Please open a new issue incase this persists.
