### ISSUE TITLE
Async Calls Not Using Default Header

### ISSUE THREAD

**Issue by Patman0021** [docusign/docusign-csharp-client#81]
I recently started using the Async calls (specifically in the AuthenticationApi and EnvelopeApi) and it keeps throwing the following exception:

DocuSign.eSign.Client.ApiException: Error calling Login: {
  "errorCode": "PARTNER_AUTHENTICATION_FAILED",
  "message": "The specified Integrator Key was not found or is disabled. An Integrator key was not specified."
} 
...

Looking at the source, and assuming that this repo is the current version of that (since the nuget pkg is v2.0.0 and this has the source at 1.7.2), it looks like the LoginAsyncWithHttpInfo method isn't initializing the headerParams dictionary with the Configuration.DefaultHeader like LoginWithHttpInfo is.  This is only the first example, it looks like all of the subsequent async methods, (I'm assuming all of them throughout) are doing the same thing.

**Comment by tehnetaholic** [comment]
@Patman0021 thank you for writing this down, you've saved me some time. I've run into this issue as well.

**Comment by Ergin008** [comment]
Thanks @Patman0021!  You're changes have been merged into the main line, closing out.

**Comment by codingoutloud** [comment]
Related bug #96 - not sure whether this one made it into 2.0.1 NuGet push on March 7, but generally speaking would be great to have a policy of pushing to NuGet as new fixes are made.

**Comment by Patman0021** [comment]
And, now, #97
