### ISSUE TITLE
What are conditions for spawning a new Auth Token (Connected Applications)?

### ISSUE THREAD

**Issue by tehnetaholic** [docusign/docusign-csharp-client#83]
Hi!
As I'm moving our codebase to your new library I became a bit confused about your authentication mechanisms
I was wondering if you could explain me a few things, one of which is why my team is constantly spawning tokens in Connected Apps. 
Currently we use an old version of your library, the one that had "DocuSign.Integration.Client" namespace.
Here is what we currently do:
1) We prompt a user for credentials. 
2) Post credentials to https://demo.docusign.net/restapi/v2/oauth2/token and receive an auth token.
Request looks something like like this:

```
"grant_type":"password"
 "client_id":{our integrator key}
 "username":{username}
 "password":{password}
 "scope":"api",
 "token_type":"bearer" 
```

3) Store user's email as a username and an acquired token as an ApiPassword (sic!) together and use it with your old library. Note that we use a token, which is supposed to be an oAuth token, as an ApiPassword. I'm not sure that this was intended, but it works.

Now I am moving our codebase to your new library. As I understand you have 2 authentication mechanism. One is "X-DocuSign-Authentication", and another one is oAuth.
In first case one has to add a username, a password and an integrator key to every request. And in case of oAuth you simply have to add an access token to request , like `"bearer":"{access_token}". 
It seemed to me to that moving us to a genuine oAuth flow would be a good thing, so I started to work in this direction. But soon I realised, that I am confused. My whole team tends to use one DocuSign account for everyone and we run out of tokens from time to time. And I assume that your old library uses  "X-DocuSign-Authentication" mechanism, since it requests both email and password.

Your documentation says about Connected Apps list that 

> "For example, if the client application were an iPad app and the user owned two iPads, then both might appear in the list"

So, my first question is:
Could you, please, shed light on what is hiding behind this "might appear"? What are conditions for spawning a new token in case of running a Web site?

My second question is:
Would using an oAuth authentication keep spawning new tokens?

Thank you!

**Comment by Ergin008** [comment]
Hi @tehnetaholic , I'm trying to confirm the info but for now here are my responses regarding your two questions:

#1:  The text you are reading refers to the older, previous OAuth paradigm we have place.  In the REST API Guide the older auth is in the section titled:  `"DocuSign OAuth (Resource Owner Credentials or SAML)"`.  The new (standard) OAuth paradigm is listed in the section titled `"DocuSign OAuth (Authorization Code Grant or Implicit Grant)"`.  Sorry for the confusion, we're in the process of cleaning that up. 

#2:  Will confirm once I know for sure but I do not believe it spawn new tokens in the Connected Apps list of your account (and therefore go against your limit).  Haven't had time to test this yet though.

**Comment by Ergin008** [comment]
Hi @tehnetaholic, to close the loop regarding the Connected Apps question - I spoke with the team and learned that right now the new OAuth mechanism is not yet managed (hooked up to) the Connected Apps in your account, however eventually you will be able to manage through there.

The connected apps limit that you are currently observing will go away, and it would only take up 1 slot per integration, not 1 slot per access token. So an app could request many tokens but it would only show up once.

Hope this helps!

Regards,
--Ergin

**Comment by tehnetaholic** [comment]
@Ergin008 thank you for the clarification
That is good news

**Comment by RajRele** [comment]
Closing this issue.
