### ISSUE TITLE
Mixed Content: The page at  This content should also be served over HTTPS

### ISSUE THREAD

**Issue by Sandy1088** [docusign/docusign-csharp-client#85]
I am getting below error while trying to get recipientView.Url

> Mixed Content: The page at 'https://www.docusign.com/developer-center?event=ttl_expired' was loaded over HTTPS, but requested an insecure image 'http://cloudconnectors.eloqua.com/publish/content/cc.aspx?RG=20084b67-abf4-203a-59c5-c68475a2c1b2&EI=docusign&EM=IMG'. This content should also be served over HTTPS

**Comment by Sandy1088** [comment]
Please help me with the same

**Comment by LarryKlugerDS** [comment]
Hi, your problem report is not clear. Both www.docusign.com and eloqua.com are marketing sites.

You should be using demo.docusign.net for your development.

If you are re-directing your client's browser to the recipientView and you are getting the ttl_expired response, then the problem is that you're delaying too long before doing the re-direct. After you receive the url, your app must re-direct to it immediately.

**Comment by Ergin008** [comment]
@Sandy1088 Please post the exact API call(s) you are making so we can help diagnose.  I see you mention you are trying to "get" the recipientViewUrl - are you actually making a `GET`operation or are you doing a `POST`?  

If you are doing a `POST` and successfully creating the signing URL, then as Larry mentioned you might be waiting too long to access it.  Signing links, by default, have a TTL (Time-to-Life) of only 5 minutes, AND they are a one-time use only!  So if you try to access after 5 mins, or you load the URL once then try doing it again in both cases you will receive the `event=ttl_expired` error.

**Comment by Sandy1088** [comment]
Well I get the recipientViewUrl and when I try to load it in an iframe it gives below warning in developer console

> Mixed Content: The page at 'https://www.docusign.com/developer-center?event=ttl_expired' was loaded over HTTPS, but requested an insecure image 'http://cloudconnectors.eloqua.com/publish/content/cc.aspx?RG=20084b67-abf4-203a-59c5-c68475a2c1b2&EI=docusign&EM=IMG'. This content should also be served over HTTPS

which I assume is due to insecure image, I get the url fine just need to load it in an iframe

**Comment by Sandy1088** [comment]
@LarryKlugerDS Yes, I am using demo account and I am trying to load it immediately

**Comment by Sandy1088** [comment]
how do I serve 'http://cloudconnectors.eloqua.com/publish/content/cc.aspx?RG=20084b67-abf4-203a-59c5-c68475a2c1b2&EI=docusign&EM=IMG' content over HTTPS

**Comment by Sandy1088** [comment]
I had to load recipientViewUrl  in other window...and it's fine now
