### ISSUE TITLE
Missing TemplateName in Connect event payload

### ISSUE THREAD

**Issue by tehnetaholic** [docusign/docusign-csharp-client#86]
When connect sends an event, there is a node inside of EnvelopeStatus node, looking like this:
```
       <DocumentStatuses>
            <DocumentStatus>
                <ID>1</ID>
                <Name>medical_intake_form.pdf</Name>
                <TemplateName />
                <Sequence>1</Sequence>
            </DocumentStatus>
        </DocumentStatuses>
```

I'm pretty sure that TemplateName had always come up with a value.
I've tried different templates and different connect configurations - it's all the same, TemplateName is missing.

**Comment by Ergin008** [comment]
Hi @tehnetaholic , I haven't had time to test this yet but my understanding is that the `<TemplateName />` node will only have a value if the document in question was provided by a DocuSign Template in your account.  For instance, if you send a signature request on a local document that's on the sending device then it would be null, but if you sent a signature request from a server-side template then it should have a value.  

Can you confirm that the particular payload that you are examining definitely came from a DocuSign Template and was not provided at real-time?

**Comment by tehnetaholic** [comment]
Hi, @Ergin008 
I can confirm that sent envelopes were based on server-side templates. However a few days after I've noticed this issue the TemplateName property began to have value. I guess it must have been some kind of a glitch or a bug.

**Comment by Ergin008** [comment]
Ok thanks for the update and apologies for the inconsistent behavior.  Our demo is environment is relatively stable and most bugs get caught before they make it to demo, however occasionally some slip through before they are identified.

Feel free to log a new one issue if you happen to encounter this again and we'll investigate.  

Thanks,
-Ergin
