### ISSUE TITLE
NuGet Install - File Not Found

### ISSUE THREAD

**Issue by ECHDeveloper** [docusign/docusign-csharp-client#87]
After installing the Nuget package in my Winforms VB.NET application and running the project I came across an issue. When it hit the following line of code I received an error:

`Dim envDef As New EnvelopeDefinition() With {.EmailSubject = "DocuSign SDK - Please sign this doc"}`

**Error:** EnvelopeDefinition.cs not found

I had to manually locate the file in the packages folder for my project.

**More error info:**
Locating source for 'y:\Docusign\Github\DevCenter\SDKs\csharp\sdk\src\main\csharp\DocuSign\eSign\Model\EnvelopeDefinition.cs'. Checksum: MD5 {de 2b ef 57 21 9f 2f 81 87 a2 42 8f 82 f1 a7 7c}
The file 'y:\Docusign\Github\DevCenter\SDKs\csharp\sdk\src\main\csharp\DocuSign\eSign\Model\EnvelopeDefinition.cs' does not exist.
Looking in script documents for 'y:\Docusign\Github\DevCenter\SDKs\csharp\sdk\src\main\csharp\DocuSign\eSign\Model\EnvelopeDefinition.cs'...
Looking in the Edit-and-Continue directory 'C:\Users\chris.EXPRESSCORP\ECH Applications\Express Housing Manager 2012 v2 - vs2015\enc_temp_folder\'...
The file with the matching checksum was not found in the Edit-and-Continue directory.
Looking in the projects for 'y:\Docusign\Github\DevCenter\SDKs\csharp\sdk\src\main\csharp\DocuSign\eSign\Model\EnvelopeDefinition.cs'.
The file was not found in a project.
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\crt\src\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\src\mfc\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\src\atl\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include\'...
Looking in directory 'C:\'...
The debug source files settings for the active solution indicate that the debugger will not ask the user to find the file: y:\Docusign\Github\DevCenter\SDKs\csharp\sdk\src\main\csharp\DocuSign\eSign\Model\EnvelopeDefinition.cs.
The debugger could not locate the source file 'y:\Docusign\Github\DevCenter\SDKs\csharp\sdk\src\main\csharp\DocuSign\eSign\Model\EnvelopeDefinition.cs'.

**Comment by RajRele** [comment]
@ECHDeveloper sorry for delayed response.
Please get the latest package, and see if the issue persists.
I am closing this - please open a new issue if this persists for us to track better.
Thanks
