### ISSUE TITLE
DocuSign C# Client is blocked behind corporate proxy

### ISSUE THREAD

**Issue by janeski** [docusign/docusign-csharp-client#88]
When I am using the DocuSign C# Client behind a corporate proxy the RestClient (RestSharp) instance cannot authenticate itself to the proxy server and the requests to DocuSign are being blocked.
 One way to resolve this is to set the **UseDefaultCredentials** attribute  of the RestClient instance to true. However, this property is not publicly exposed in the DocuSign C# Client SDK and the default value is "false", which makes the Nuget Package unusable for this purpose.

The **UseDefaultCredentials** property enables the user account credentials to be sent along to the server ( the proxy server.) The user account is the account under which the DoCuSign Client process is running.

**Comment by LarryKlugerDS** [comment]
Thank you for your comment and PR. I will raise this issue to our engineering group.

**Comment by LarryKlugerDS** [comment]
Good news, this issue is in progress by DocuSign Engineering

**Comment by manishandankar** [comment]
What is the ETA for this? I would be eager to have this capability at the earliest. What is the workaround for this as a stop gap?
Appreciate your help on this.

**Comment by RajRele** [comment]
We have an release candidate published on Nuget https://www.nuget.org/packages/DocuSign.eSign.dll/4.1.1-rc.

You need to initialize the `ApiClient` with your WebProxy details. `WebProxy` is a optional parameter on the `ApiClient` class.
