### ISSUE TITLE
Building on .NET 4.0 - it's still possible!

### ISSUE THREAD

**Issue by brbeaird** [docusign/docusign-csharp-client#92]
I know the most recent version of this sdk "requires" .NET 4.5, but I managed to get it running on 4.0 without too much trouble. Here are the steps:

Add the code into a new C# .NET 4.0 class library project
Add a reference to System.Runtime.Serialization
Add a reference to Newtonsoft.Json (we're still way behind on version 5.0.6 but amazingly it works)
Add RestSharp via package manager (install-package RestSharp)
Add Microsoft.Bcl.Build via package manager (install-package Microsoft.BCL.Build)
Add Microsoft.Bcl.Build.Async via package manager (install-package Microsoft.Bcl.Async)

After that, things should build, and you can use the resulting dll as your 4.0-compatible version of the SDK.

If someone else out there actually cares about this and can't figure out, let me know, and maybe I can even just post either an entire pre-made solution or my own compiled dll.

**Comment by tek2hd** [comment]
i am very interested in this and am unable for some reason to get it to work on my own... any help would be appreciated it

**Comment by brbeaird** [comment]
So I needed to repeat these steps to compile on a new machine and pulling down the most recent version of the code, and this made me realize I left something out in my original steps. You need to add Microsoft.Bcl.Async (not just BCL.Build). Once you do that, it should compile.

@tek2hd  - give that try if you didn't already figure it out and are still curious about doing this.
