### ISSUE TITLE
Fix for ListTemplatesAsync apparently not in latest NuGet package

### ISSUE THREAD

**Issue by codingoutloud** [docusign/docusign-csharp-client#96]
I am experiencing a problem when calling `ListTemplatesAsync` from C# using [version 2.0.1 of the DocuSign NuGet package](https://www.nuget.org/packages/DocuSign.eSign.dll/2.0.1). The `ListTemplates` method works fine; only the async version is having a problem.

The problem is that an error is raised, even after previously establishing the X-DocuSign-Authentication header:
  "errorCode": "PARTNER_AUTHENTICATION_FAILED",
  "message": "The specified Integrator Key was not found or is disabled. An Integrator key was not specified."

But that problem appears to have been fixed in the code. I see this commit on March 2, 2016:
https://github.com/docusign/docusign-csharp-client/commit/618fdd5079a6f074b575bec7dd1d32de47bdc866

In this commit, the following is changed on line 465 which is in method `ListTemplatesAsync`:
OLD: var headerParams = new Dictionary<String, String>();
NEW:  var headerParams = new Dictionary<String, String>(Configuration.DefaultHeader);

This is an important bug fix since otherwise you will get the authentication error mentioned above.

My NuGet reference from packages.json reads:
`<package id="DocuSign.eSign.dll" version="2.0.1" targetFramework="net451" />`

And, according to https://www.nuget.org/packages/DocuSign.eSign.dll/2.0.1, this version was published on March 7, 2016, five days after the above commit.

Reverse-engineering the method in the NuGet package shows that it does not appear to contain the fix from the above commit, and the behavior is consistent with this observation.

If my analysis is correct, the NuGet package was released on March 7 without the commit from March 2, 2016.  If so, please publish an update.

**Comment by gsnavin** [comment]
@codingoutloud 
Sorry for the delay, We have published a new version with the fix applied. Please let us know if this resolves your issue.
