### ISSUE TITLE
Dynamically adding data to PDF's in DocuSign using c#.net

### ISSUE THREAD

**Issue by kranthi17** [docusign/docusign-csharp-client#99]
Hi All,

Am using DocuSign Api's for signing documents. Now I have created template in DocuSign and Uploaded the PDF's there.

Now when user click's on submit from my site, we need to auto populate docusign pdf's with data from my source code and I don't have custom fields added at docusign and it should be dynamic. Below is the code which is not working.

public string SignDocument()
{
var accountId = Login();
var url = GetRecipientDocumentUrl(accountId);
return url;
}
private string Login()
{

string authHeader = "{\"Username\":\"" + Username + "\", \"Password\":\"" + Password + "\", \"IntegratorKey\":\"" + IntegratorKey + "\"}";
DocuSign.eSign.Client.Configuration.Default.AddDefaultHeader("X-DocuSign-Authentication", authHeader);

// we will retrieve this from the login() results
string accountId = null;

// the authentication api uses the apiClient (and X-DocuSign-Authentication header) that are set in Configuration object
var authApi = new AuthenticationApi();
LoginInformation loginInfo = authApi.Login();

// find the default account for this user
foreach (LoginAccount loginAcct in loginInfo.LoginAccounts)
{
if (loginAcct.IsDefault == "true")
{
accountId = loginAcct.AccountId;
break;
}
}
if (accountId == null)
{ // if no default found set to first account
accountId = loginInfo.LoginAccounts[0].AccountId;
}
return accountId;
}
private string GetRecipientDocumentUrl(string accountId)
{
//var envelope = BuildEnvelopeDefinition(documents);
var envelope = BuildEnvelopeDefinition();
// |EnvelopesApi| contains methods related to creating and sending Envelopes (aka signature requests)
var envelopesApi = new EnvelopesApi();
//TemplateCustomFields 
var summary = envelopesApi.CreateEnvelope(accountId, envelope);
//===========================================================
// Step 3: Create Embedded Signing View (URL)
//===========================================================
var viewOptions = BuildRecipientViewRequest(envelope);
var recipientView = envelopesApi.CreateRecipientView(accountId, summary.EnvelopeId, viewOptions);
return recipientView.Url;
}

private EnvelopeDefinition BuildEnvelopeDefinition()
{

TemplateRole templateRole = new TemplateRole();
templateRole.Email = "kpothireddy@firstam.com";
templateRole.Name = "Sample";
templateRole.RoleName = "1";

templateRole.Tabs = new Tabs();
templateRole.Tabs.TextTabs = new List<Text>();
Text textTab = new Text();
textTab.TabLabel = "Approved by";
textTab.Value = "Kranthi";
//textTab.XPosition = "100";
//textTab.YPosition = "100";
templateRole.Tabs.TextTabs.Add(textTab);
templateRole.ClientUserId = Guid.NewGuid().ToString();

List<TemplateRole> rolesList = new List<TemplateRole>();
rolesList.Add(templateRole);
//rolesList.Add(templateRole1);

var envelope = new EnvelopeDefinition
{
TemplateRoles = rolesList,
//TemplateId = "3b07a774-5ec5-4bbd-928a-a4b0bace2fc5",
TemplateId = "44d25c06-4fc3-4cbe-a9d0-7e0e1e3013bc", //Prefill
Status = "sent"
};
//Envelope e = new Envelope();

return envelope;
}
private RecipientViewRequest BuildRecipientViewRequest(EnvelopeDefinition envelope)
{
RecipientViewRequest viewOptions = new RecipientViewRequest()
{
ReturnUrl = ReturnUrl,
ClientUserId = envelope.TemplateRoles.First().ClientUserId, // must match clientUserId set in step #2!
AuthenticationMethod = "email",
UserName = envelope.TemplateRoles.First().Name,
Email = envelope.TemplateRoles.First().Email
//UserName = envelope.Recipients.Signers.First().Name,
//Email = envelope.Recipients.Signers.First().Email
};
return viewOptions;
}

Could you please help me out.

**Comment by MarsMayflower** [comment]
This is the C# I am using for the service we use to initialize the transaction... maybe it can help you...

public class DocuSignStartTransactionController : ApiController
    {
        public string POST(DocuSignData data)
        {

            string Username = "7673fca0-d16e-4ee4-b41b-440a8fc82ee4";
            string Password = "Cookie762!";
            string IntegratorKey = "e005aa8e-5215-416e-b1dc-493306f81ce0";

            // set demo (aka test) environment (for production change to www.docusign.net/restapi)
            string basePath = "https://demo.docusign.net/restapi";

            // instantiate a new api client and set desired environment
            ApiClient apiClient = new ApiClient(basePath);
            Configuration cfg = new Configuration(apiClient);


            // create JSON formatted auth header containing Username, Password, and Integrator Key
            string authHeader = "{\"Username\":\"" + Username + "\", \"Password\":\"" + Password + "\", \"IntegratorKey\":\"" + IntegratorKey + "\"}";
            cfg.AddDefaultHeader("X-DocuSign-Authentication", authHeader);

            // the authentication api uses the apiClient (and X-DocuSign-Authentication header) that are set in Configuration object
            AuthenticationApi authApi = new AuthenticationApi(cfg);
            LoginInformation loginInfo = authApi.Login();

            string clientUserId = Guid.NewGuid().ToString(); //

            EnvelopeDefinition envDef = new EnvelopeDefinition();
            //envDef.EmailSubject = "API TESTING - Please sign this doc";


            // assign recipient to template role by setting name, email, and role name.  Note that the
            // template role name must match the placeholder role name saved in your account template.  
            TemplateRole tRole = new TemplateRole();
            tRole.RoleName = data.SignerRole;
            tRole.Email = data.SignerEmail;
            tRole.Name = data.SignerName;
            tRole.ClientUserId = clientUserId;

            //generate random access code
            //Random rnd = new Random();
            //tRole.AccessCode = rnd.Next(10000,99999).ToString();

            List<Text> tabsTextList = new List<Text>();
            List<Number> tabsNumberList = new List<Number>();

            if (data.TextTabs != null)
            {
                //tabs
                foreach (DocuSignTab textTab in data.TextTabs)
                {
                    Text tab = new Text();
                    //tab.Name = textTab.Name;
                    tab.TabLabel = "\\*" +  textTab.Name;
                    tab.Value = textTab.Value;
                    //tab.Shared = "true";
                    //tab.PageNumber = textTab.PageNumber;
                    //tab.DocumentId = textTab.DocumentId;
                    tabsTextList.Add(tab);
                }
            }


            Tabs tabs = new Tabs();
            tabs.TextTabs = tabsTextList;
            //tabs.NumberTabs = tabsNumberList; //C# library doesn't support the Date and Number Tab types, currently
            tRole.Tabs = tabs;

            List<TemplateRole> rolesList = new List<TemplateRole>() { tRole };

            // add the role to the envelope and assign valid templateId from your account
            envDef.TemplateRoles = rolesList;
            envDef.TemplateId = data.TemplateId;

            List<TextCustomField> customFieldsTextList = new List<TextCustomField>();

            if (data.CustomFieldsText != null)
            {
                //custom text fields
                foreach (DocuSignCustomField customField in data.CustomFieldsText)
                {
                    TextCustomField newField = new TextCustomField();
                    newField.Name = customField.Name;
                    newField.Value = customField.Value;
                    newField.Show = customField.Show;
                    newField.Required = customField.Required;

                    customFieldsTextList.Add(newField);
                }
            }

            CustomFields customFields = new CustomFields();
            customFields.TextCustomFields = customFieldsTextList;


            envDef.CustomFields = customFields;

            // set envelope status to "sent" to immediately send the signature request
            envDef.Status = "sent";

            string accountId = loginInfo.LoginAccounts[0].AccountId;

            // |EnvelopesApi| contains methods related to creating and sending Envelopes (aka signature requests)
            EnvelopesApi envelopesApi = new EnvelopesApi(cfg);
            EnvelopeSummary envelopeSummary = envelopesApi.CreateEnvelope(accountId, envDef);

            RecipientViewRequest viewOptions = new RecipientViewRequest()
            {
                ReturnUrl = data.ReturnUrl,
                ClientUserId = clientUserId,  // must match clientUserId set in step #2! 
                AuthenticationMethod = "email",
                UserName = data.SignerUserName,
                Email = data.SignerEmail
            };

            // create the recipient view (aka signing URL) 

            ViewUrl recipientView = envelopesApi.CreateRecipientView(accountId, envelopeSummary.EnvelopeId, viewOptions);

            return recipientView.Url;
        }
    }

**Comment by MarsMayflower** [comment]
public class DocuSignStartTransactionController : ApiController
    {
        public string POST(DocuSignData data)
        {

            string Username = "username";
            string Password = "password
            string IntegratorKey = "key";

            // set demo (aka test) environment (for production change to www.docusign.net/restapi)
            string basePath = "https://demo.docusign.net/restapi";

            // instantiate a new api client and set desired environment
            ApiClient apiClient = new ApiClient(basePath);
            Configuration cfg = new Configuration(apiClient);


            // create JSON formatted auth header containing Username, Password, and Integrator Key
            string authHeader = "{\"Username\":\"" + Username + "\", \"Password\":\"" + Password + "\", \"IntegratorKey\":\"" + IntegratorKey + "\"}";
            cfg.AddDefaultHeader("X-DocuSign-Authentication", authHeader);

            // the authentication api uses the apiClient (and X-DocuSign-Authentication header) that are set in Configuration object
            AuthenticationApi authApi = new AuthenticationApi(cfg);
            LoginInformation loginInfo = authApi.Login();

            string clientUserId = Guid.NewGuid().ToString(); //

            EnvelopeDefinition envDef = new EnvelopeDefinition();
            //envDef.EmailSubject = "API TESTING - Please sign this doc";


            // assign recipient to template role by setting name, email, and role name.  Note that the
            // template role name must match the placeholder role name saved in your account template.  
            TemplateRole tRole = new TemplateRole();
            tRole.RoleName = data.SignerRole;
            tRole.Email = data.SignerEmail;
            tRole.Name = data.SignerName;
            tRole.ClientUserId = clientUserId;

            //generate random access code
            //Random rnd = new Random();
            //tRole.AccessCode = rnd.Next(10000,99999).ToString();

            List<Text> tabsTextList = new List<Text>();
            List<Number> tabsNumberList = new List<Number>();

            if (data.TextTabs != null)
            {
                //tabs
                foreach (DocuSignTab textTab in data.TextTabs)
                {
                    Text tab = new Text();
                    //tab.Name = textTab.Name;
                    tab.TabLabel = "\\*" +  textTab.Name;
                    tab.Value = textTab.Value;
                    //tab.Shared = "true";
                    //tab.PageNumber = textTab.PageNumber;
                    //tab.DocumentId = textTab.DocumentId;
                    tabsTextList.Add(tab);
                }
            }


            Tabs tabs = new Tabs();
            tabs.TextTabs = tabsTextList;
            //tabs.NumberTabs = tabsNumberList; //C# library doesn't support the Date and Number Tab types, currently
            tRole.Tabs = tabs;

            List<TemplateRole> rolesList = new List<TemplateRole>() { tRole };

            // add the role to the envelope and assign valid templateId from your account
            envDef.TemplateRoles = rolesList;
            envDef.TemplateId = data.TemplateId;

            List<TextCustomField> customFieldsTextList = new List<TextCustomField>();

            if (data.CustomFieldsText != null)
            {
                //custom text fields
                foreach (DocuSignCustomField customField in data.CustomFieldsText)
                {
                    TextCustomField newField = new TextCustomField();
                    newField.Name = customField.Name;
                    newField.Value = customField.Value;
                    newField.Show = customField.Show;
                    newField.Required = customField.Required;

                    customFieldsTextList.Add(newField);
                }
            }

            CustomFields customFields = new CustomFields();
            customFields.TextCustomFields = customFieldsTextList;


            envDef.CustomFields = customFields;

            // set envelope status to "sent" to immediately send the signature request
            envDef.Status = "sent";

            string accountId = loginInfo.LoginAccounts[0].AccountId;

            // |EnvelopesApi| contains methods related to creating and sending Envelopes (aka signature requests)
            EnvelopesApi envelopesApi = new EnvelopesApi(cfg);
            EnvelopeSummary envelopeSummary = envelopesApi.CreateEnvelope(accountId, envDef);

            RecipientViewRequest viewOptions = new RecipientViewRequest()
            {
                ReturnUrl = data.ReturnUrl,
                ClientUserId = clientUserId,  // must match clientUserId set in step #2! 
                AuthenticationMethod = "email",
                UserName = data.SignerUserName,
                Email = data.SignerEmail
            };

            // create the recipient view (aka signing URL) 

            ViewUrl recipientView = envelopesApi.CreateRecipientView(accountId, envelopeSummary.EnvelopeId, viewOptions);

            return recipientView.Url;
        }
    }

**Comment by MarsMayflower** [comment]
The key is this line...

tab.TabLabel = "\\*" +  textTab.Name;

Undocumented DocuSign magic, right there.

**Comment by kranthi17** [comment]
Hi Thanks for reply,

Firstly when i create and text tab and add List<Text>, they are not showing in pdf document. would there be any restriction on login credentials because am using demo and license one?

**Comment by Ergin008** [comment]
If you are able to create the envelope but the text tabs are not showing up then it should not have anything to do with login or credentials.  

Can you capture the JSON that you're request is sending out and post it here?  You can redact any private info the request may contain.  Seeing the request body will greatly help diagnosing the issue, you can easily capture your requests by going into your Privacy settings and enabling **Request Logging**.

**Comment by MarsMayflower** [comment]
did you prefix double back slash + asterisk to the tab.TabLabel string property? You need to escape the first backslash so it needs to be two backslashes

please see code above

**Comment by MarsMayflower** [comment]
tab.TabLabel = "\*" + textTab.Name

this should actually be two backslashes but this site is removing one of the backslashes

**Comment by MarsMayflower** [comment]
dang it....  this site removes backslash....

tab.TabLabel = "\\\*" + textTab.Name;

**Comment by MarsMayflower** [comment]
so add one more backslash to that code

**Comment by kranthi17** [comment]
Hi Thanks for reply again both,

Below is the my Json object

{"templateId":"6f898104-57db-4ef1-8c74-a6cd78aa9d50","templateRoles":[{"email":"kpothireddy@ciber.com","roleName":"1","name":"Sample","clientUserId":"fffaf061-f30c-42b1-a4e8-d29878221c1e","tabs":{"textTabs":[{"value":"Kranthi","tabLabel":"\\*CustomerDetails"}]}}],"status":"sent"}

I can see there is custom control, but it is not showing in pdf file for some reason.

![error](https://cloud.githubusercontent.com/assets/20257734/16940811/e77f7ea4-4da9-11e6-875a-00304f9238b7.png)

**Comment by kranthi17** [comment]
FYI I have changed custom control name to **CustomerDetails**

**Comment by MarsMayflower** [comment]
Make sure your actual field names in Docusign don't actually include the backslashes and asterisk.

**Comment by kranthi17** [comment]
I tried without the backslashes and asterisk, still no same issue.

**Comment by MarsMayflower** [comment]
Hmmm, not sure what's going on, really. You could try using my code exactly.... here is the type I am passing to the method...

public class DocuSignData
    {
        public string SignerEmail { get; set; }
        public string SignerName { get; set; }
        public string SignerUserName { get; set; }
        public string SignerRole { get; set; }
        public string TemplateId { get; set; }
        public string ReturnUrl { get; set; }
        public List<DocuSignCustomField> CustomFieldsText { get; set; }
        public List<DocuSignTab> TextTabs { get; set; }
        public List<DocuSignTab> NumberTabs { get; set; }
        
    }

    public class DocuSignTab
    {
        public string Name { get; set; }
        public string Value { get; set; }
        public string DocumentId { get; set; }
        public string PageNumber { get; set; }
    }

    public class DocuSignCustomField
    {
        public string Name{get;set;}
        public string Value{get;set;}
        public string Required { get; set; }
        public string Show { get; set; }

    }

**Comment by LarryKlugerDS** [comment]
Thank you for using DocuSign. I'm closing out old issues that have not had any recent updates. Please re-open if the issue is still current. Thank you.
